import { Action, Realm } from '../game/types';
import { PILL_RECIPES } from './alchemy';
import { BREAKTHROUGH_RULES } from './breakthroughs';

const SMALL_QI_PILL_COST = PILL_RECIPES.small_qi_pill.requiredResources;
const STABILIZING_POWDER_COST = PILL_RECIPES.stabilizing_powder.requiredResources;
const CLEANSING_PILL_COST = PILL_RECIPES.cleansing_pill.requiredResources;
const QI_LAYER_2_COST = BREAKTHROUGH_RULES.qi_layer_2.requiredResources;
const QI_LAYER_3_COST = BREAKTHROUGH_RULES.qi_layer_3.requiredResources;
const FOUNDATION_COST = BREAKTHROUGH_RULES.foundation.requiredResources;

export const ACTIONS: Record<string, Action> = {
  kuzuo: {
    id: 'kuzuo',
    name: '枯坐',
    cost: { essence: 5 },
    output: { insight: 1 },
    cooldown: 5,
    riskProbability: 0,
    conditions: {},
  },
  tuna: {
    id: 'tuna',
    name: '吐纳',
    cost: { essence: 10 },
    output: { qi: 1 },
    cooldown: 5,
    riskProbability: 0,
    conditions: {},
  },
  caiyao: {
    id: 'caiyao',
    name: '采药',
    cost: { essence: 20 },
    output: { herbs: 1 },
    cooldown: 10,
    riskProbability: 0.1,
    conditions: {},
  },
  bianyao: {
    id: 'bianyao',
    name: '辨药',
    cost: { essence: 5, herbs: 1 },
    output: { insight: 1 },
    cooldown: 5,
    riskProbability: 0,
    conditions: {},
  },
  xunshan: {
    id: 'xunshan',
    name: '巡山',
    cost: { essence: 30 },
    output: { insight: 1, herbs: 2 },
    cooldown: 20,
    riskProbability: 0.3,
    conditions: {},
  },
  trade: {
    id: 'trade',
    name: '小买卖',
    cost: { essence: 10 },
    output: { coins: 2 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'market',
    },
  },
  gossip: {
    id: 'gossip',
    name: '听闻',
    cost: { essence: 10 },
    output: { insight: 1 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'market',
    },
  },
  sect_chore: {
    id: 'sect_chore',
    name: '外门杂务',
    cost: { essence: 20 },
    output: { coins: 1, insight: 1 },
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'outer_gate',
    },
  },
  sect_errand: {
    id: 'sect_errand',
    name: '领外门短差',
    cost: { essence: 40 },
    output: { coins: 4, herbs: 1, insight: 1 },
    cooldown: 50,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['heard_outer_gate_rules'],
      requiredLocation: 'outer_gate',
      requiredRealm: Realm.QiCondensation,
    },
  },
  sect_supply: {
    id: 'sect_supply',
    name: '领外门供给',
    cost: { essence: 20 },
    output: { herbs: 3, coins: 2 },
    cooldown: 80,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['completed_sect_errand'],
      requiredLocation: 'outer_gate',
      requiredRealm: Realm.QiCondensation,
    },
  },
  sect_roll_call: {
    id: 'sect_roll_call',
    name: '外门点卯',
    cost: { essence: 10 },
    output: { insight: 1 },
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['outer_gate_registered'],
      requiredLocation: 'outer_gate',
      requiredRealm: Realm.QiCondensation,
    },
  },
  sect_patrol: {
    id: 'sect_patrol',
    name: '领外门巡值',
    cost: { essence: 35 },
    output: { coins: 3, herbs: 1, insight: 1 },
    cooldown: 60,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['attended_outer_gate_roll_call'],
      requiredLocation: 'outer_gate',
      requiredRealm: Realm.QiCondensation,
    },
  },
  listen_lesson: {
    id: 'listen_lesson',
    name: '听课',
    cost: { essence: 15 },
    output: { insight: 1 },
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'outer_gate',
    },
  },
  tiaoxi: {
    id: 'tiaoxi',
    name: '调息',
    cost: {},
    output: { essence: 30 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {},
  },
  yinqi: {
    id: 'yinqi',
    name: '引气入体',
    cost: { qi: 15, insight: 3, essence: 30 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['completed_rike_tuna'],
      requiredLocation: 'home',
      requiredRealm: Realm.Mortal,
    },
  },
  inspect_root: {
    id: 'inspect_root',
    name: '内视灵根',
    cost: { essence: 20, insight: 1 },
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['root_known'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  attune_technique: {
    id: 'attune_technique',
    name: '按相修订',
    cost: { essence: 20, insight: 2 },
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['root_known'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  study_qi_formula: {
    id: 'study_qi_formula',
    name: '辨小丹方',
    cost: { essence: 10, herbs: 2, insight: 2 },
    output: {},
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_small_qi_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  study_steady_formula: {
    id: 'study_steady_formula',
    name: '辨稳息方',
    cost: { essence: 15, herbs: 3, insight: 3 },
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_small_qi_pill'],
      forbiddenFlags: ['known_recipe_stabilizing_powder'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  brew_qi_pill: {
    id: 'brew_qi_pill',
    name: '炼小聚气丸',
    cost: SMALL_QI_PILL_COST,
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_small_qi_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  brew_stabilizing_powder: {
    id: 'brew_stabilizing_powder',
    name: '炼稳息散',
    cost: STABILIZING_POWDER_COST,
    output: {},
    cooldown: 35,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_stabilizing_powder'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  study_cleansing_formula: {
    id: 'study_cleansing_formula',
    name: '辨清躁方',
    cost: { essence: 20, herbs: 3, insight: 4 },
    output: {},
    cooldown: 25,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_small_qi_pill'],
      forbiddenFlags: ['known_recipe_cleansing_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  brew_cleansing_pill: {
    id: 'brew_cleansing_pill',
    name: '炼清躁丸',
    cost: CLEANSING_PILL_COST,
    output: {},
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_cleansing_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  take_qi_pill: {
    id: 'take_qi_pill',
    name: '服小聚气丸',
    cost: { qiPills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_qi_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  take_stabilizing_powder: {
    id: 'take_stabilizing_powder',
    name: '服稳息散',
    cost: { stabilizingPowders: 1 },
    output: {},
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_stabilizing_powder'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  take_cleansing_pill: {
    id: 'take_cleansing_pill',
    name: '服清躁丸',
    cost: { cleansingPills: 1 },
    output: {},
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_cleansing_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  seek_foundation_guardian: {
    id: 'seek_foundation_guardian',
    name: '求护法',
    cost: { essence: 20, coins: 8, insight: 2 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['bottleneck_foundation'],
      forbiddenFlags: ['foundation_guardian', 'foundation_guardian_account_open'],
      requiredLocation: 'outer_gate',
      requiredRealm: Realm.QiCondensation,
    },
  },
  borrow_foundation_pill: {
    id: 'borrow_foundation_pill',
    name: '借丹筑基',
    cost: { coins: 12, insight: 3 },
    output: { dantoxin: 12 },
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['bottleneck_foundation'],
      forbiddenFlags: ['borrowed_foundation_aid', 'foundation_pill_debt_open'],
      requiredLocation: 'market',
      requiredRealm: Realm.QiCondensation,
    },
  },
  withdraw_foundation: {
    id: 'withdraw_foundation',
    name: '筑基收功',
    cost: { essence: 25, qi: 6 },
    output: {},
    cooldown: 80,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_foundation'],
      forbiddenFlags: ['reached_foundation'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  stabilize_bottleneck: {
    id: 'stabilize_bottleneck',
    name: '稳固关口',
    cost: { essence: 35, qi: 3, insight: 1 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  breakthrough_qi_2: {
    id: 'breakthrough_qi_2',
    name: '冲炼气二层',
    cost: QI_LAYER_2_COST,
    output: {},
    cooldown: 60,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_qi_layer_2'],
      forbiddenFlags: ['reached_qi_layer_2'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  breakthrough_qi_3: {
    id: 'breakthrough_qi_3',
    name: '冲炼气三层',
    cost: QI_LAYER_3_COST,
    output: {},
    cooldown: 70,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_qi_layer_3'],
      forbiddenFlags: ['reached_qi_layer_3'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  breakthrough_foundation: {
    id: 'breakthrough_foundation',
    name: '冲筑基',
    cost: FOUNDATION_COST,
    output: {},
    cooldown: 120,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_foundation'],
      forbiddenFlags: ['reached_foundation'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  rike_tuna: {
    id: 'rike_tuna',
    name: '日课吐纳',
    cost: { essence: 60 },
    output: { qi: 8 },
    cooldown: 50,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'home',
    },
  },
  short_retreat: {
    id: 'short_retreat',
    name: '三日闭关',
    cost: { essence: 90, qi: 2 },
    output: { qi: 26 },
    cooldown: 150,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
};
