import { Action, Realm } from '../game/types';
import { PILL_RECIPES } from './alchemy';
import { BREAKTHROUGH_RULES } from './breakthroughs';

const SMALL_QI_PILL_COST = PILL_RECIPES.small_qi_pill.requiredResources;
const STABILIZING_POWDER_COST = PILL_RECIPES.stabilizing_powder.requiredResources;
const CLEANSING_PILL_COST = PILL_RECIPES.cleansing_pill.requiredResources;
const MERIDIAN_CLEANSING_PILL_COST = PILL_RECIPES.meridian_cleansing_pill.requiredResources;
const FOUNDATION_STRENGTHENING_PILL_COST = PILL_RECIPES.foundation_strengthening_pill.requiredResources;
const SPIRIT_GATHERING_PILL_COST = PILL_RECIPES.spirit_gathering_pill.requiredResources;
const WARM_FURNACE_PILL_COST = PILL_RECIPES.warm_furnace_pill.requiredResources;
const NIGHT_SITTING_PILL_COST = PILL_RECIPES.night_sitting_pill.requiredResources;
const CLOUD_GATHERING_PILL_COST = PILL_RECIPES.cloud_gathering_pill.requiredResources;
const IRON_BODY_PILL_COST = PILL_RECIPES.iron_body_pill.requiredResources;
const DEMON_BANE_PILL_COST = PILL_RECIPES.demon_bane_pill.requiredResources;
const FOUNDATION_EXPLOSION_PILL_COST = PILL_RECIPES.foundation_explosion_pill.requiredResources;
const SPIRIT_VEIN_PILL_COST = PILL_RECIPES.spirit_vein_pill.requiredResources;
const SHADOW_ESCAPE_PILL_COST = PILL_RECIPES.shadow_escape_pill.requiredResources;
const LONGEVITY_PILL_COST = PILL_RECIPES.longevity_pill.requiredResources;
const FIRE_FURNACE_PILL_COST = PILL_RECIPES.fire_furnace_pill.requiredResources;
const NINE_TURN_FOUNDATION_PILL_COST = PILL_RECIPES.nine_turn_foundation_pill.requiredResources;
const BUDDHA_HEART_PILL_COST = PILL_RECIPES.buddha_heart_pill.requiredResources;
const GOLDEN_CORE_FORMATION_PILL_COST = PILL_RECIPES.golden_core_formation_pill.requiredResources;
const GOLDEN_CORE_STRENGTHENING_PILL_COST = PILL_RECIPES.golden_core_strengthening_pill.requiredResources;
const GOLDEN_CORE_FIRE_PILL_COST = PILL_RECIPES.golden_core_fire_pill.requiredResources;
const NASCENT_SOUL_NURTURING_PILL_COST = PILL_RECIPES.nascent_soul_nurturing_pill.requiredResources;
const NASCENT_SOUL_SEPARATION_PILL_COST = PILL_RECIPES.nascent_soul_separation_pill.requiredResources;
const NASCENT_SOUL_PROTECTION_PILL_COST = PILL_RECIPES.nascent_soul_protection_pill.requiredResources;
const SPIRIT_TRANSFORM_PILL_COST = PILL_RECIPES.spirit_transform_pill.requiredResources;
const SPIRIT_TRANSFORM_FIRE_PILL_COST = PILL_RECIPES.spirit_transform_fire_pill.requiredResources;
const INTEGRATION_PILL_COST = PILL_RECIPES.integration_pill.requiredResources;
const INTEGRATION_BODY_PILL_COST = PILL_RECIPES.integration_body_pill.requiredResources;
const MAHAYANA_PILL_COST = PILL_RECIPES.mahayana_pill.requiredResources;
const MAHAYANA_ENLIGHTENMENT_PILL_COST = PILL_RECIPES.mahayana_enlightenment_pill.requiredResources;
const TRIBULATION_PROTECTION_PILL_COST = PILL_RECIPES.tribulation_protection_pill.requiredResources;
const HEAVENLY_TRIBULATION_PILL_COST = PILL_RECIPES.heavenly_tribulation_pill.requiredResources;
const TRIBULATION_SOUL_PILL_COST = PILL_RECIPES.tribulation_soul_pill.requiredResources;

const QI_LAYER_2_COST = BREAKTHROUGH_RULES.qi_layer_2.requiredResources;
const QI_LAYER_3_COST = BREAKTHROUGH_RULES.qi_layer_3.requiredResources;
const QI_LAYER_4_COST = BREAKTHROUGH_RULES.qi_layer_4.requiredResources;
const QI_LAYER_5_COST = BREAKTHROUGH_RULES.qi_layer_5.requiredResources;
const QI_LAYER_6_COST = BREAKTHROUGH_RULES.qi_layer_6.requiredResources;
const QI_LAYER_7_COST = BREAKTHROUGH_RULES.qi_layer_7.requiredResources;
const QI_LAYER_8_COST = BREAKTHROUGH_RULES.qi_layer_8.requiredResources;
const QI_LAYER_9_COST = BREAKTHROUGH_RULES.qi_layer_9.requiredResources;
const FOUNDATION_COST = BREAKTHROUGH_RULES.foundation.requiredResources;
const GOLDEN_CORE_COST = BREAKTHROUGH_RULES.golden_core.requiredResources;
const NASCENT_SOUL_COST = BREAKTHROUGH_RULES.nascent_soul.requiredResources;
const SPIRIT_TRANSFORMATION_COST = BREAKTHROUGH_RULES.spirit_transformation.requiredResources;
const INTEGRATION_COST = BREAKTHROUGH_RULES.integration.requiredResources;
const MAHAYANA_COST = BREAKTHROUGH_RULES.mahayana.requiredResources;
const TRIBULATION_COST = BREAKTHROUGH_RULES.tribulation.requiredResources;

export const ACTIONS: Record<string, Action> = {
  kuzuo: {
    id: 'kuzuo',
    name: '枯坐',
    cost: { essence: 5 },
    output: { insight: 1 },
    cooldown: 5,
    riskProbability: 0,
    conditions: {},
  },
  tuna: {
    id: 'tuna',
    name: '吐纳',
    cost: { essence: 10 },
    output: { qi: 1 },
    cooldown: 5,
    riskProbability: 0,
    conditions: {},
  },
  caiyao: {
    id: 'caiyao',
    name: '采药',
    cost: { essence: 20 },
    output: { herbs: 1 },
    cooldown: 10,
    riskProbability: 0.1,
    conditions: {},
  },
  bianyao: {
    id: 'bianyao',
    name: '辨药',
    cost: { essence: 5, herbs: 1 },
    output: { insight: 1 },
    cooldown: 5,
    riskProbability: 0,
    conditions: {},
  },
  xunshan: {
    id: 'xunshan',
    name: '巡山',
    cost: { essence: 30 },
    output: { insight: 1, herbs: 2 },
    cooldown: 20,
    riskProbability: 0.3,
    conditions: {},
  },
  trade: {
    id: 'trade',
    name: '小买卖',
    cost: { essence: 10 },
    output: { coins: 2 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'market',
    },
  },
  gossip: {
    id: 'gossip',
    name: '听闻',
    cost: { essence: 10 },
    output: { insight: 1 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'market',
    },
  },
  sect_chore: {
    id: 'sect_chore',
    name: '外门杂务',
    cost: { essence: 20 },
    output: { coins: 1, insight: 1 },
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'outer_gate',
    },
  },
  sect_errand: {
    id: 'sect_errand',
    name: '领外门短差',
    cost: { essence: 40 },
    output: { coins: 4, herbs: 1, insight: 1 },
    cooldown: 50,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['heard_outer_gate_rules'],
      requiredLocation: 'outer_gate',
      requiredRealm: Realm.QiCondensation,
    },
  },
  sect_supply: {
    id: 'sect_supply',
    name: '领外门供给',
    cost: { essence: 20 },
    output: { herbs: 3, coins: 2 },
    cooldown: 80,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['completed_sect_errand'],
      requiredLocation: 'outer_gate',
      requiredRealm: Realm.QiCondensation,
    },
  },
  sect_roll_call: {
    id: 'sect_roll_call',
    name: '外门点卯',
    cost: { essence: 10 },
    output: { insight: 1 },
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['outer_gate_registered'],
      requiredLocation: 'outer_gate',
      requiredRealm: Realm.QiCondensation,
    },
  },
  sect_patrol: {
    id: 'sect_patrol',
    name: '领外门巡值',
    cost: { essence: 35 },
    output: { coins: 3, herbs: 1, insight: 1 },
    cooldown: 60,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['attended_outer_gate_roll_call'],
      requiredLocation: 'outer_gate',
      requiredRealm: Realm.QiCondensation,
    },
  },
  listen_lesson: {
    id: 'listen_lesson',
    name: '听课',
    cost: { essence: 15 },
    output: { insight: 1 },
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'outer_gate',
    },
  },
  tiaoxi: {
    id: 'tiaoxi',
    name: '调息',
    cost: {},
    output: { essence: 30 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {},
  },
  yinqi: {
    id: 'yinqi',
    name: '引气入体',
    cost: { qi: 15, insight: 3, essence: 30 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['completed_rike_tuna'],
      requiredLocation: 'home',
      requiredRealm: Realm.Mortal,
    },
  },
  inspect_root: {
    id: 'inspect_root',
    name: '内视灵根',
    cost: { essence: 20, insight: 1 },
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['root_known'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  attune_technique: {
    id: 'attune_technique',
    name: '按相修订',
    cost: { essence: 20, insight: 2 },
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['root_known'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  study_qi_formula: {
    id: 'study_qi_formula',
    name: '辨小丹方',
    cost: { essence: 10, herbs: 2, insight: 2 },
    output: {},
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_small_qi_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  study_steady_formula: {
    id: 'study_steady_formula',
    name: '辨稳息方',
    cost: { essence: 15, herbs: 3, insight: 3 },
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_small_qi_pill'],
      forbiddenFlags: ['known_recipe_stabilizing_powder'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  brew_qi_pill: {
    id: 'brew_qi_pill',
    name: '炼小聚气丸',
    cost: SMALL_QI_PILL_COST,
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_small_qi_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  brew_stabilizing_powder: {
    id: 'brew_stabilizing_powder',
    name: '炼稳息散',
    cost: STABILIZING_POWDER_COST,
    output: {},
    cooldown: 35,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_stabilizing_powder'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  study_cleansing_formula: {
    id: 'study_cleansing_formula',
    name: '辨清躁方',
    cost: { essence: 20, herbs: 3, insight: 4 },
    output: {},
    cooldown: 25,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_small_qi_pill'],
      forbiddenFlags: ['known_recipe_cleansing_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  brew_cleansing_pill: {
    id: 'brew_cleansing_pill',
    name: '炼清躁丸',
    cost: CLEANSING_PILL_COST,
    output: {},
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_cleansing_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  take_qi_pill: {
    id: 'take_qi_pill',
    name: '服小聚气丸',
    cost: { qiPills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_qi_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  take_stabilizing_powder: {
    id: 'take_stabilizing_powder',
    name: '服稳息散',
    cost: { stabilizingPowders: 1 },
    output: {},
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_stabilizing_powder'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  take_cleansing_pill: {
    id: 'take_cleansing_pill',
    name: '服清躁丸',
    cost: { cleansingPills: 1 },
    output: {},
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_cleansing_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  seek_foundation_guardian: {
    id: 'seek_foundation_guardian',
    name: '求护法',
    cost: { essence: 20, coins: 8, insight: 2 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['bottleneck_foundation'],
      forbiddenFlags: ['foundation_guardian', 'foundation_guardian_account_open'],
      requiredLocation: 'outer_gate',
      requiredRealm: Realm.QiCondensation,
    },
  },
  borrow_foundation_pill: {
    id: 'borrow_foundation_pill',
    name: '借丹筑基',
    cost: { coins: 12, insight: 3 },
    output: { dantoxin: 12 },
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['bottleneck_foundation'],
      forbiddenFlags: ['borrowed_foundation_aid', 'foundation_pill_debt_open'],
      requiredLocation: 'market',
      requiredRealm: Realm.QiCondensation,
    },
  },
  withdraw_foundation: {
    id: 'withdraw_foundation',
    name: '筑基收功',
    cost: { essence: 25, qi: 6 },
    output: {},
    cooldown: 80,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_foundation'],
      forbiddenFlags: ['reached_foundation'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  stabilize_bottleneck: {
    id: 'stabilize_bottleneck',
    name: '稳固关口',
    cost: { essence: 35, qi: 3, insight: 1 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
    },
  },
  breakthrough_qi_2: {
    id: 'breakthrough_qi_2',
    name: '冲炼气二层',
    cost: QI_LAYER_2_COST,
    output: {},
    cooldown: 60,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_qi_layer_2'],
      forbiddenFlags: ['reached_qi_layer_2'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  breakthrough_qi_3: {
    id: 'breakthrough_qi_3',
    name: '冲炼气三层',
    cost: QI_LAYER_3_COST,
    output: {},
    cooldown: 70,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_qi_layer_3'],
      forbiddenFlags: ['reached_qi_layer_3'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  breakthrough_qi_4: {
    id: 'breakthrough_qi_4',
    name: '冲炼气四层',
    cost: QI_LAYER_4_COST,
    output: {},
    cooldown: 80,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_qi_layer_4'],
      forbiddenFlags: ['reached_qi_layer_4'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  breakthrough_qi_5: {
    id: 'breakthrough_qi_5',
    name: '冲炼气五层',
    cost: QI_LAYER_5_COST,
    output: {},
    cooldown: 90,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_qi_layer_5'],
      forbiddenFlags: ['reached_qi_layer_5'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  breakthrough_qi_6: {
    id: 'breakthrough_qi_6',
    name: '冲炼气六层',
    cost: QI_LAYER_6_COST,
    output: {},
    cooldown: 100,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_qi_layer_6'],
      forbiddenFlags: ['reached_qi_layer_6'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  breakthrough_qi_7: {
    id: 'breakthrough_qi_7',
    name: '冲炼气七层',
    cost: QI_LAYER_7_COST,
    output: {},
    cooldown: 110,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_qi_layer_7'],
      forbiddenFlags: ['reached_qi_layer_7'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  breakthrough_qi_8: {
    id: 'breakthrough_qi_8',
    name: '冲炼气八层',
    cost: QI_LAYER_8_COST,
    output: {},
    cooldown: 120,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_qi_layer_8'],
      forbiddenFlags: ['reached_qi_layer_8'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  breakthrough_qi_9: {
    id: 'breakthrough_qi_9',
    name: '冲炼气九层',
    cost: QI_LAYER_9_COST,
    output: {},
    cooldown: 130,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_qi_layer_9'],
      forbiddenFlags: ['reached_qi_layer_9'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  breakthrough_foundation: {
    id: 'breakthrough_foundation',
    name: '冲筑基',
    cost: FOUNDATION_COST,
    output: {},
    cooldown: 120,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_foundation'],
      forbiddenFlags: ['reached_foundation'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  rike_tuna: {
    id: 'rike_tuna',
    name: '日课吐纳',
    cost: { essence: 60 },
    output: { qi: 8 },
    cooldown: 50,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'home',
    },
  },
  short_retreat: {
    id: 'short_retreat',
    name: '三日闭关',
    cost: { essence: 90, qi: 2 },
    output: { qi: 26 },
    cooldown: 150,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  foundation_daily_practice: {
    id: 'foundation_daily_practice',
    name: '筑基日课',
    cost: { essence: 25 },
    output: { qi: 6, insight: 1 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.FoundationEstablishment,
      requiredFlags: ['foundation_morning_seen'],
      forbiddenFlags: [],
    },
  },
  inner_gate_rumor: {
    id: 'inner_gate_rumor',
    name: '内门传闻',
    cost: { essence: 10 },
    output: { insight: 3 },
    cooldown: 8,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'outer_gate',
    },
  },
  foundation_meditation: {
    id: 'foundation_meditation',
    name: '筑基静修',
    cost: { essence: 50, herbs: 2 },
    output: { qi: 12, insight: 2 },
    cooldown: 30,
    riskProbability: 0.05,
    conditions: {
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  study_meridian_cleansing_formula: {
    id: 'study_meridian_cleansing_formula',
    name: '辨通脉方',
    cost: { essence: 25, herbs: 4, insight: 5 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_meridian_cleansing_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  brew_meridian_cleansing_pill: {
    id: 'brew_meridian_cleansing_pill',
    name: '炼通脉丸',
    cost: MERIDIAN_CLEANSING_PILL_COST,
    output: {},
    cooldown: 50,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_meridian_cleansing_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  take_meridian_cleansing_pill: {
    id: 'take_meridian_cleansing_pill',
    name: '服通脉丸',
    cost: { meridianCleansingPills: 1 },
    output: {},
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_meridian_cleansing_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  study_foundation_strengthening_formula: {
    id: 'study_foundation_strengthening_formula',
    name: '辨固基方',
    cost: { essence: 20, herbs: 3, insight: 4 },
    output: {},
    cooldown: 25,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_foundation_strengthening_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  brew_foundation_strengthening_pill: {
    id: 'brew_foundation_strengthening_pill',
    name: '炼固基丹',
    cost: FOUNDATION_STRENGTHENING_PILL_COST,
    output: {},
    cooldown: 45,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_foundation_strengthening_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  take_foundation_strengthening_pill: {
    id: 'take_foundation_strengthening_pill',
    name: '服固基丹',
    cost: { foundationStrengtheningPills: 1 },
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_foundation_strengthening_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  study_spirit_gathering_formula: {
    id: 'study_spirit_gathering_formula',
    name: '辨聚灵方',
    cost: { essence: 20, herbs: 3, insight: 4 },
    output: {},
    cooldown: 25,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_spirit_gathering_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  brew_spirit_gathering_pill: {
    id: 'brew_spirit_gathering_pill',
    name: '炼聚灵丸',
    cost: SPIRIT_GATHERING_PILL_COST,
    output: {},
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_spirit_gathering_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  take_spirit_gathering_pill: {
    id: 'take_spirit_gathering_pill',
    name: '服聚灵丸',
    cost: { spiritGatheringPills: 1 },
    output: {},
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_spirit_gathering_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  // F4: Sect deepening actions
  inner_gate_task: {
    id: 'inner_gate_task',
    name: '领内门任务',
    cost: { essence: 30 },
    output: { coins: 2, insight: 1 },
    cooldown: 60,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'inner_gate',
      requiredFlags: ['sect_rank_inner'],
    },
  },
  report_task_completion: {
    id: 'report_task_completion',
    name: '复命',
    cost: { essence: 10 },
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'inner_gate',
      requiredFlags: ['has_active_sect_task'],
    },
  },
  attend_sect_ceremony: {
    id: 'attend_sect_ceremony',
    name: '参加宗门典礼',
    cost: { essence: 15 },
    output: { insight: 5 },
    cooldown: 100,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'inner_gate',
      requiredFlags: ['sect_rank_inner'],
    },
  },
  // F5: Dwelling actions
  establish_dwelling: {
    id: 'establish_dwelling',
    name: '开辟洞府',
    cost: { coins: 20, herbs: 5 },
    output: {},
    cooldown: 100,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.FoundationEstablishment,
    },
  },
  upgrade_dwelling: {
    id: 'upgrade_dwelling',
    name: '扩建洞府',
    cost: { coins: 50, herbs: 10, insight: 5 },
    output: {},
    cooldown: 150,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['dwelling_level_1'],
    },
  },
  install_formation: {
    id: 'install_formation',
    name: '布阵',
    cost: { coins: 30, insight: 8 },
    output: {},
    cooldown: 200,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['dwelling_level_2'],
    },
  },
  // F6: Market deeper actions
  open_market_stall: {
    id: 'open_market_stall',
    name: '开摊',
    cost: { coins: 10, herbs: 5 },
    output: { coins: 8, insight: 1 },
    cooldown: 80,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'market',
    },
  },
  buy_rare_herbs: {
    id: 'buy_rare_herbs',
    name: '买珍药',
    cost: { coins: 15 },
    output: { herbs: 5 },
    cooldown: 60,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'market',
    },
  },
  // F7: Follower actions
  recruit_servant: {
    id: 'recruit_servant',
    name: '招杂役',
    cost: { coins: 15 },
    output: {},
    cooldown: 200,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'home',
      requiredFlags: ['dwelling_level_1'],
    },
  },
  recruit_disciple: {
    id: 'recruit_disciple',
    name: '收弟子',
    cost: { coins: 25, insight: 3 },
    output: {},
    cooldown: 300,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
      requiredFlags: ['dwelling_level_2'],
    },
  },
  recruit_guard: {
    id: 'recruit_guard',
    name: '招护卫',
    cost: { coins: 20 },
    output: {},
    cooldown: 250,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'home',
      requiredFlags: ['dwelling_level_2'],
    },
  },
  assign_herb_gathering: {
    id: 'assign_herb_gathering',
    name: '派采药',
    cost: {},
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'home',
      requiredFlags: ['has_follower'],
    },
  },
  assign_patrol_duty: {
    id: 'assign_patrol_duty',
    name: '派巡山',
    cost: {},
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'home',
      requiredFlags: ['has_follower', 'sect_rank_outer'],
    },
  },
  collect_follower_income: {
    id: 'collect_follower_income',
    name: '收杂役成果',
    cost: {},
    output: {},
    cooldown: 50,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'home',
      requiredFlags: ['has_follower'],
    },
  },
  // F8: Secret Realm actions
  explore_secret_realm: {
    id: 'explore_secret_realm',
    name: '探索秘境',
    cost: { essence: 50 },
    output: {},
    cooldown: 200,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'home',
      requiredFlags: ['has_discovered_realm'],
    },
  },
  continue_exploration: {
    id: 'continue_exploration',
    name: '深入探索',
    cost: { essence: 30, qi: 5 },
    output: {},
    cooldown: 50,
    riskProbability: 0.15,
    conditions: {
      requiredFlags: ['exploring_secret_realm'],
    },
  },
  claim_exploration_loot: {
    id: 'claim_exploration_loot',
    name: '收取探索成果',
    cost: {},
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['exploration_complete'],
    },
  },
  abandon_exploration: {
    id: 'abandon_exploration',
    name: '放弃探索',
    cost: {},
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['exploring_secret_realm'],
    },
  },
  meditate_detox: {
    id: 'meditate_detox',
    name: '静坐逼毒',
    cost: { essence: 40 },
    output: { dantoxin: -3 },
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      minResources: { dantoxin: 10, essence: 40 },
      requiredFlags: ['entered_qi_condensation'],
      forbiddenFlags: [],
    },
  },
  // F9: Ascension actions
  attempt_ascension: {
    id: 'attempt_ascension',
    name: '尝试飞升',
    cost: { qi: 200 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.NascentSoul,
    },
  },
  // F9: GoldenCore and NascentSoul practice
  golden_core_practice: {
    id: 'golden_core_practice',
    name: '金丹日课',
    cost: { essence: 30 },
    output: { qi: 10, insight: 2 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.GoldenCore,
    },
  },
  nascent_soul_practice: {
    id: 'nascent_soul_practice',
    name: '元婴日课',
    cost: { essence: 40 },
    output: { qi: 15, insight: 3 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.NascentSoul,
    },
  },
  // F9: GoldenCore and NascentSoul breakthrough actions
  breakthrough_golden_core: {
    id: 'breakthrough_golden_core',
    name: '冲金丹',
    cost: GOLDEN_CORE_COST,
    output: {},
    cooldown: 200,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_golden_core'],
      forbiddenFlags: ['reached_golden_core'],
      requiredLocation: 'home',
      requiredRealm: Realm.FoundationEstablishment,
    },
  },
  breakthrough_nascent_soul: {
    id: 'breakthrough_nascent_soul',
    name: '冲元婴',
    cost: NASCENT_SOUL_COST,
    output: {},
    cooldown: 300,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_nascent_soul'],
      forbiddenFlags: ['reached_nascent_soul'],
      requiredLocation: 'home',
      requiredRealm: Realm.GoldenCore,
    },
  },
  // New realm practice actions
  spirit_transformation_practice: {
    id: 'spirit_transformation_practice',
    name: '化神日课',
    cost: { essence: 50 },
    output: { qi: 20, insight: 4 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.SpiritTransformation,
    },
  },
  integration_practice: {
    id: 'integration_practice',
    name: '合体日课',
    cost: { essence: 60 },
    output: { qi: 25, insight: 5 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.Integration,
    },
  },
  mahayana_practice: {
    id: 'mahayana_practice',
    name: '大乘日课',
    cost: { essence: 70 },
    output: { qi: 30, insight: 6 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.Mahayana,
    },
  },
  tribulation_practice: {
    id: 'tribulation_practice',
    name: '渡劫日课',
    cost: { essence: 80 },
    output: { qi: 40, insight: 8 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.Tribulation,
    },
  },
  // New realm breakthrough actions
  breakthrough_spirit_transformation: {
    id: 'breakthrough_spirit_transformation',
    name: '冲化神',
    cost: SPIRIT_TRANSFORMATION_COST,
    output: {},
    cooldown: 400,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_spirit_transformation'],
      forbiddenFlags: ['reached_spirit_transformation'],
      requiredLocation: 'home',
      requiredRealm: Realm.NascentSoul,
    },
  },
  breakthrough_integration: {
    id: 'breakthrough_integration',
    name: '冲合体',
    cost: INTEGRATION_COST,
    output: {},
    cooldown: 500,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_integration'],
      forbiddenFlags: ['reached_integration'],
      requiredLocation: 'home',
      requiredRealm: Realm.SpiritTransformation,
    },
  },
  breakthrough_mahayana: {
    id: 'breakthrough_mahayana',
    name: '冲大乘',
    cost: MAHAYANA_COST,
    output: {},
    cooldown: 600,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_mahayana'],
      forbiddenFlags: ['reached_mahayana'],
      requiredLocation: 'home',
      requiredRealm: Realm.Integration,
    },
  },
  breakthrough_tribulation: {
    id: 'breakthrough_tribulation',
    name: '冲渡劫',
    cost: TRIBULATION_COST,
    output: {},
    cooldown: 800,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_tribulation'],
      forbiddenFlags: ['reached_tribulation'],
      requiredLocation: 'home',
      requiredRealm: Realm.Mahayana,
    },
  },
  // New location actions
  water_meditation: {
    id: 'water_meditation',
    name: '溪边静坐',
    cost: { essence: 15 },
    output: { qi: 2, insight: 1 },
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'stream_valley',
    },
  },
  collect_night_dew: {
    id: 'collect_night_dew',
    name: '收夜露',
    cost: { essence: 10 },
    output: { herbs: 2 },
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'stream_valley',
    },
  },
  explore_ruins: {
    id: 'explore_ruins',
    name: '探查废观',
    cost: { essence: 20 },
    output: { insight: 2 },
    cooldown: 25,
    riskProbability: 0.1,
    conditions: {
      requiredLocation: 'abandoned_temple',
    },
  },
  sweep_temple: {
    id: 'sweep_temple',
    name: '清扫殿宇',
    cost: { essence: 10 },
    output: { insight: 1 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'abandoned_temple',
    },
  },
  read_stone_tablet: {
    id: 'read_stone_tablet',
    name: '读石碑',
    cost: { essence: 15, insight: 2 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'abandoned_temple',
      requiredFlags: ['found_jade_slip'],
    },
  },
  identify_herb: {
    id: 'identify_herb',
    name: '辨药性',
    cost: { essence: 5, herbs: 2 },
    output: { insight: 2 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'herb_slope',
    },
  },
  protect_seedling: {
    id: 'protect_seedling',
    name: '护苗',
    cost: { essence: 10, herbs: 1 },
    output: {},
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'herb_slope',
      requiredFlags: ['marked_herb_patch'],
    },
  },
  listen_traveler: {
    id: 'listen_traveler',
    name: '听客谈',
    cost: { essence: 10 },
    output: { insight: 2 },
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'ferry_crossing',
    },
  },
  hire_boat: {
    id: 'hire_boat',
    name: '雇船出行',
    cost: { coins: 5, essence: 20 },
    output: { insight: 3 },
    cooldown: 40,
    riskProbability: 0.1,
    conditions: {
      requiredLocation: 'ferry_crossing',
    },
  },
  // New alchemy actions: warm furnace pill
  study_warm_furnace_formula: {
    id: 'study_warm_furnace_formula',
    name: '辨暖炉方',
    cost: { essence: 20, herbs: 3, insight: 3 },
    output: {},
    cooldown: 25,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_warm_furnace_pill'],
      requiredRealm: Realm.QiCondensation,
      requiredLocation: 'home',
    },
  },
  brew_warm_furnace_pill: {
    id: 'brew_warm_furnace_pill',
    name: '炼暖炉丹',
    cost: WARM_FURNACE_PILL_COST,
    output: {},
    cooldown: 35,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_warm_furnace_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  take_warm_furnace_pill: {
    id: 'take_warm_furnace_pill',
    name: '服暖炉丹',
    cost: { warmFurnacePills: 1 },
    output: {},
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_warm_furnace_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
  // New alchemy actions: night sitting pill
  study_night_sitting_formula: {
    id: 'study_night_sitting_formula',
    name: '辨夜坐方',
    cost: { essence: 25, herbs: 4, insight: 5 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_night_sitting_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  brew_night_sitting_pill: {
    id: 'brew_night_sitting_pill',
    name: '炼夜坐丸',
    cost: NIGHT_SITTING_PILL_COST,
    output: {},
    cooldown: 45,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_night_sitting_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  take_night_sitting_pill: {
    id: 'take_night_sitting_pill',
    name: '服夜坐丸',
    cost: { nightSittingPills: 1 },
    output: {},
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_night_sitting_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  // === New location-specific actions ===
  // Spirit Field actions
  plant_herb: {
    id: 'plant_herb',
    name: '种药',
    cost: { herbs: 1, essence: 5 },
    output: { insight: 1 },
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'spirit_field',
    },
  },
  harvest_herb: {
    id: 'harvest_herb',
    name: '收药',
    cost: { essence: 5 },
    output: { herbs: 3 },
    cooldown: 3,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'spirit_field',
    },
  },
  tend_field: {
    id: 'tend_field',
    name: '照料灵田',
    cost: { essence: 3 },
    output: { herbs: 1, insight: 1 },
    cooldown: 2,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'spirit_field',
    },
  },
  // Pill Hall actions
  use_furnace: {
    id: 'use_furnace',
    name: '借炉炼丹',
    cost: { coins: 5, essence: 10 },
    output: { insight: 2 },
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'pill_hall',
    },
  },
  study_advanced_formula: {
    id: 'study_advanced_formula',
    name: '参悟高阶丹方',
    cost: { insight: 3, herbs: 2 },
    output: { insight: 3 },
    cooldown: 8,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_foundation_strengthening_pill'],
      requiredLocation: 'pill_hall',
      requiredRealm: Realm.FoundationEstablishment,
    },
  },
  // Sword Pavilion actions
  practice_sword: {
    id: 'practice_sword',
    name: '练剑',
    cost: { essence: 10, qi: 5 },
    output: { insight: 2 },
    cooldown: 3,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'sword_pavilion',
    },
  },
  observe_sword_intent: {
    id: 'observe_sword_intent',
    name: '观摩剑意',
    cost: { insight: 5 },
    output: { insight: 4 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'sword_pavilion',
      requiredRealm: Realm.FoundationEstablishment,
    },
  },
  // Sect Hall actions
  attend_ceremony: {
    id: 'attend_ceremony',
    name: '参加典礼',
    cost: { coins: 3 },
    output: { insight: 2 },
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'sect_hall',
      requiredRealm: Realm.FoundationEstablishment,
    },
  },
  receive_mission: {
    id: 'receive_mission',
    name: '领取任务',
    cost: { essence: 5 },
    output: { coins: 3, insight: 1 },
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'sect_hall',
      requiredFlags: ['sect_rank_outer'],
    },
  },
  // Deep Temple actions
  search_altar: {
    id: 'search_altar',
    name: '探查祭坛',
    cost: { essence: 15 },
    output: { insight: 3 },
    cooldown: 8,
    riskProbability: 0.2,
    conditions: {
      requiredLocation: 'deep_temple',
      requiredRealm: Realm.FoundationEstablishment,
    },
  },
  meditate_dark: {
    id: 'meditate_dark',
    name: '冥思暗堂',
    cost: { essence: 10, qi: 5 },
    output: { insight: 4, qi: 3 },
    cooldown: 5,
    riskProbability: 0.15,
    conditions: {
      requiredLocation: 'deep_temple',
      requiredRealm: Realm.FoundationEstablishment,
    },
  },
  // Mountain Cave actions
  mine_crystal: {
    id: 'mine_crystal',
    name: '采集灵晶',
    cost: { essence: 15 },
    output: { coins: 5, herbs: 2 },
    cooldown: 4,
    riskProbability: 0.1,
    conditions: {
      requiredLocation: 'mountain_cave',
    },
  },
  explore_depths: {
    id: 'explore_depths',
    name: '深入探索',
    cost: { essence: 20, qi: 10 },
    output: { insight: 5, coins: 3 },
    cooldown: 6,
    riskProbability: 0.25,
    conditions: {
      requiredLocation: 'mountain_cave',
      requiredRealm: Realm.FoundationEstablishment,
    },
  },
  // Tea House actions
  drink_tea: {
    id: 'drink_tea',
    name: '饮茶',
    cost: { coins: 2 },
    output: { insight: 1, essence: 3 },
    cooldown: 2,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'tea_house',
    },
  },
  listen_rumor: {
    id: 'listen_rumor',
    name: '听传闻',
    cost: {},
    output: { insight: 1 },
    cooldown: 3,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'tea_house',
    },
  },
  gamble_dice: {
    id: 'gamble_dice',
    name: '掷骰赌钱',
    cost: { coins: 3 },
    output: { coins: 5 },
    cooldown: 5,
    riskProbability: 0.5,
    conditions: {
      requiredLocation: 'tea_house',
    },
  },
  // Demonic Forest actions
  hunt_beast: {
    id: 'hunt_beast',
    name: '猎杀妖兽',
    cost: { essence: 20, qi: 10 },
    output: { coins: 8, herbs: 3 },
    cooldown: 4,
    riskProbability: 0.3,
    conditions: {
      requiredLocation: 'demonic_forest',
      requiredRealm: Realm.FoundationEstablishment,
    },
  },
  gather_demonic_herb: {
    id: 'gather_demonic_herb',
    name: '采集魔药',
    cost: { essence: 10 },
    output: { herbs: 4 },
    cooldown: 3,
    riskProbability: 0.2,
    conditions: {
      requiredLocation: 'demonic_forest',
    },
  },
  set_trap: {
    id: 'set_trap',
    name: '设置陷阱',
    cost: { coins: 3, essence: 5 },
    output: { coins: 5, herbs: 2 },
    cooldown: 5,
    riskProbability: 0.15,
    conditions: {
      requiredLocation: 'demonic_forest',
    },
  },
  // Celestial Cliff actions
  cliff_meditation: {
    id: 'cliff_meditation',
    name: '悬崖静坐',
    cost: { essence: 15, qi: 10 },
    output: { qi: 8, insight: 3 },
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'celestial_cliff',
      requiredRealm: Realm.FoundationEstablishment,
    },
  },
  face_heavenly_wind: {
    id: 'face_heavenly_wind',
    name: '迎天风',
    cost: { qi: 15, essence: 20 },
    output: { qi: 12, insight: 5 },
    cooldown: 8,
    riskProbability: 0.2,
    conditions: {
      requiredLocation: 'celestial_cliff',
      requiredRealm: Realm.FoundationEstablishment,
    },
  },
  // === New pill study/brew/take actions ===
  // Cloud Gathering Pill (聚云丸)
  study_cloud_gathering_formula: {
    id: 'study_cloud_gathering_formula',
    name: '辨聚云方',
    cost: { essence: 25, herbs: 2, insight: 3 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_cloud_gathering_pill'],
      requiredFlags: ['known_recipe_foundation_strengthening_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  brew_cloud_gathering_pill: {
    id: 'brew_cloud_gathering_pill',
    name: '炼聚云丸',
    cost: CLOUD_GATHERING_PILL_COST,
    output: {},
    cooldown: 3,
    riskProbability: 0.1,
    conditions: {
      requiredFlags: ['known_recipe_cloud_gathering_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  take_cloud_gathering_pill: {
    id: 'take_cloud_gathering_pill',
    name: '服聚云丸',
    cost: { cloudGatheringPills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_cloud_gathering_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  // Iron Body Pill (铁身丹)
  study_iron_body_formula: {
    id: 'study_iron_body_formula',
    name: '辨铁身方',
    cost: { essence: 30, herbs: 2, insight: 4 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_iron_body_pill'],
      requiredFlags: ['known_recipe_foundation_strengthening_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  brew_iron_body_pill: {
    id: 'brew_iron_body_pill',
    name: '炼铁身丹',
    cost: IRON_BODY_PILL_COST,
    output: {},
    cooldown: 3,
    riskProbability: 0.1,
    conditions: {
      requiredFlags: ['known_recipe_iron_body_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  take_iron_body_pill: {
    id: 'take_iron_body_pill',
    name: '服铁身丹',
    cost: { ironBodyPills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_iron_body_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  // Demon Bane Pill (驱魔丹)
  study_demon_bane_formula: {
    id: 'study_demon_bane_formula',
    name: '辨驱魔方',
    cost: { essence: 35, herbs: 2, insight: 5 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_demon_bane_pill'],
      requiredFlags: ['known_recipe_meridian_cleansing_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  brew_demon_bane_pill: {
    id: 'brew_demon_bane_pill',
    name: '炼驱魔丹',
    cost: DEMON_BANE_PILL_COST,
    output: {},
    cooldown: 3,
    riskProbability: 0.1,
    conditions: {
      requiredFlags: ['known_recipe_demon_bane_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  take_demon_bane_pill: {
    id: 'take_demon_bane_pill',
    name: '服驱魔丹',
    cost: { demonBanePills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_demon_bane_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  // Foundation Explosion Pill (破基丹)
  study_foundation_explosion_formula: {
    id: 'study_foundation_explosion_formula',
    name: '辨破基方',
    cost: { essence: 40, herbs: 2, insight: 6 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_foundation_explosion_pill'],
      requiredFlags: ['known_recipe_foundation_strengthening_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  brew_foundation_explosion_pill: {
    id: 'brew_foundation_explosion_pill',
    name: '炼破基丹',
    cost: FOUNDATION_EXPLOSION_PILL_COST,
    output: {},
    cooldown: 3,
    riskProbability: 0.1,
    conditions: {
      requiredFlags: ['known_recipe_foundation_explosion_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  take_foundation_explosion_pill: {
    id: 'take_foundation_explosion_pill',
    name: '服破基丹',
    cost: { foundationExplosionPills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_foundation_explosion_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  // Spirit Vein Pill (通灵丸)
  study_spirit_vein_formula: {
    id: 'study_spirit_vein_formula',
    name: '辨通灵方',
    cost: { essence: 30, herbs: 2, insight: 4 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_spirit_vein_pill'],
      requiredFlags: ['known_recipe_meridian_cleansing_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  brew_spirit_vein_pill: {
    id: 'brew_spirit_vein_pill',
    name: '炼通灵丸',
    cost: SPIRIT_VEIN_PILL_COST,
    output: {},
    cooldown: 3,
    riskProbability: 0.1,
    conditions: {
      requiredFlags: ['known_recipe_spirit_vein_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  take_spirit_vein_pill: {
    id: 'take_spirit_vein_pill',
    name: '服通灵丸',
    cost: { spiritVeinPills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_spirit_vein_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  // Shadow Escape Pill (影遁丸)
  study_shadow_escape_formula: {
    id: 'study_shadow_escape_formula',
    name: '辨影遁方',
    cost: { essence: 30, herbs: 2, insight: 4 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_shadow_escape_pill'],
      requiredFlags: ['known_recipe_spirit_gathering_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  brew_shadow_escape_pill: {
    id: 'brew_shadow_escape_pill',
    name: '炼影遁丸',
    cost: SHADOW_ESCAPE_PILL_COST,
    output: {},
    cooldown: 3,
    riskProbability: 0.1,
    conditions: {
      requiredFlags: ['known_recipe_shadow_escape_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  take_shadow_escape_pill: {
    id: 'take_shadow_escape_pill',
    name: '服影遁丸',
    cost: { shadowEscapePills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_shadow_escape_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  // Longevity Pill (延寿丹)
  study_longevity_formula: {
    id: 'study_longevity_formula',
    name: '辨延寿方',
    cost: { essence: 50, herbs: 2, insight: 8 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_longevity_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
  brew_longevity_pill: {
    id: 'brew_longevity_pill',
    name: '炼延寿丹',
    cost: LONGEVITY_PILL_COST,
    output: {},
    cooldown: 3,
    riskProbability: 0.1,
    conditions: {
      requiredFlags: ['known_recipe_longevity_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
  take_longevity_pill: {
    id: 'take_longevity_pill',
    name: '服延寿丹',
    cost: { longevityPills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_longevity_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
  // Fire Furnace Pill (火炉丹)
  study_fire_furnace_formula: {
    id: 'study_fire_furnace_formula',
    name: '辨火炉方',
    cost: { essence: 30, herbs: 2, insight: 3 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_fire_furnace_pill'],
      requiredFlags: ['known_recipe_warm_furnace_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  brew_fire_furnace_pill: {
    id: 'brew_fire_furnace_pill',
    name: '炼火炉丹',
    cost: FIRE_FURNACE_PILL_COST,
    output: {},
    cooldown: 3,
    riskProbability: 0.1,
    conditions: {
      requiredFlags: ['known_recipe_fire_furnace_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  take_fire_furnace_pill: {
    id: 'take_fire_furnace_pill',
    name: '服火炉丹',
    cost: { fireFurnacePills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_fire_furnace_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  // Nine Turn Foundation Pill (重炉筑基丹)
  study_nine_turn_foundation_formula: {
    id: 'study_nine_turn_foundation_formula',
    name: '辨重炉筑基方',
    cost: { essence: 60, herbs: 2, insight: 10 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_nine_turn_foundation_pill'],
      requiredFlags: ['known_recipe_foundation_strengthening_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
  brew_nine_turn_foundation_pill: {
    id: 'brew_nine_turn_foundation_pill',
    name: '炼重炉筑基丹',
    cost: NINE_TURN_FOUNDATION_PILL_COST,
    output: {},
    cooldown: 3,
    riskProbability: 0.1,
    conditions: {
      requiredFlags: ['known_recipe_nine_turn_foundation_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
  take_nine_turn_foundation_pill: {
    id: 'take_nine_turn_foundation_pill',
    name: '服重炉筑基丹',
    cost: { nineTurnFoundationPills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_nine_turn_foundation_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
  // Buddha Heart Pill (定神丸)
  study_buddha_heart_formula: {
    id: 'study_buddha_heart_formula',
    name: '辨定神方',
    cost: { essence: 35, herbs: 2, insight: 5 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_buddha_heart_pill'],
      requiredFlags: ['known_recipe_cleansing_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  brew_buddha_heart_pill: {
    id: 'brew_buddha_heart_pill',
    name: '炼定神丸',
    cost: BUDDHA_HEART_PILL_COST,
    output: {},
    cooldown: 3,
    riskProbability: 0.1,
    conditions: {
      requiredFlags: ['known_recipe_buddha_heart_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  take_buddha_heart_pill: {
    id: 'take_buddha_heart_pill',
    name: '服定神丸',
    cost: { buddhaHeartPills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_buddha_heart_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
  // === Higher realm location actions ===
  // Core Gate actions (GoldenCore+)
  core_gate_cultivation: {
    id: 'core_gate_cultivation',
    name: '核心峰修炼',
    cost: { essence: 30, qi: 5 },
    output: { qi: 15, insight: 3 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'core_gate',
    },
  },
  core_gate_exchange: {
    id: 'core_gate_exchange',
    name: '核心峰兑换',
    cost: { coins: 20 },
    output: { herbs: 8, insight: 2 },
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'core_gate',
    },
  },
  seek_elder_guidance: {
    id: 'seek_elder_guidance',
    name: '求教长老',
    cost: { essence: 25, coins: 10 },
    output: { insight: 5, qi: 5 },
    cooldown: 60,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'core_gate',
      requiredFlags: ['sect_rank_core'],
    },
  },
  // Spirit Lake actions
  spirit_lake_meditation: {
    id: 'spirit_lake_meditation',
    name: '灵湖静修',
    cost: { essence: 20 },
    output: { qi: 8, insight: 2 },
    cooldown: 12,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'spirit_lake',
    },
  },
  dive_for_treasure: {
    id: 'dive_for_treasure',
    name: '潜湖寻宝',
    cost: { essence: 30, qi: 10 },
    output: { coins: 10, herbs: 5 },
    cooldown: 30,
    riskProbability: 0.2,
    conditions: {
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'spirit_lake',
    },
  },
  // Thunder Peak actions (NascentSoul+)
  face_tribulation: {
    id: 'face_tribulation',
    name: '引雷淬体',
    cost: { essence: 50, qi: 20 },
    output: { qi: 30, insight: 8 },
    cooldown: 40,
    riskProbability: 0.3,
    conditions: {
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'thunder_peak',
    },
  },
  thunder_cultivation: {
    id: 'thunder_cultivation',
    name: '雷修日课',
    cost: { essence: 40, qi: 15 },
    output: { qi: 25, insight: 5 },
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'thunder_peak',
    },
  },
  // Ancient Battlefield actions (SpiritTransformation+)
  search_battlefield: {
    id: 'search_battlefield',
    name: '搜索战场遗迹',
    cost: { essence: 40, qi: 15 },
    output: { coins: 15, herbs: 5, insight: 3 },
    cooldown: 20,
    riskProbability: 0.25,
    conditions: {
      requiredRealm: Realm.SpiritTransformation,
      requiredLocation: 'ancient_battlefield',
    },
  },
  commune_with_remnants: {
    id: 'commune_with_remnants',
    name: '感应残灵',
    cost: { essence: 30, qi: 20, insight: 5 },
    output: { insight: 10, qi: 10 },
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.SpiritTransformation,
      requiredLocation: 'ancient_battlefield',
    },
  },
  // Void Rift actions (Integration+)
  explore_void: {
    id: 'explore_void',
    name: '探查虚空',
    cost: { essence: 60, qi: 30 },
    output: { qi: 40, insight: 15 },
    cooldown: 50,
    riskProbability: 0.35,
    conditions: {
      requiredRealm: Realm.Integration,
      requiredLocation: 'void_rift',
    },
  },
  gather_void_essence: {
    id: 'gather_void_essence',
    name: '采集虚灵',
    cost: { essence: 40, qi: 20 },
    output: { qi: 25, herbs: 8 },
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.Integration,
      requiredLocation: 'void_rift',
    },
  },
  // Celestial Pavilion actions (NascentSoul+)
  study_celestial_script: {
    id: 'study_celestial_script',
    name: '参悟天书',
    cost: { essence: 30, insight: 5 },
    output: { insight: 8, qi: 10 },
    cooldown: 25,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'celestial_pavilion',
    },
  },
  meditate_on_dao: {
    id: 'meditate_on_dao',
    name: '悟道',
    cost: { essence: 50, qi: 25 },
    output: { qi: 20, insight: 12 },
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'celestial_pavilion',
    },
  },
  // Demon Seal Ground actions (GoldenCore+)
  patrol_seal: {
    id: 'patrol_seal',
    name: '巡守封印',
    cost: { essence: 25 },
    output: { coins: 8, insight: 2 },
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'demon_seal_ground',
    },
  },
  gather_demonic_material: {
    id: 'gather_demonic_material',
    name: '采集魔材',
    cost: { essence: 20 },
    output: { herbs: 6 },
    cooldown: 10,
    riskProbability: 0.15,
    conditions: {
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'demon_seal_ground',
    },
  },
  // Spirit Mountain actions (Mahayana+)
  spirit_mountain_retreat: {
    id: 'spirit_mountain_retreat',
    name: '灵山闭关',
    cost: { essence: 80, qi: 40 },
    output: { qi: 60, insight: 20 },
    cooldown: 60,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.Mahayana,
      requiredLocation: 'spirit_mountain',
    },
  },
  comprehend_dao: {
    id: 'comprehend_dao',
    name: '参道',
    cost: { essence: 60, qi: 30, insight: 10 },
    output: { qi: 30, insight: 25 },
    cooldown: 50,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.Mahayana,
      requiredLocation: 'spirit_mountain',
    },
  },
  // Tribulation Platform actions (Tribulation realm)
  face_heavenly_tribulation: {
    id: 'face_heavenly_tribulation',
    name: '迎天劫',
    cost: { essence: 100, qi: 50 },
    output: { qi: 80, insight: 30 },
    cooldown: 100,
    riskProbability: 0.4,
    conditions: {
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'tribulation_platform',
    },
  },
  stabilize_dao_foundation: {
    id: 'stabilize_dao_foundation',
    name: '稳固道基',
    cost: { essence: 60, qi: 30 },
    output: { qi: 20 },
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'tribulation_platform',
    },
  },
  // Immortal Garden actions (NascentSoul+)
  gather_immortal_herb: {
    id: 'gather_immortal_herb',
    name: '采仙草',
    cost: { essence: 20 },
    output: { herbs: 8, insight: 1 },
    cooldown: 8,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'immortal_garden',
    },
  },
  meditate_garden: {
    id: 'meditate_garden',
    name: '仙园悟道',
    cost: { essence: 30, qi: 10 },
    output: { qi: 15, insight: 5 },
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'immortal_garden',
    },
  },
  // Inner demon actions
  confront_demon: {
    id: 'confront_demon',
    name: '直面心魔',
    cost: { essence: 20, qi: 5 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'home',
    },
  },
  suppress_demon: {
    id: 'suppress_demon',
    name: '压制心魔',
    cost: { essence: 10 },
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'home',
    },
  },
  ignore_demon: {
    id: 'ignore_demon',
    name: '无视心魔',
    cost: {},
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {},
  },

  // High-realm pill actions: GoldenCore tier
  study_golden_core_formation_formula: {
    id: 'study_golden_core_formation_formula',
    name: '辨凝丹方',
    cost: { essence: 30, herbs: 5, insight: 6 },
    output: {},
    cooldown: 35,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_golden_core_formation_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
  brew_golden_core_formation_pill: {
    id: 'brew_golden_core_formation_pill',
    name: '炼凝丹丸',
    cost: GOLDEN_CORE_FORMATION_PILL_COST,
    output: {},
    cooldown: 50,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_golden_core_formation_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
  take_golden_core_formation_pill: {
    id: 'take_golden_core_formation_pill',
    name: '服凝丹丸',
    cost: { goldenCorePills: 1 },
    output: {},
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_golden_core_formation_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
  study_golden_core_strengthening_formula: {
    id: 'study_golden_core_strengthening_formula',
    name: '辨固丹方',
    cost: { essence: 30, herbs: 5, insight: 6 },
    output: {},
    cooldown: 35,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_golden_core_strengthening_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
  brew_golden_core_strengthening_pill: {
    id: 'brew_golden_core_strengthening_pill',
    name: '炼固丹丸',
    cost: GOLDEN_CORE_STRENGTHENING_PILL_COST,
    output: {},
    cooldown: 50,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_golden_core_strengthening_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
  take_golden_core_strengthening_pill: {
    id: 'take_golden_core_strengthening_pill',
    name: '服固丹丸',
    cost: { goldenCorePills: 1 },
    output: {},
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_golden_core_strengthening_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
  study_golden_core_fire_formula: {
    id: 'study_golden_core_fire_formula',
    name: '辨烈丹方',
    cost: { essence: 35, herbs: 6, insight: 7 },
    output: {},
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_golden_core_fire_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
  brew_golden_core_fire_pill: {
    id: 'brew_golden_core_fire_pill',
    name: '炼烈丹丸',
    cost: GOLDEN_CORE_FIRE_PILL_COST,
    output: {},
    cooldown: 55,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_golden_core_fire_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
  take_golden_core_fire_pill: {
    id: 'take_golden_core_fire_pill',
    name: '服烈丹丸',
    cost: { goldenCorePills: 1 },
    output: {},
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_golden_core_fire_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
  // High-realm pill actions: NascentSoul tier
  study_nascent_soul_nurturing_formula: {
    id: 'study_nascent_soul_nurturing_formula',
    name: '辨培婴方',
    cost: { essence: 40, herbs: 7, insight: 8 },
    output: {},
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_nascent_soul_nurturing_pill'],
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'home',
    },
  },
  brew_nascent_soul_nurturing_pill: {
    id: 'brew_nascent_soul_nurturing_pill',
    name: '炼培婴丹',
    cost: NASCENT_SOUL_NURTURING_PILL_COST,
    output: {},
    cooldown: 60,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_nascent_soul_nurturing_pill'],
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'home',
    },
  },
  take_nascent_soul_nurturing_pill: {
    id: 'take_nascent_soul_nurturing_pill',
    name: '服培婴丹',
    cost: { nascentSoulPills: 1 },
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_nascent_soul_nurturing_pill'],
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'home',
    },
  },
  study_nascent_soul_separation_formula: {
    id: 'study_nascent_soul_separation_formula',
    name: '辨出窍方',
    cost: { essence: 45, herbs: 8, insight: 9 },
    output: {},
    cooldown: 45,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_nascent_soul_separation_pill'],
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'home',
    },
  },
  brew_nascent_soul_separation_pill: {
    id: 'brew_nascent_soul_separation_pill',
    name: '炼出窍丹',
    cost: NASCENT_SOUL_SEPARATION_PILL_COST,
    output: {},
    cooldown: 65,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_nascent_soul_separation_pill'],
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'home',
    },
  },
  take_nascent_soul_separation_pill: {
    id: 'take_nascent_soul_separation_pill',
    name: '服出窍丹',
    cost: { nascentSoulPills: 1 },
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_nascent_soul_separation_pill'],
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'home',
    },
  },
  study_nascent_soul_protection_formula: {
    id: 'study_nascent_soul_protection_formula',
    name: '辨护婴方',
    cost: { essence: 40, herbs: 7, insight: 8 },
    output: {},
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_nascent_soul_protection_pill'],
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'home',
    },
  },
  brew_nascent_soul_protection_pill: {
    id: 'brew_nascent_soul_protection_pill',
    name: '炼护婴丹',
    cost: NASCENT_SOUL_PROTECTION_PILL_COST,
    output: {},
    cooldown: 60,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_nascent_soul_protection_pill'],
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'home',
    },
  },
  take_nascent_soul_protection_pill: {
    id: 'take_nascent_soul_protection_pill',
    name: '服护婴丹',
    cost: { nascentSoulPills: 1 },
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_nascent_soul_protection_pill'],
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'home',
    },
  },
  // High-realm pill actions: SpiritTransformation tier
  study_spirit_transform_formula: {
    id: 'study_spirit_transform_formula',
    name: '辨化神丹方',
    cost: { essence: 50, herbs: 9, insight: 10 },
    output: {},
    cooldown: 45,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_spirit_transform_pill'],
      requiredRealm: Realm.SpiritTransformation,
      requiredLocation: 'home',
    },
  },
  brew_spirit_transform_pill: {
    id: 'brew_spirit_transform_pill',
    name: '炼化神丹',
    cost: SPIRIT_TRANSFORM_PILL_COST,
    output: {},
    cooldown: 70,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_spirit_transform_pill'],
      requiredRealm: Realm.SpiritTransformation,
      requiredLocation: 'home',
    },
  },
  take_spirit_transform_pill: {
    id: 'take_spirit_transform_pill',
    name: '服化神丹',
    cost: { spiritTransformPills: 1 },
    output: {},
    cooldown: 25,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_spirit_transform_pill'],
      requiredRealm: Realm.SpiritTransformation,
      requiredLocation: 'home',
    },
  },
  study_spirit_transform_fire_formula: {
    id: 'study_spirit_transform_fire_formula',
    name: '辨化火丹方',
    cost: { essence: 55, herbs: 10, insight: 12 },
    output: {},
    cooldown: 50,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_spirit_transform_fire_pill'],
      requiredRealm: Realm.SpiritTransformation,
      requiredLocation: 'home',
    },
  },
  brew_spirit_transform_fire_pill: {
    id: 'brew_spirit_transform_fire_pill',
    name: '炼化火丹',
    cost: SPIRIT_TRANSFORM_FIRE_PILL_COST,
    output: {},
    cooldown: 75,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_spirit_transform_fire_pill'],
      requiredRealm: Realm.SpiritTransformation,
      requiredLocation: 'home',
    },
  },
  take_spirit_transform_fire_pill: {
    id: 'take_spirit_transform_fire_pill',
    name: '服化火丹',
    cost: { spiritTransformPills: 1 },
    output: {},
    cooldown: 25,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_spirit_transform_fire_pill'],
      requiredRealm: Realm.SpiritTransformation,
      requiredLocation: 'home',
    },
  },
  // High-realm pill actions: Integration tier
  study_integration_formula: {
    id: 'study_integration_formula',
    name: '辨合体丹方',
    cost: { essence: 60, herbs: 12, insight: 14 },
    output: {},
    cooldown: 50,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_integration_pill'],
      requiredRealm: Realm.Integration,
      requiredLocation: 'home',
    },
  },
  brew_integration_pill: {
    id: 'brew_integration_pill',
    name: '炼合体丹',
    cost: INTEGRATION_PILL_COST,
    output: {},
    cooldown: 80,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_integration_pill'],
      requiredRealm: Realm.Integration,
      requiredLocation: 'home',
    },
  },
  take_integration_pill: {
    id: 'take_integration_pill',
    name: '服合体丹',
    cost: { integrationPills: 1 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_integration_pill'],
      requiredRealm: Realm.Integration,
      requiredLocation: 'home',
    },
  },
  study_integration_body_formula: {
    id: 'study_integration_body_formula',
    name: '辨归体丹方',
    cost: { essence: 65, herbs: 13, insight: 15 },
    output: {},
    cooldown: 55,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_integration_body_pill'],
      requiredRealm: Realm.Integration,
      requiredLocation: 'home',
    },
  },
  brew_integration_body_pill: {
    id: 'brew_integration_body_pill',
    name: '炼归体丹',
    cost: INTEGRATION_BODY_PILL_COST,
    output: {},
    cooldown: 85,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_integration_body_pill'],
      requiredRealm: Realm.Integration,
      requiredLocation: 'home',
    },
  },
  take_integration_body_pill: {
    id: 'take_integration_body_pill',
    name: '服归体丹',
    cost: { integrationPills: 1 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_integration_body_pill'],
      requiredRealm: Realm.Integration,
      requiredLocation: 'home',
    },
  },
  // High-realm pill actions: Mahayana tier
  study_mahayana_formula: {
    id: 'study_mahayana_formula',
    name: '辨大乘丹方',
    cost: { essence: 70, herbs: 15, insight: 18 },
    output: {},
    cooldown: 60,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_mahayana_pill'],
      requiredRealm: Realm.Mahayana,
      requiredLocation: 'home',
    },
  },
  brew_mahayana_pill: {
    id: 'brew_mahayana_pill',
    name: '炼大乘丹',
    cost: MAHAYANA_PILL_COST,
    output: {},
    cooldown: 90,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_mahayana_pill'],
      requiredRealm: Realm.Mahayana,
      requiredLocation: 'home',
    },
  },
  take_mahayana_pill: {
    id: 'take_mahayana_pill',
    name: '服大乘丹',
    cost: { mahayanaPills: 1 },
    output: {},
    cooldown: 35,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_mahayana_pill'],
      requiredRealm: Realm.Mahayana,
      requiredLocation: 'home',
    },
  },
  study_mahayana_enlightenment_formula: {
    id: 'study_mahayana_enlightenment_formula',
    name: '辨悟道丹方',
    cost: { essence: 80, herbs: 18, insight: 22 },
    output: {},
    cooldown: 70,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_mahayana_enlightenment_pill'],
      requiredRealm: Realm.Mahayana,
      requiredLocation: 'home',
    },
  },
  brew_mahayana_enlightenment_pill: {
    id: 'brew_mahayana_enlightenment_pill',
    name: '炼悟道丹',
    cost: MAHAYANA_ENLIGHTENMENT_PILL_COST,
    output: {},
    cooldown: 100,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_mahayana_enlightenment_pill'],
      requiredRealm: Realm.Mahayana,
      requiredLocation: 'home',
    },
  },
  take_mahayana_enlightenment_pill: {
    id: 'take_mahayana_enlightenment_pill',
    name: '服悟道丹',
    cost: { mahayanaPills: 1 },
    output: {},
    cooldown: 35,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_mahayana_enlightenment_pill'],
      requiredRealm: Realm.Mahayana,
      requiredLocation: 'home',
    },
  },
  // High-realm pill actions: Tribulation tier
  study_tribulation_protection_formula: {
    id: 'study_tribulation_protection_formula',
    name: '辨护劫丹方',
    cost: { essence: 80, herbs: 20, insight: 25 },
    output: {},
    cooldown: 70,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_tribulation_protection_pill'],
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'home',
    },
  },
  brew_tribulation_protection_pill: {
    id: 'brew_tribulation_protection_pill',
    name: '炼护劫丹',
    cost: TRIBULATION_PROTECTION_PILL_COST,
    output: {},
    cooldown: 100,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_tribulation_protection_pill'],
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'home',
    },
  },
  take_tribulation_protection_pill: {
    id: 'take_tribulation_protection_pill',
    name: '服护劫丹',
    cost: { tribulationPills: 1 },
    output: {},
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_tribulation_protection_pill'],
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'home',
    },
  },
  study_heavenly_tribulation_formula: {
    id: 'study_heavenly_tribulation_formula',
    name: '辨天劫丹方',
    cost: { essence: 100, herbs: 25, insight: 30 },
    output: {},
    cooldown: 80,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_heavenly_tribulation_pill'],
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'home',
    },
  },
  brew_heavenly_tribulation_pill: {
    id: 'brew_heavenly_tribulation_pill',
    name: '炼天劫丹',
    cost: HEAVENLY_TRIBULATION_PILL_COST,
    output: {},
    cooldown: 120,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_heavenly_tribulation_pill'],
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'home',
    },
  },
  take_heavenly_tribulation_pill: {
    id: 'take_heavenly_tribulation_pill',
    name: '服天劫丹',
    cost: { heavenlyTribulationPills: 1 },
    output: {},
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_heavenly_tribulation_pill'],
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'home',
    },
  },
  study_tribulation_soul_formula: {
    id: 'study_tribulation_soul_formula',
    name: '辨安魂丹方',
    cost: { essence: 90, herbs: 22, insight: 28 },
    output: {},
    cooldown: 75,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_tribulation_soul_pill'],
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'home',
    },
  },
  brew_tribulation_soul_pill: {
    id: 'brew_tribulation_soul_pill',
    name: '炼安魂丹',
    cost: TRIBULATION_SOUL_PILL_COST,
    output: {},
    cooldown: 110,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_tribulation_soul_pill'],
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'home',
    },
  },
  take_tribulation_soul_pill: {
    id: 'take_tribulation_soul_pill',
    name: '服安魂丹',
    cost: { tribulationPills: 1 },
    output: {},
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_tribulation_soul_pill'],
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'home',
    },
  },
};
