import { Action, Realm } from '../game/types';

export const ACTIONS: Record<string, Action> = {
  kuzuo: {
    id: 'kuzuo',
    name: '枯坐',
    cost: { essence: 5 },
    output: { insight: 1 },
    cooldown: 5,
    riskProbability: 0,
    conditions: {},
  },
  tuna: {
    id: 'tuna',
    name: '吐纳',
    cost: { essence: 10 },
    output: { qi: 1 },
    cooldown: 5,
    riskProbability: 0,
    conditions: {},
  },
  caiyao: {
    id: 'caiyao',
    name: '采药',
    cost: { essence: 20 },
    output: { herbs: 1 },
    cooldown: 10,
    riskProbability: 0.1,
    conditions: {},
  },
  bianyao: {
    id: 'bianyao',
    name: '辨药',
    cost: { essence: 5, herbs: 1 },
    output: { insight: 1 },
    cooldown: 5,
    riskProbability: 0,
    conditions: {},
  },
  xunshan: {
    id: 'xunshan',
    name: '巡山',
    cost: { essence: 30 },
    output: { insight: 1, herbs: 2 },
    cooldown: 20,
    riskProbability: 0.3,
    conditions: {},
  },
  tiaoxi: {
    id: 'tiaoxi',
    name: '调息',
    cost: {},
    output: { essence: 30 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {},
  },
  yinqi: {
    id: 'yinqi',
    name: '引气入体',
    cost: { qi: 15, insight: 3, essence: 30 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['completed_rike_tuna'],
      requiredLocation: 'home',
      requiredRealm: Realm.Mortal,
    },
  },
  rike_tuna: {
    id: 'rike_tuna',
    name: '日课吐纳',
    cost: { essence: 60 },
    output: { qi: 8 },
    cooldown: 50,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'home',
    },
  },
};
