import { Element, Resources, Season } from '../game/types';

export type HerbNature = 'cold' | 'cool' | 'neutral' | 'warm' | 'hot';
export type HerbFlavor = 'pungent' | 'sweet' | 'sour' | 'bitter' | 'salty' | 'bland' | 'astringent';
export type HerbDirection = 'rise' | 'descend' | 'float' | 'sink';
export type HerbToxicity = 'none' | 'trace' | 'light' | 'medium' | 'heavy';

export interface HerbProfile {
  id: string;
  name: string;
  nature: HerbNature;
  flavor: HerbFlavor;
  phase: Element;
  direction: HerbDirection;
  toxicity: HerbToxicity;
  habitats: string[];
  seasons: Season[];
  use: string;
}

export interface PillRecipe {
  id: string;
  name: string;
  summary: string;
  mainHerbId: string;
  assistantHerbId: string;
  nature: HerbNature;
  phase: Element;
  direction: HerbDirection;
  requiredResources: Partial<Resources>;
  outputResource: keyof Resources;
  outputAmount: number;
  effect: Partial<Resources>;
  dantoxin: number;
  failureDantoxin: number;
  baseSuccess: number;
  seasonalAffinity: Season[];
}

export const HERB_NATURE_LABELS: Record<HerbNature, string> = {
  cold: '寒',
  cool: '凉',
  neutral: '平',
  warm: '温',
  hot: '热',
};

export const HERB_FLAVOR_LABELS: Record<HerbFlavor, string> = {
  pungent: '辛',
  sweet: '甘',
  sour: '酸',
  bitter: '苦',
  salty: '咸',
  bland: '淡',
  astringent: '涩',
};

export const HERB_DIRECTION_LABELS: Record<HerbDirection, string> = {
  rise: '升',
  descend: '降',
  float: '浮',
  sink: '沉',
};

export const HERB_PROFILES: Record<string, HerbProfile> = {
  dew_vein_grass: {
    id: 'dew_vein_grass',
    name: '露脉草',
    nature: 'cool',
    flavor: 'sweet',
    phase: Element.Water,
    direction: 'float',
    toxicity: 'trace',
    habitats: ['mountain_path'],
    seasons: [Season.Spring, Season.Autumn],
    use: '引气入脉，适合低阶聚气。',
  },
  yellow_dust_seed: {
    id: 'yellow_dust_seed',
    name: '黄尘籽',
    nature: 'neutral',
    flavor: 'sweet',
    phase: Element.Earth,
    direction: 'rise',
    toxicity: 'none',
    habitats: ['market', 'mountain_path'],
    seasons: [Season.Spring, Season.Summer, Season.Autumn],
    use: '调和药性，减少药气散逸。',
  },
  stone_sinew_root: {
    id: 'stone_sinew_root',
    name: '石筋根',
    nature: 'neutral',
    flavor: 'astringent',
    phase: Element.Earth,
    direction: 'sink',
    toxicity: 'none',
    habitats: ['mountain_path'],
    seasons: [Season.Autumn, Season.Winter],
    use: '收束气机，适合稳固关口。',
  },
  mist_leaf: {
    id: 'mist_leaf',
    name: '雾叶',
    nature: 'cool',
    flavor: 'bland',
    phase: Element.Wood,
    direction: 'float',
    toxicity: 'trace',
    habitats: ['mountain_path'],
    seasons: [Season.Spring, Season.Summer],
    use: '缓和躁气，略降药滞。',
  },
  green_bitter_vine: {
    id: 'green_bitter_vine',
    name: '青苦藤',
    nature: 'cold',
    flavor: 'bitter',
    phase: Element.Wood,
    direction: 'descend',
    toxicity: 'trace',
    habitats: ['mountain_path'],
    seasons: [Season.Spring, Season.Summer],
    use: '清降躁热，适合处理药气上冲。',
  },
  white_stone_lift: {
    id: 'white_stone_lift',
    name: '白石衣',
    nature: 'neutral',
    flavor: 'bland',
    phase: Element.Earth,
    direction: 'sink',
    toxicity: 'none',
    habitats: ['mountain_path'],
    seasons: [Season.Winter],
    use: '沉药入土，缓解丹毒入脉。',
  },
  ash_stem_flower: {
    id: 'ash_stem_flower',
    name: '灰茎花',
    nature: 'warm',
    flavor: 'bitter',
    phase: Element.Fire,
    direction: 'rise',
    toxicity: 'light',
    habitats: ['abandoned_temple', 'mountain_path'],
    seasons: [Season.Summer],
    use: '提升火候，适合炼炉助火。',
  },
  iron_wire_moss: {
    id: 'iron_wire_moss',
    name: '铁线苔',
    nature: 'cold',
    flavor: 'salty',
    phase: Element.Metal,
    direction: 'sink',
    toxicity: 'light',
    habitats: ['stream_valley', 'mountain_path'],
    seasons: [Season.Autumn, Season.Winter],
    use: '压制伤势，寒性入骨。',
  },
  candle_heart_tendril: {
    id: 'candle_heart_tendril',
    name: '烛心须',
    nature: 'hot',
    flavor: 'pungent',
    phase: Element.Fire,
    direction: 'rise',
    toxicity: 'medium',
    habitats: ['abandoned_temple'],
    seasons: [Season.Summer],
    use: '短时冲关，心魔风险高。',
  },
  night_sand_fungus: {
    id: 'night_sand_fungus',
    name: '夜砂芝',
    nature: 'warm',
    flavor: 'sweet',
    phase: Element.Earth,
    direction: 'sink',
    toxicity: 'trace',
    habitats: ['stream_valley'],
    seasons: [Season.Winter],
    use: '闭关稳定，适合夜修。',
  },
  cloud_petal: {
    id: 'cloud_petal',
    name: '云瓣花',
    nature: 'cool',
    flavor: 'sweet',
    phase: Element.Water,
    direction: 'float',
    toxicity: 'none',
    habitats: ['mountain_path', 'celestial_cliff'],
    seasons: [Season.Spring],
    use: '聚灵养神，高阶聚气辅助。',
  },
  black_iron_root: {
    id: 'black_iron_root',
    name: '黑铁根',
    nature: 'cold',
    flavor: 'salty',
    phase: Element.Metal,
    direction: 'sink',
    toxicity: 'light',
    habitats: ['mountain_cave'],
    seasons: [Season.Autumn, Season.Winter],
    use: '铁性入骨，锻体之材。',
  },
  spirit_vein_moss: {
    id: 'spirit_vein_moss',
    name: '灵脉苔',
    nature: 'neutral',
    flavor: 'bland',
    phase: Element.Earth,
    direction: 'float',
    toxicity: 'trace',
    habitats: ['mountain_cave', 'stream_valley'],
    seasons: [Season.Spring, Season.Summer, Season.Autumn],
    use: '脉中灵气凝成，通脉良材。',
  },
  crimson_lotus: {
    id: 'crimson_lotus',
    name: '赤莲',
    nature: 'hot',
    flavor: 'bitter',
    phase: Element.Fire,
    direction: 'rise',
    toxicity: 'medium',
    habitats: ['demonic_forest'],
    seasons: [Season.Summer],
    use: '火性极盛，短时强冲关卡。',
  },
  moon_dew_herb: {
    id: 'moon_dew_herb',
    name: '月露草',
    nature: 'cool',
    flavor: 'sweet',
    phase: Element.Water,
    direction: 'float',
    toxicity: 'none',
    habitats: ['celestial_cliff', 'stream_valley'],
    seasons: [Season.Autumn],
    use: '月华凝聚，修炼辅助。',
  },
  ghost_fern: {
    id: 'ghost_fern',
    name: '鬼蕨',
    nature: 'cold',
    flavor: 'bitter',
    phase: Element.Water,
    direction: 'descend',
    toxicity: 'heavy',
    habitats: ['deep_temple', 'mountain_cave'],
    seasons: [Season.Winter],
    use: '阴寒入骨，可入镇魔丹方，但毒性大。',
  },
  golden_silk_vine: {
    id: 'golden_silk_vine',
    name: '金丝藤',
    nature: 'warm',
    flavor: 'sweet',
    phase: Element.Metal,
    direction: 'rise',
    toxicity: 'none',
    habitats: ['spirit_field', 'herb_slope'],
    seasons: [Season.Spring, Season.Summer],
    use: '金丝养脉，恢复良材。',
  },
  demon_bane_grass: {
    id: 'demon_bane_grass',
    name: '驱魔草',
    nature: 'warm',
    flavor: 'pungent',
    phase: Element.Fire,
    direction: 'rise',
    toxicity: 'light',
    habitats: ['demonic_forest'],
    seasons: [Season.Summer, Season.Autumn],
    use: '驱邪镇魔，克制心魔。',
  },
  thousand_year_pine_gum: {
    id: 'thousand_year_pine_gum',
    name: '千年松脂',
    nature: 'neutral',
    flavor: 'sweet',
    phase: Element.Wood,
    direction: 'sink',
    toxicity: 'trace',
    habitats: ['mountain_path', 'mountain_cave'],
    seasons: [Season.Autumn, Season.Winter],
    use: '古松精华，延寿固元。',
  },
  shadow_moss: {
    id: 'shadow_moss',
    name: '影苔',
    nature: 'cold',
    flavor: 'bland',
    phase: Element.Water,
    direction: 'descend',
    toxicity: 'trace',
    habitats: ['deep_temple', 'mountain_cave'],
    seasons: [Season.Winter],
    use: '阴属性辅助，隐遁术材料。',
  },
  sunfire_berry: {
    id: 'sunfire_berry',
    name: '阳火果',
    nature: 'hot',
    flavor: 'sweet',
    phase: Element.Fire,
    direction: 'rise',
    toxicity: 'medium',
    habitats: ['demonic_forest', 'mountain_path'],
    seasons: [Season.Summer],
    use: '纯阳火果，炼丹催化。',
  },
  earthheart_stone_powder: {
    id: 'earthheart_stone_powder',
    name: '地心石粉',
    nature: 'warm',
    flavor: 'bland',
    phase: Element.Earth,
    direction: 'sink',
    toxicity: 'light',
    habitats: ['mountain_cave'],
    seasons: [Season.Spring, Season.Autumn],
    use: '地脉精华，固基之材。',
  },
  wind_chime_flower: {
    id: 'wind_chime_flower',
    name: '风铃花',
    nature: 'cool',
    flavor: 'pungent',
    phase: Element.Metal,
    direction: 'float',
    toxicity: 'none',
    habitats: ['celestial_cliff', 'mountain_path'],
    seasons: [Season.Spring],
    use: '风性轻灵，轻功遁术材料。',
  },
  buddha_heart_leaf: {
    id: 'buddha_heart_leaf',
    name: '镇意叶',
    nature: 'neutral',
    flavor: 'sweet',
    phase: Element.Earth,
    direction: 'sink',
    toxicity: 'none',
    habitats: ['abandoned_temple', 'deep_temple'],
    seasons: [Season.Spring, Season.Autumn],
    use: '心性辅助，抗心魔。',
  },
  nine_turn_ginseng: {
    id: 'nine_turn_ginseng',
    name: '厚壤参',
    nature: 'warm',
    flavor: 'sweet',
    phase: Element.Earth,
    direction: 'rise',
    toxicity: 'heavy',
    habitats: ['mountain_cave'],
    seasons: [Season.Autumn],
    use: '稀世灵药，筑基突破辅材。',
  },

  // === Mid-tier herbs (FoundationEstablishment / GoldenCore) ===
  purple_ginseng: {
    id: 'purple_ginseng',
    name: '紫须参',
    nature: 'warm',
    flavor: 'sweet',
    phase: Element.Earth,
    direction: 'rise',
    toxicity: 'none',
    habitats: ['mountain_cave', 'celestial_cliff'],
    seasons: [Season.Autumn],
    use: '筑基后补气灵药，金丹辅材。',
  },
  jade_spirit_fruit: {
    id: 'jade_spirit_fruit',
    name: '玉灵果',
    nature: 'neutral',
    flavor: 'sweet',
    phase: Element.Wood,
    direction: 'float',
    toxicity: 'none',
    habitats: ['spirit_field'],
    seasons: [Season.Summer],
    use: '筑基后期灵果，稳固根基。',
  },
  sky_frost_flower: {
    id: 'sky_frost_flower',
    name: '天霜花',
    nature: 'cold',
    flavor: 'bitter',
    phase: Element.Water,
    direction: 'descend',
    toxicity: 'trace',
    habitats: ['celestial_cliff'],
    seasons: [Season.Winter],
    use: '极寒灵药，凝丹辅材。',
  },
  earth_marow_stone: {
    id: 'earth_marow_stone',
    name: '地髓石',
    nature: 'warm',
    flavor: 'bland',
    phase: Element.Earth,
    direction: 'sink',
    toxicity: 'light',
    habitats: ['mountain_cave'],
    seasons: [Season.Spring, Season.Autumn],
    use: '地脉精华凝石，金丹稳固之材。',
  },
  spirit_gathering_vine: {
    id: 'spirit_gathering_vine',
    name: '聚灵藤',
    nature: 'neutral',
    flavor: 'sweet',
    phase: Element.Wood,
    direction: 'rise',
    toxicity: 'none',
    habitats: ['spirit_field', 'stream_valley'],
    seasons: [Season.Spring, Season.Summer],
    use: '灵气密集之藤，金丹辅修。',
  },

  // === High-tier herbs (GoldenCore / NascentSoul) ===
  golden_coral_branch: {
    id: 'golden_coral_branch',
    name: '金珊瑚枝',
    nature: 'warm',
    flavor: 'sweet',
    phase: Element.Metal,
    direction: 'rise',
    toxicity: 'light',
    habitats: ['mountain_cave'],
    seasons: [Season.Summer],
    use: '金属性灵材，元婴凝炼辅材。',
  },
  nether_soul_grass: {
    id: 'nether_soul_grass',
    name: '幽魂草',
    nature: 'cold',
    flavor: 'bitter',
    phase: Element.Water,
    direction: 'descend',
    toxicity: 'medium',
    habitats: ['deep_temple'],
    seasons: [Season.Winter],
    use: '阴灵之草，元婴出窍辅材。',
  },
  tribulation_grass: {
    id: 'tribulation_grass',
    name: '劫草',
    nature: 'hot',
    flavor: 'pungent',
    phase: Element.Fire,
    direction: 'rise',
    toxicity: 'heavy',
    habitats: ['celestial_cliff'],
    seasons: [Season.Summer],
    use: '天劫余蕴所生，渡劫辅材。',
  },
  thousand_year_snow_lotus: {
    id: 'thousand_year_snow_lotus',
    name: '千年雪莲',
    nature: 'cold',
    flavor: 'sweet',
    phase: Element.Water,
    direction: 'float',
    toxicity: 'trace',
    habitats: ['celestial_cliff'],
    seasons: [Season.Winter],
    use: '稀世灵药，元婴培婴良材。',
  },
  dragon_blood_grass: {
    id: 'dragon_blood_grass',
    name: '龙血草',
    nature: 'hot',
    flavor: 'sweet',
    phase: Element.Fire,
    direction: 'rise',
    toxicity: 'medium',
    habitats: ['demonic_forest'],
    seasons: [Season.Summer],
    use: '龙血浸染之草，化神辅材。',
  },

  // === Ultra-tier herbs (SpiritTransformation+) ===
  void_crystal_herb: {
    id: 'void_crystal_herb',
    name: '虚晶草',
    nature: 'cold',
    flavor: 'bland',
    phase: Element.Metal,
    direction: 'sink',
    toxicity: 'light',
    habitats: ['celestial_cliff'],
    seasons: [Season.Autumn],
    use: '虚空之力凝聚，化神辅修。',
  },
  chaos_lotus: {
    id: 'chaos_lotus',
    name: '混沌莲',
    nature: 'neutral',
    flavor: 'sweet',
    phase: Element.Earth,
    direction: 'float',
    toxicity: 'heavy',
    habitats: ['mountain_cave'],
    seasons: [Season.Summer],
    use: '混沌之力蕴莲，合体辅修。',
  },
  heavenly_dew_grass: {
    id: 'heavenly_dew_grass',
    name: '天露草',
    nature: 'cool',
    flavor: 'sweet',
    phase: Element.Water,
    direction: 'float',
    toxicity: 'none',
    habitats: ['celestial_cliff'],
    seasons: [Season.Spring],
    use: '天露凝灵，大乘辅修。',
  },
  star_iron_moss: {
    id: 'star_iron_moss',
    name: '星铁苔',
    nature: 'cold',
    flavor: 'salty',
    phase: Element.Metal,
    direction: 'sink',
    toxicity: 'medium',
    habitats: ['mountain_cave'],
    seasons: [Season.Winter],
    use: '星铁之苔，渡劫护体辅材。',
  },
  primordial_ginseng: {
    id: 'primordial_ginseng',
    name: '太初参',
    nature: 'warm',
    flavor: 'sweet',
    phase: Element.Earth,
    direction: 'rise',
    toxicity: 'heavy',
    habitats: ['mountain_cave'],
    seasons: [Season.Autumn],
    use: '太初灵气所化，渡劫极品辅材。',
  },
  phoenix_feather_fern: {
    id: 'phoenix_feather_fern',
    name: '凤羽蕨',
    nature: 'hot',
    flavor: 'pungent',
    phase: Element.Fire,
    direction: 'rise',
    toxicity: 'medium',
    habitats: ['demonic_forest'],
    seasons: [Season.Summer],
    use: '凤羽灵火之蕨，化神辅修。',
  },
  soul_nurturing_wood: {
    id: 'soul_nurturing_wood',
    name: '养魂木',
    nature: 'neutral',
    flavor: 'sweet',
    phase: Element.Wood,
    direction: 'sink',
    toxicity: 'trace',
    habitats: ['deep_temple'],
    seasons: [Season.Spring, Season.Autumn],
    use: '养魂安神之木，元婴出窍辅修。',
  },
  thunder_essence_vine: {
    id: 'thunder_essence_vine',
    name: '雷精藤',
    nature: 'hot',
    flavor: 'pungent',
    phase: Element.Fire,
    direction: 'rise',
    toxicity: 'heavy',
    habitats: ['celestial_cliff'],
    seasons: [Season.Summer],
    use: '雷精之力，渡劫护体辅修。',
  },
  yin_yang_fruit: {
    id: 'yin_yang_fruit',
    name: '阴阳果',
    nature: 'neutral',
    flavor: 'sweet',
    phase: Element.Wood,
    direction: 'float',
    toxicity: 'light',
    habitats: ['spirit_field', 'mountain_cave'],
    seasons: [Season.Autumn],
    use: '阴阳调和之果，金丹突破辅佐。',
  },
  crimson_blood_vine: {
    id: 'crimson_blood_vine',
    name: '赤血藤',
    nature: 'warm',
    flavor: 'sour',
    phase: Element.Fire,
    direction: 'rise',
    toxicity: 'medium',
    habitats: ['demonic_forest', 'mountain_cave'],
    seasons: [Season.Summer, Season.Autumn],
    use: '赤血浸染之藤，活血化瘀良材。',
  },
};

export const PILL_RECIPES: Record<string, PillRecipe> = {
  small_qi_pill: {
    id: 'small_qi_pill',
    name: '小聚气丸',
    summary: '凉甘而浮，水土相和。服后添真气，兼生丹毒。',
    mainHerbId: 'dew_vein_grass',
    assistantHerbId: 'yellow_dust_seed',
    nature: 'cool',
    phase: Element.Water,
    direction: 'float',
    requiredResources: { essence: 30, herbs: 3, insight: 1 },
    outputResource: 'qiPills',
    outputAmount: 1,
    effect: { qi: 6 },
    dantoxin: 3,
    failureDantoxin: 1,
    baseSuccess: 0.72,
    seasonalAffinity: [Season.Spring, Season.Winter],
  },
  stabilizing_powder: {
    id: 'stabilizing_powder',
    name: '稳息散',
    summary: '平涩而沉，木土相调。服后气机转慢，可护下一次冲关。',
    mainHerbId: 'stone_sinew_root',
    assistantHerbId: 'mist_leaf',
    nature: 'neutral',
    phase: Element.Earth,
    direction: 'sink',
    requiredResources: { essence: 35, herbs: 4, insight: 2 },
    outputResource: 'stabilizingPowders',
    outputAmount: 1,
    effect: { qi: -2, dantoxin: -2 },
    dantoxin: 1,
    failureDantoxin: 1,
    baseSuccess: 0.66,
    seasonalAffinity: [Season.Autumn, Season.Winter],
  },
  cleansing_pill: {
    id: 'cleansing_pill',
    name: '清躁丸',
    summary: '寒苦而降，木土相济。服后清药躁，退丹毒，伤精元。',
    mainHerbId: 'green_bitter_vine',
    assistantHerbId: 'white_stone_lift',
    nature: 'cold',
    phase: Element.Wood,
    direction: 'descend',
    requiredResources: { essence: 40, herbs: 5, insight: 3 },
    outputResource: 'cleansingPills',
    outputAmount: 1,
    effect: { essence: -8, dantoxin: -16, wounds: -1 },
    dantoxin: 1,
    failureDantoxin: 0,
    baseSuccess: 0.62,
    seasonalAffinity: [Season.Spring, Season.Winter],
  },
  meridian_cleansing_pill: {
    id: 'meridian_cleansing_pill',
    name: '通脉丸',
    summary: '凉苦而降，水土相济。服后通脉解毒，兼耗精元。',
    mainHerbId: 'dew_vein_grass',
    assistantHerbId: 'green_bitter_vine',
    nature: 'cool',
    phase: Element.Water,
    direction: 'descend',
    requiredResources: { essence: 30, herbs: 5, insight: 5 },
    outputResource: 'meridianCleansingPills',
    outputAmount: 1,
    effect: { dantoxin: -25, wounds: -1, essence: -20 },
    dantoxin: 2,
    failureDantoxin: 1,
    baseSuccess: 0.58,
    seasonalAffinity: [Season.Spring, Season.Autumn],
  },
  foundation_strengthening_pill: {
    id: 'foundation_strengthening_pill',
    name: '固基丹',
    summary: '温甘而升，土土相和。服后固基添气，助冲关。',
    mainHerbId: 'yellow_dust_seed',
    assistantHerbId: 'stone_sinew_root',
    nature: 'warm',
    phase: Element.Earth,
    direction: 'rise',
    requiredResources: { essence: 25, herbs: 4, coins: 5, insight: 3 },
    outputResource: 'foundationStrengtheningPills',
    outputAmount: 1,
    effect: { qi: 8 },
    dantoxin: 1,
    failureDantoxin: 0,
    baseSuccess: 0.60,
    seasonalAffinity: [Season.Summer, Season.Autumn],
  },
  spirit_gathering_pill: {
    id: 'spirit_gathering_pill',
    name: '聚灵丸',
    summary: '平甘而升，金土相和。服后聚灵添气，丹毒偏重。',
    mainHerbId: 'dew_vein_grass',
    assistantHerbId: 'yellow_dust_seed',
    nature: 'neutral',
    phase: Element.Metal,
    direction: 'rise',
    requiredResources: { essence: 20, herbs: 4, insight: 3 },
    outputResource: 'spiritGatheringPills',
    outputAmount: 1,
    effect: { qi: 15 },
    dantoxin: 3,
    failureDantoxin: 2,
    baseSuccess: 0.55,
    seasonalAffinity: [Season.Spring, Season.Winter],
  },
  warm_furnace_pill: {
    id: 'warm_furnace_pill',
    name: '暖炉丹',
    summary: '温苦而升，火火相催。服后提升炼丹成功率，但火盛致丹毒上升。',
    mainHerbId: 'ash_stem_flower',
    assistantHerbId: 'candle_heart_tendril',
    nature: 'warm',
    phase: Element.Fire,
    direction: 'rise',
    requiredResources: { essence: 25, herbs: 4, insight: 2 },
    outputResource: 'warmFurnacePills',
    outputAmount: 1,
    effect: { qi: 3, dantoxin: 5 },
    dantoxin: 4,
    failureDantoxin: 2,
    baseSuccess: 0.58,
    seasonalAffinity: [Season.Summer],
  },
  night_sitting_pill: {
    id: 'night_sitting_pill',
    name: '夜坐丸',
    summary: '温甘而沉，土水相守。服后闭关收益上升，但消耗寿元。',
    mainHerbId: 'night_sand_fungus',
    assistantHerbId: 'dew_vein_grass',
    nature: 'warm',
    phase: Element.Earth,
    direction: 'sink',
    requiredResources: { essence: 30, herbs: 5, insight: 4 },
    outputResource: 'nightSittingPills',
    outputAmount: 1,
    effect: { qi: 15, insight: 3, lifespan: -30 },
    dantoxin: 2,
    failureDantoxin: 1,
    baseSuccess: 0.52,
    seasonalAffinity: [Season.Winter, Season.Autumn],
  },
  cloud_gathering_pill: {
    id: 'cloud_gathering_pill',
    name: '聚云丸',
    summary: '凉甘而浮，水水相济。服后灵气充盈，适合修炼辅助。',
    mainHerbId: 'cloud_petal',
    assistantHerbId: 'moon_dew_herb',
    nature: 'cool',
    phase: Element.Water,
    direction: 'float',
    requiredResources: { essence: 25, herbs: 4, insight: 2 },
    outputResource: 'cloudGatheringPills',
    outputAmount: 1,
    effect: { qi: 12 },
    dantoxin: 2,
    failureDantoxin: 1,
    baseSuccess: 0.65,
    seasonalAffinity: [Season.Spring, Season.Winter],
  },
  iron_body_pill: {
    id: 'iron_body_pill',
    name: '铁身丹',
    summary: '寒咸而沉，金金相固。服后锻体强骨，伤减一分。',
    mainHerbId: 'black_iron_root',
    assistantHerbId: 'golden_silk_vine',
    nature: 'cold',
    phase: Element.Metal,
    direction: 'sink',
    requiredResources: { essence: 35, herbs: 5, insight: 3 },
    outputResource: 'ironBodyPills',
    outputAmount: 1,
    effect: { wounds: -2, dantoxin: 3 },
    dantoxin: 3,
    failureDantoxin: 2,
    baseSuccess: 0.55,
    seasonalAffinity: [Season.Autumn, Season.Winter],
  },
  demon_bane_pill: {
    id: 'demon_bane_pill',
    name: '驱魔丹',
    summary: '温辛而升，火金相克。服后镇心魔，降心魔风险。',
    mainHerbId: 'demon_bane_grass',
    assistantHerbId: 'buddha_heart_leaf',
    nature: 'warm',
    phase: Element.Fire,
    direction: 'rise',
    requiredResources: { essence: 40, herbs: 6, insight: 5 },
    outputResource: 'demonBanePills',
    outputAmount: 1,
    effect: { dantoxin: -10 },
    dantoxin: 2,
    failureDantoxin: 1,
    baseSuccess: 0.50,
    seasonalAffinity: [Season.Summer, Season.Autumn],
  },
  foundation_explosion_pill: {
    id: 'foundation_explosion_pill',
    name: '破基丹',
    summary: '热苦而升，火土相催。服后猛冲筑基关口，但代价惨重。',
    mainHerbId: 'crimson_lotus',
    assistantHerbId: 'earthheart_stone_powder',
    nature: 'hot',
    phase: Element.Fire,
    direction: 'rise',
    requiredResources: { essence: 50, herbs: 8, insight: 6 },
    outputResource: 'foundationExplosionPills',
    outputAmount: 1,
    effect: { qi: 25, dantoxin: 8, wounds: 1 },
    dantoxin: 6,
    failureDantoxin: 4,
    baseSuccess: 0.42,
    seasonalAffinity: [Season.Summer],
  },
  spirit_vein_pill: {
    id: 'spirit_vein_pill',
    name: '通灵丸',
    summary: '平淡而浮，土水相和。服后通脉净灵，降丹毒兼添真气。',
    mainHerbId: 'spirit_vein_moss',
    assistantHerbId: 'dew_vein_grass',
    nature: 'neutral',
    phase: Element.Earth,
    direction: 'float',
    requiredResources: { essence: 30, herbs: 5, insight: 4 },
    outputResource: 'spiritVeinPills',
    outputAmount: 1,
    effect: { dantoxin: -15, qi: 8 },
    dantoxin: 2,
    failureDantoxin: 1,
    baseSuccess: 0.60,
    seasonalAffinity: [Season.Spring, Season.Autumn],
  },
  shadow_escape_pill: {
    id: 'shadow_escape_pill',
    name: '影遁丸',
    summary: '寒淡而降，水水相隐。服后短时隐匿能力提升，避险脱困。',
    mainHerbId: 'shadow_moss',
    assistantHerbId: 'moon_dew_herb',
    nature: 'cold',
    phase: Element.Water,
    direction: 'descend',
    requiredResources: { essence: 35, herbs: 5, insight: 3 },
    outputResource: 'shadowEscapePills',
    outputAmount: 1,
    effect: { qi: 5, dantoxin: 2 },
    dantoxin: 3,
    failureDantoxin: 2,
    baseSuccess: 0.55,
    seasonalAffinity: [Season.Winter, Season.Autumn],
  },
  longevity_pill: {
    id: 'longevity_pill',
    name: '延寿丹',
    summary: '温甘而沉，土木相生。服后延年益寿，修行者梦寐以求。',
    mainHerbId: 'thousand_year_pine_gum',
    assistantHerbId: 'golden_silk_vine',
    nature: 'warm',
    phase: Element.Wood,
    direction: 'sink',
    requiredResources: { essence: 60, herbs: 8, insight: 8 },
    outputResource: 'longevityPills',
    outputAmount: 1,
    effect: { lifespan: 100, dantoxin: 5 },
    dantoxin: 4,
    failureDantoxin: 3,
    baseSuccess: 0.40,
    seasonalAffinity: [Season.Autumn, Season.Winter],
  },
  fire_furnace_pill: {
    id: 'fire_furnace_pill',
    name: '火炉丹',
    summary: '热甘而升，火火相催。炼丹师专用，大幅提升炼丹火候。',
    mainHerbId: 'sunfire_berry',
    assistantHerbId: 'ash_stem_flower',
    nature: 'hot',
    phase: Element.Fire,
    direction: 'rise',
    requiredResources: { essence: 30, herbs: 5, insight: 3 },
    outputResource: 'fireFurnacePills',
    outputAmount: 1,
    effect: { qi: 5, dantoxin: 8 },
    dantoxin: 5,
    failureDantoxin: 3,
    baseSuccess: 0.50,
    seasonalAffinity: [Season.Summer],
  },
  nine_turn_foundation_pill: {
    id: 'nine_turn_foundation_pill',
    name: '重炉筑基丹',
    summary: '温甘而升，土土相固。稀世丹药，筑基成功率大增，代价亦高。',
    mainHerbId: 'nine_turn_ginseng',
    assistantHerbId: 'earthheart_stone_powder',
    nature: 'warm',
    phase: Element.Earth,
    direction: 'rise',
    requiredResources: { essence: 80, herbs: 10, insight: 10 },
    outputResource: 'nineTurnFoundationPills',
    outputAmount: 1,
    effect: { qi: 30, dantoxin: 10, lifespan: -100 },
    dantoxin: 8,
    failureDantoxin: 5,
    baseSuccess: 0.35,
    seasonalAffinity: [Season.Autumn],
  },
  buddha_heart_pill: {
    id: 'buddha_heart_pill',
    name: '定神丸',
    summary: '平淡而沉，土土相守。服后心境清明，心魔压制效果极好。',
    mainHerbId: 'buddha_heart_leaf',
    assistantHerbId: 'white_stone_lift',
    nature: 'neutral',
    phase: Element.Earth,
    direction: 'sink',
    requiredResources: { essence: 40, herbs: 5, insight: 4 },
    outputResource: 'buddhaHeartPills',
    outputAmount: 1,
    effect: { dantoxin: -20, qi: 3 },
    dantoxin: 1,
    failureDantoxin: 0,
    baseSuccess: 0.58,
    seasonalAffinity: [Season.Spring, Season.Autumn],
  },

  // === Foundation / GoldenCore tier ===
  golden_core_formation_pill: {
    id: 'golden_core_formation_pill',
    name: '凝丹丸',
    summary: '温甘而升，金土相和。服后凝气成丹，金丹突破辅佐。',
    mainHerbId: 'purple_ginseng',
    assistantHerbId: 'earth_marow_stone',
    nature: 'warm',
    phase: Element.Metal,
    direction: 'rise',
    requiredResources: { essence: 60, herbs: 8, insight: 8 },
    outputResource: 'goldenCorePills',
    outputAmount: 1,
    effect: { qi: 35 },
    dantoxin: 8,
    failureDantoxin: 4,
    baseSuccess: 0.38,
    seasonalAffinity: [Season.Autumn],
  },
  golden_core_strengthening_pill: {
    id: 'golden_core_strengthening_pill',
    name: '固丹丸',
    summary: '平甘而升，土木相生。服后稳固金丹，兼退丹毒。',
    mainHerbId: 'jade_spirit_fruit',
    assistantHerbId: 'spirit_gathering_vine',
    nature: 'neutral',
    phase: Element.Earth,
    direction: 'rise',
    requiredResources: { essence: 50, herbs: 6, insight: 6 },
    outputResource: 'goldenCorePills',
    outputAmount: 1,
    effect: { qi: 20, dantoxin: -5 },
    dantoxin: 5,
    failureDantoxin: 3,
    baseSuccess: 0.45,
    seasonalAffinity: [Season.Summer],
  },
  golden_core_fire_pill: {
    id: 'golden_core_fire_pill',
    name: '丹火丸',
    summary: '寒苦而降，水火相济。服后丹火凝聚，炼丹火候精进。',
    mainHerbId: 'sky_frost_flower',
    assistantHerbId: 'sunfire_berry',
    nature: 'hot',
    phase: Element.Fire,
    direction: 'rise',
    requiredResources: { essence: 70, herbs: 10, insight: 10 },
    outputResource: 'warmFurnacePills',
    outputAmount: 1,
    effect: { qi: 15, dantoxin: 5 },
    dantoxin: 6,
    failureDantoxin: 3,
    baseSuccess: 0.35,
    seasonalAffinity: [Season.Summer, Season.Winter],
  },

  // === NascentSoul tier ===
  nascent_soul_nurturing_pill: {
    id: 'nascent_soul_nurturing_pill',
    name: '培婴丹',
    summary: '寒甘而浮，水木相生。服后培元育婴，元婴突破良药。',
    mainHerbId: 'thousand_year_snow_lotus',
    assistantHerbId: 'soul_nurturing_wood',
    nature: 'cold',
    phase: Element.Water,
    direction: 'float',
    requiredResources: { essence: 100, herbs: 12, insight: 15 },
    outputResource: 'nascentSoulPills',
    outputAmount: 1,
    effect: { qi: 50 },
    dantoxin: 10,
    failureDantoxin: 6,
    baseSuccess: 0.30,
    seasonalAffinity: [Season.Winter],
  },
  nascent_soul_separation_pill: {
    id: 'nascent_soul_separation_pill',
    name: '出窍丹',
    summary: '寒苦而降，水水相济。服后元神出窍，修为与悟性齐增。',
    mainHerbId: 'nether_soul_grass',
    assistantHerbId: 'moon_dew_herb',
    nature: 'cold',
    phase: Element.Water,
    direction: 'descend',
    requiredResources: { essence: 80, herbs: 10, insight: 12 },
    outputResource: 'nascentSoulPills',
    outputAmount: 1,
    effect: { qi: 30, insight: 5 },
    dantoxin: 12,
    failureDantoxin: 7,
    baseSuccess: 0.28,
    seasonalAffinity: [Season.Winter, Season.Autumn],
  },
  nascent_soul_protection_pill: {
    id: 'nascent_soul_protection_pill',
    name: '护婴丹',
    summary: '温甘而升，金金相固。服后护婴安神，兼退丹毒。',
    mainHerbId: 'golden_coral_branch',
    assistantHerbId: 'golden_silk_vine',
    nature: 'warm',
    phase: Element.Metal,
    direction: 'rise',
    requiredResources: { essence: 90, herbs: 10, insight: 10 },
    outputResource: 'nascentSoulPills',
    outputAmount: 1,
    effect: { qi: 25, dantoxin: -8 },
    dantoxin: 5,
    failureDantoxin: 3,
    baseSuccess: 0.35,
    seasonalAffinity: [Season.Summer],
  },

  // === SpiritTransformation tier ===
  spirit_transform_pill: {
    id: 'spirit_transform_pill',
    name: '化神丹',
    summary: '热甘而升，火金相炼。服后化神入虚，修为大进。',
    mainHerbId: 'dragon_blood_grass',
    assistantHerbId: 'void_crystal_herb',
    nature: 'hot',
    phase: Element.Fire,
    direction: 'rise',
    requiredResources: { essence: 150, herbs: 15, insight: 25 },
    outputResource: 'spiritTransformPills',
    outputAmount: 1,
    effect: { qi: 80, insight: 10 },
    dantoxin: 15,
    failureDantoxin: 10,
    baseSuccess: 0.22,
    seasonalAffinity: [Season.Summer],
  },
  spirit_transform_fire_pill: {
    id: 'spirit_transform_fire_pill',
    name: '化火丹',
    summary: '热辛而升，火火相催。服后灵火蜕变，化神火候精进。',
    mainHerbId: 'phoenix_feather_fern',
    assistantHerbId: 'crimson_lotus',
    nature: 'hot',
    phase: Element.Fire,
    direction: 'rise',
    requiredResources: { essence: 120, herbs: 12, insight: 20 },
    outputResource: 'spiritTransformPills',
    outputAmount: 1,
    effect: { qi: 60 },
    dantoxin: 18,
    failureDantoxin: 12,
    baseSuccess: 0.25,
    seasonalAffinity: [Season.Summer],
  },

  // === Integration tier ===
  integration_pill: {
    id: 'integration_pill',
    name: '合体丹',
    summary: '平甘而浮，土木相合。服后天人合一，合体突破辅佐。',
    mainHerbId: 'chaos_lotus',
    assistantHerbId: 'thousand_year_pine_gum',
    nature: 'neutral',
    phase: Element.Earth,
    direction: 'float',
    requiredResources: { essence: 250, herbs: 20, insight: 40 },
    outputResource: 'integrationPills',
    outputAmount: 1,
    effect: { qi: 120, insight: 15 },
    dantoxin: 20,
    failureDantoxin: 14,
    baseSuccess: 0.18,
    seasonalAffinity: [Season.Summer, Season.Autumn],
  },
  integration_body_pill: {
    id: 'integration_body_pill',
    name: '融体丹',
    summary: '温淡而沉，土金相融。服后融体合道，兼愈伤势。',
    mainHerbId: 'earthheart_stone_powder',
    assistantHerbId: 'void_crystal_herb',
    nature: 'warm',
    phase: Element.Earth,
    direction: 'sink',
    requiredResources: { essence: 200, herbs: 18, insight: 35 },
    outputResource: 'integrationPills',
    outputAmount: 1,
    effect: { qi: 80, wounds: -5 },
    dantoxin: 15,
    failureDantoxin: 10,
    baseSuccess: 0.20,
    seasonalAffinity: [Season.Autumn, Season.Winter],
  },

  // === Mahayana tier ===
  mahayana_pill: {
    id: 'mahayana_pill',
    name: '大乘丹',
    summary: '凉甘而浮，水土相济。服后大乘境界大开，修为暴涨。',
    mainHerbId: 'heavenly_dew_grass',
    assistantHerbId: 'primordial_ginseng',
    nature: 'cool',
    phase: Element.Water,
    direction: 'float',
    requiredResources: { essence: 400, herbs: 25, insight: 60 },
    outputResource: 'mahayanaPills',
    outputAmount: 1,
    effect: { qi: 200, insight: 25 },
    dantoxin: 25,
    failureDantoxin: 18,
    baseSuccess: 0.12,
    seasonalAffinity: [Season.Spring],
  },
  mahayana_enlightenment_pill: {
    id: 'mahayana_enlightenment_pill',
    name: '悟道丹',
    summary: '凉甘而浮，水水相济。服后顿悟大道，悟性大增。',
    mainHerbId: 'cloud_petal',
    assistantHerbId: 'heavenly_dew_grass',
    nature: 'cool',
    phase: Element.Water,
    direction: 'float',
    requiredResources: { essence: 350, herbs: 22, insight: 50 },
    outputResource: 'mahayanaPills',
    outputAmount: 1,
    effect: { qi: 100, insight: 40 },
    dantoxin: 20,
    failureDantoxin: 14,
    baseSuccess: 0.15,
    seasonalAffinity: [Season.Spring, Season.Winter],
  },

  // === Tribulation tier ===
  tribulation_protection_pill: {
    id: 'tribulation_protection_pill',
    name: '渡劫护体丹',
    summary: '热辛而升，火金相护。服后护体渡劫，兼退丹毒。',
    mainHerbId: 'tribulation_grass',
    assistantHerbId: 'star_iron_moss',
    nature: 'hot',
    phase: Element.Fire,
    direction: 'rise',
    requiredResources: { essence: 500, herbs: 30, insight: 80 },
    outputResource: 'tribulationPills',
    outputAmount: 1,
    effect: { qi: 150, dantoxin: -20 },
    dantoxin: 15,
    failureDantoxin: 10,
    baseSuccess: 0.10,
    seasonalAffinity: [Season.Summer],
  },
  heavenly_tribulation_pill: {
    id: 'heavenly_tribulation_pill',
    name: '天劫丹',
    summary: '热辛而升，火土相催。服后天劫淬体，修为悟性齐升。',
    mainHerbId: 'thunder_essence_vine',
    assistantHerbId: 'primordial_ginseng',
    nature: 'hot',
    phase: Element.Fire,
    direction: 'rise',
    requiredResources: { essence: 600, herbs: 35, insight: 100 },
    outputResource: 'heavenlyTribulationPills',
    outputAmount: 1,
    effect: { qi: 300, insight: 30 },
    dantoxin: 30,
    failureDantoxin: 22,
    baseSuccess: 0.08,
    seasonalAffinity: [Season.Summer],
  },
  tribulation_soul_pill: {
    id: 'tribulation_soul_pill',
    name: '渡劫安魂丹',
    summary: '平淡而沉，土木相守。服后安魂定魄，渡劫心魔不侵。',
    mainHerbId: 'buddha_heart_leaf',
    assistantHerbId: 'soul_nurturing_wood',
    nature: 'neutral',
    phase: Element.Earth,
    direction: 'sink',
    requiredResources: { essence: 450, herbs: 28, insight: 70 },
    outputResource: 'tribulationPills',
    outputAmount: 1,
    effect: { qi: 100, dantoxin: -30, wounds: -3 },
    dantoxin: 10,
    failureDantoxin: 6,
    baseSuccess: 0.15,
    seasonalAffinity: [Season.Spring, Season.Autumn],
  },

  // === Special / Utility pills ===
  true_essence_pill: {
    id: 'true_essence_pill',
    name: '真元丹',
    summary: '温甘而升，金水相生。服后真元充实，聚气良药。',
    mainHerbId: 'golden_silk_vine',
    assistantHerbId: 'dew_vein_grass',
    nature: 'warm',
    phase: Element.Metal,
    direction: 'rise',
    requiredResources: { essence: 40, herbs: 6, insight: 5 },
    outputResource: 'spiritGatheringPills',
    outputAmount: 1,
    effect: { qi: 20 },
    dantoxin: 4,
    failureDantoxin: 2,
    baseSuccess: 0.50,
    seasonalAffinity: [Season.Spring, Season.Summer],
  },
  gathering_spirit_pill: {
    id: 'gathering_spirit_pill',
    name: '聚元丹',
    summary: '平甘而升，木土相和。服后灵气汇聚，修为增长。',
    mainHerbId: 'spirit_gathering_vine',
    assistantHerbId: 'yellow_dust_seed',
    nature: 'neutral',
    phase: Element.Wood,
    direction: 'rise',
    requiredResources: { essence: 55, herbs: 8, insight: 7 },
    outputResource: 'spiritGatheringPills',
    outputAmount: 1,
    effect: { qi: 30 },
    dantoxin: 6,
    failureDantoxin: 3,
    baseSuccess: 0.42,
    seasonalAffinity: [Season.Spring, Season.Summer],
  },
  body_tempering_pill: {
    id: 'body_tempering_pill',
    name: '锻体丹',
    summary: '寒咸而沉，金金相固。服后锻体强筋，伤势减轻。',
    mainHerbId: 'black_iron_root',
    assistantHerbId: 'iron_wire_moss',
    nature: 'cold',
    phase: Element.Metal,
    direction: 'sink',
    requiredResources: { essence: 45, herbs: 6, insight: 5 },
    outputResource: 'ironBodyPills',
    outputAmount: 1,
    effect: { wounds: -3 },
    dantoxin: 4,
    failureDantoxin: 2,
    baseSuccess: 0.48,
    seasonalAffinity: [Season.Autumn, Season.Winter],
  },
  soul_cleansing_pill: {
    id: 'soul_cleansing_pill',
    name: '洗魂丹',
    summary: '凉甘而浮，水土相济。服后洗魂净灵，大退丹毒。',
    mainHerbId: 'moon_dew_herb',
    assistantHerbId: 'buddha_heart_leaf',
    nature: 'cool',
    phase: Element.Water,
    direction: 'float',
    requiredResources: { essence: 60, herbs: 8, insight: 8 },
    outputResource: 'buddhaHeartPills',
    outputAmount: 1,
    effect: { dantoxin: -30, qi: 5 },
    dantoxin: 2,
    failureDantoxin: 1,
    baseSuccess: 0.40,
    seasonalAffinity: [Season.Spring, Season.Autumn],
  },
  extreme_foundation_pill: {
    id: 'extreme_foundation_pill',
    name: '极筑丹',
    summary: '温甘而升，土土相固。服后极筑根基，修为大增但丹毒亦重。',
    mainHerbId: 'nine_turn_ginseng',
    assistantHerbId: 'purple_ginseng',
    nature: 'warm',
    phase: Element.Earth,
    direction: 'rise',
    requiredResources: { essence: 100, herbs: 12, insight: 12 },
    outputResource: 'nineTurnFoundationPills',
    outputAmount: 1,
    effect: { qi: 40, dantoxin: 12 },
    dantoxin: 10,
    failureDantoxin: 6,
    baseSuccess: 0.28,
    seasonalAffinity: [Season.Autumn],
  },
};
