import { Realm, Resources } from '../game/types';

export interface BreakthroughRule {
  id: string;
  actionId: string;
  name: string;
  fromRealm: Realm;
  fromLayer: number;
  toRealm: Realm;
  toLayer: number;
  requiredResources: Partial<Resources>;
  baseSuccess: number;
  partialWindow: number;
  preparationCap: number;
  successFlag: string;
}

export const BREAKTHROUGH_RULES: Record<string, BreakthroughRule> = {
  qi_layer_2: {
    id: 'qi_layer_2',
    actionId: 'breakthrough_qi_2',
    name: '炼气二层',
    fromRealm: Realm.QiCondensation,
    fromLayer: 1,
    toRealm: Realm.QiCondensation,
    toLayer: 2,
    requiredResources: { essence: 60, qi: 30, insight: 3 },
    baseSuccess: 0.62,
    partialWindow: 0.16,
    preparationCap: 3,
    successFlag: 'reached_qi_layer_2',
  },
  qi_layer_3: {
    id: 'qi_layer_3',
    actionId: 'breakthrough_qi_3',
    name: '炼气三层',
    fromRealm: Realm.QiCondensation,
    fromLayer: 2,
    toRealm: Realm.QiCondensation,
    toLayer: 3,
    requiredResources: { essence: 70, qi: 45, insight: 5 },
    baseSuccess: 0.55,
    partialWindow: 0.14,
    preparationCap: 3,
    successFlag: 'reached_qi_layer_3',
  },
  qi_layer_4: {
    id: 'qi_layer_4',
    actionId: 'breakthrough_qi_4',
    name: '炼气四层',
    fromRealm: Realm.QiCondensation,
    fromLayer: 3,
    toRealm: Realm.QiCondensation,
    toLayer: 4,
    requiredResources: { essence: 80, qi: 60, insight: 8 },
    baseSuccess: 0.48,
    partialWindow: 0.14,
    preparationCap: 3,
    successFlag: 'reached_qi_layer_4',
  },
  qi_layer_5: {
    id: 'qi_layer_5',
    actionId: 'breakthrough_qi_5',
    name: '炼气五层',
    fromRealm: Realm.QiCondensation,
    fromLayer: 4,
    toRealm: Realm.QiCondensation,
    toLayer: 5,
    requiredResources: { essence: 90, qi: 75, insight: 10 },
    baseSuccess: 0.42,
    partialWindow: 0.13,
    preparationCap: 3,
    successFlag: 'reached_qi_layer_5',
  },
  qi_layer_6: {
    id: 'qi_layer_6',
    actionId: 'breakthrough_qi_6',
    name: '炼气六层',
    fromRealm: Realm.QiCondensation,
    fromLayer: 5,
    toRealm: Realm.QiCondensation,
    toLayer: 6,
    requiredResources: { essence: 100, qi: 90, insight: 12 },
    baseSuccess: 0.36,
    partialWindow: 0.12,
    preparationCap: 4,
    successFlag: 'reached_qi_layer_6',
  },
  qi_layer_7: {
    id: 'qi_layer_7',
    actionId: 'breakthrough_qi_7',
    name: '炼气七层',
    fromRealm: Realm.QiCondensation,
    fromLayer: 6,
    toRealm: Realm.QiCondensation,
    toLayer: 7,
    requiredResources: { essence: 110, qi: 110, insight: 15 },
    baseSuccess: 0.30,
    partialWindow: 0.12,
    preparationCap: 4,
    successFlag: 'reached_qi_layer_7',
  },
  qi_layer_8: {
    id: 'qi_layer_8',
    actionId: 'breakthrough_qi_8',
    name: '炼气八层',
    fromRealm: Realm.QiCondensation,
    fromLayer: 7,
    toRealm: Realm.QiCondensation,
    toLayer: 8,
    requiredResources: { essence: 130, qi: 130, insight: 18 },
    baseSuccess: 0.25,
    partialWindow: 0.11,
    preparationCap: 5,
    successFlag: 'reached_qi_layer_8',
  },
  qi_layer_9: {
    id: 'qi_layer_9',
    actionId: 'breakthrough_qi_9',
    name: '炼气九层',
    fromRealm: Realm.QiCondensation,
    fromLayer: 8,
    toRealm: Realm.QiCondensation,
    toLayer: 9,
    requiredResources: { essence: 150, qi: 150, insight: 22 },
    baseSuccess: 0.20,
    partialWindow: 0.10,
    preparationCap: 5,
    successFlag: 'reached_qi_layer_9',
  },
  foundation: {
    id: 'foundation',
    actionId: 'breakthrough_foundation',
    name: '筑基',
    fromRealm: Realm.QiCondensation,
    fromLayer: 9,
    toRealm: Realm.FoundationEstablishment,
    toLayer: 1,
    requiredResources: { essence: 180, qi: 160, insight: 25 },
    baseSuccess: 0.35,
    partialWindow: 0.18,
    preparationCap: 5,
    successFlag: 'reached_foundation',
  },
  golden_core: {
    id: 'golden_core',
    actionId: 'breakthrough_golden_core',
    name: '金丹',
    fromRealm: Realm.FoundationEstablishment,
    fromLayer: 1,
    toRealm: Realm.GoldenCore,
    toLayer: 1,
    requiredResources: { essence: 120, qi: 80, insight: 15 },
    baseSuccess: 0.30,
    partialWindow: 0.15,
    preparationCap: 6,
    successFlag: 'reached_golden_core',
  },
  nascent_soul: {
    id: 'nascent_soul',
    actionId: 'breakthrough_nascent_soul',
    name: '元婴',
    fromRealm: Realm.GoldenCore,
    fromLayer: 1,
    toRealm: Realm.NascentSoul,
    toLayer: 1,
    requiredResources: { essence: 150, qi: 150, insight: 30 },
    baseSuccess: 0.22,
    partialWindow: 0.12,
    preparationCap: 8,
    successFlag: 'reached_nascent_soul',
  },
  spirit_transformation: {
    id: 'spirit_transformation',
    actionId: 'breakthrough_spirit_transformation',
    name: '化神',
    fromRealm: Realm.NascentSoul,
    fromLayer: 1,
    toRealm: Realm.SpiritTransformation,
    toLayer: 1,
    requiredResources: { essence: 200, qi: 200, insight: 50 },
    baseSuccess: 0.28,
    partialWindow: 0.10,
    preparationCap: 10,
    successFlag: 'reached_spirit_transformation',
  },
  integration: {
    id: 'integration',
    actionId: 'breakthrough_integration',
    name: '合体',
    fromRealm: Realm.SpiritTransformation,
    fromLayer: 1,
    toRealm: Realm.Integration,
    toLayer: 1,
    requiredResources: { essence: 300, qi: 300, insight: 80 },
    baseSuccess: 0.25,
    partialWindow: 0.08,
    preparationCap: 12,
    successFlag: 'reached_integration',
  },
  mahayana: {
    id: 'mahayana',
    actionId: 'breakthrough_mahayana',
    name: '大乘',
    fromRealm: Realm.Integration,
    fromLayer: 1,
    toRealm: Realm.Mahayana,
    toLayer: 1,
    requiredResources: { essence: 500, qi: 500, insight: 120 },
    baseSuccess: 0.22,
    partialWindow: 0.06,
    preparationCap: 15,
    successFlag: 'reached_mahayana',
  },
  tribulation: {
    id: 'tribulation',
    actionId: 'breakthrough_tribulation',
    name: '渡劫',
    fromRealm: Realm.Mahayana,
    fromLayer: 1,
    toRealm: Realm.Tribulation,
    toLayer: 1,
    requiredResources: { essence: 800, qi: 800, insight: 200 },
    baseSuccess: 0.18,
    partialWindow: 0.04,
    preparationCap: 20,
    successFlag: 'reached_tribulation',
  },
};

export const BREAKTHROUGH_BY_ACTION = Object.fromEntries(
  Object.values(BREAKTHROUGH_RULES).map((rule) => [rule.actionId, rule])
) as Record<string, BreakthroughRule>;
