import { Element, Realm } from '../game/types';

export enum TechniqueGrade {
  Mortal = 'Mortal',     // 凡级
  Yellow = 'Yellow',     // 黄级
  Mystic = 'Mystic',     // 玄级
  Earth = 'Earth',       // 地级
  Heaven = 'Heaven',     // 天级
}

export const GRADE_LABELS: Record<TechniqueGrade, string> = {
  [TechniqueGrade.Mortal]: '凡级',
  [TechniqueGrade.Yellow]: '黄级',
  [TechniqueGrade.Mystic]: '玄级',
  [TechniqueGrade.Earth]: '地级',
  [TechniqueGrade.Heaven]: '天级',
};

export interface CultivationTechnique {
  id: string;
  name: string;
  phase: Element | null;
  description: string;
  grade: TechniqueGrade;
  requiredRealm: Realm;
  qiBonus: number;
  insightBonus: number;
  sideEffect?: string;
}

export const ELEMENT_LABELS: Record<Element, string> = {
  [Element.Wood]: '木',
  [Element.Fire]: '火',
  [Element.Earth]: '土',
  [Element.Metal]: '金',
  [Element.Water]: '水',
};

export const TECHNIQUES: Record<string, CultivationTechnique> = {
  // ──────────────── 凡级 (Mortal Grade) ────────────────
  small_breathing: {
    id: 'small_breathing',
    name: '小吐纳法',
    phase: null,
    description: '不偏五行，慢而少险。',
    grade: TechniqueGrade.Mortal,
    requiredRealm: Realm.Mortal,
    qiBonus: 1,
    insightBonus: 0,
  },
  wood_breathing: {
    id: 'wood_breathing',
    name: '引木诀',
    phase: Element.Wood,
    description: '顺木相生发，春日和药地较顺。',
    grade: TechniqueGrade.Mortal,
    requiredRealm: Realm.Mortal,
    qiBonus: 2,
    insightBonus: 0,
  },
  fire_breathing: {
    id: 'fire_breathing',
    name: '伏火诀',
    phase: Element.Fire,
    description: '借火相催动，进境快而躁。',
    grade: TechniqueGrade.Mortal,
    requiredRealm: Realm.Mortal,
    qiBonus: 2,
    insightBonus: 0,
    sideEffect: '火气躁动，心魔风险微增',
  },
  earth_breathing: {
    id: 'earth_breathing',
    name: '守土诀',
    phase: Element.Earth,
    description: '守中调和，适合居处日课。',
    grade: TechniqueGrade.Mortal,
    requiredRealm: Realm.Mortal,
    qiBonus: 1,
    insightBonus: 1,
  },
  metal_breathing: {
    id: 'metal_breathing',
    name: '敛金诀',
    phase: Element.Metal,
    description: '收束气机，秋日和规矩之地较顺。',
    grade: TechniqueGrade.Mortal,
    requiredRealm: Realm.Mortal,
    qiBonus: 2,
    insightBonus: 0,
  },
  water_breathing: {
    id: 'water_breathing',
    name: '听水诀',
    phase: Element.Water,
    description: '藏息入静，冬日和闭关较顺。',
    grade: TechniqueGrade.Mortal,
    requiredRealm: Realm.Mortal,
    qiBonus: 1,
    insightBonus: 1,
  },
  mixed_breathing: {
    id: 'mixed_breathing',
    name: '杂息法',
    phase: null,
    description: '不拘五行，杂根之人的笨拙之路，慢但可辨。',
    grade: TechniqueGrade.Mortal,
    requiredRealm: Realm.Mortal,
    qiBonus: 1,
    insightBonus: 1,
  },
  qingyun_method: {
    id: 'qingyun_method',
    name: '清息诀',
    phase: Element.Wood,
    description: '修行根基之法，青木养气。',
    grade: TechniqueGrade.Mortal,
    requiredRealm: Realm.Mortal,
    qiBonus: 2,
    insightBonus: 1,
  },
  tiegu_method: {
    id: 'tiegu_method',
    name: '铁骨功',
    phase: Element.Metal,
    description: '锻体固基，肉身强化。',
    grade: TechniqueGrade.Mortal,
    requiredRealm: Realm.Mortal,
    qiBonus: 1,
    insightBonus: 0,
    sideEffect: '金气伤脉，长期修炼需辅以调息',
  },
  youyun_step: {
    id: 'youyun_step',
    name: '游云步',
    phase: Element.Water,
    description: '身法轻灵，遁速提升。',
    grade: TechniqueGrade.Mortal,
    requiredRealm: Realm.QiCondensation,
    qiBonus: 1,
    insightBonus: 1,
  },

  // ──────────────── 黄级 (Yellow Grade) ────────────────
  steady_heart_method: {
    id: 'steady_heart_method',
    name: '安心诀',
    phase: Element.Earth,
    description: '守中不动，适合调息养心，降低心魔风险。',
    grade: TechniqueGrade.Yellow,
    requiredRealm: Realm.QiCondensation,
    qiBonus: 2,
    insightBonus: 1,
  },
  sharp_metal_method: {
    id: 'sharp_metal_method',
    name: '锋金诀',
    phase: Element.Metal,
    description: '锐气入脉，斗法加成，但不适合长期闭关。',
    grade: TechniqueGrade.Yellow,
    requiredRealm: Realm.QiCondensation,
    qiBonus: 3,
    insightBonus: 0,
    sideEffect: '锐气伤神，长期闭关效率递减',
  },
  cloud_step_method: {
    id: 'cloud_step_method',
    name: '云步诀',
    phase: Element.Water,
    description: '步履轻盈如云，遁速加成。',
    grade: TechniqueGrade.Yellow,
    requiredRealm: Realm.QiCondensation,
    qiBonus: 1,
    insightBonus: 2,
  },
  thunder_palm_method: {
    id: 'thunder_palm_method',
    name: '雷掌诀',
    phase: Element.Fire,
    description: '掌心蓄雷，出手刚猛，斗法增伤。',
    grade: TechniqueGrade.Yellow,
    requiredRealm: Realm.QiCondensation,
    qiBonus: 3,
    insightBonus: 0,
    sideEffect: '雷火反噬，心魔风险微增',
  },
  jade_bone_art: {
    id: 'jade_bone_art',
    name: '玉骨功',
    phase: Element.Earth,
    description: '锻体固骨，伤势恢复加快。',
    grade: TechniqueGrade.Yellow,
    requiredRealm: Realm.QiCondensation,
    qiBonus: 1,
    insightBonus: 1,
  },
  wind_sword_intent: {
    id: 'wind_sword_intent',
    name: '风剑意',
    phase: Element.Metal,
    description: '剑随心意，风起即杀。需有剑修倾向。',
    grade: TechniqueGrade.Yellow,
    requiredRealm: Realm.QiCondensation,
    qiBonus: 2,
    insightBonus: 2,
    sideEffect: '剑意侵蚀，情绪易波动',
  },
  spirit_eye_method: {
    id: 'spirit_eye_method',
    name: '灵目术',
    phase: Element.Water,
    description: '开天目，视远辨微，见闻获取增加。',
    grade: TechniqueGrade.Yellow,
    requiredRealm: Realm.QiCondensation,
    qiBonus: 0,
    insightBonus: 4,
  },
  blood_iron_body: {
    id: 'blood_iron_body',
    name: '血铁身',
    phase: Element.Metal,
    description: '舍肉铸铁，伤减但心魔易生。',
    grade: TechniqueGrade.Yellow,
    requiredRealm: Realm.FoundationEstablishment,
    qiBonus: 2,
    insightBonus: 0,
    sideEffect: '血铁侵蚀，心魔风险显著增加',
  },
  phantom_shadow_art: {
    id: 'phantom_shadow_art',
    name: '影遁术',
    phase: Element.Water,
    description: '隐遁入影，避险脱身。',
    grade: TechniqueGrade.Yellow,
    requiredRealm: Realm.FoundationEstablishment,
    qiBonus: 1,
    insightBonus: 2,
  },
  verdant_pulse_method: {
    id: 'verdant_pulse_method',
    name: '青脉诀',
    phase: Element.Wood,
    description: '木气养脉，闭关修炼效率提升。',
    grade: TechniqueGrade.Yellow,
    requiredRealm: Realm.QiCondensation,
    qiBonus: 2,
    insightBonus: 1,
  },
  crimson_furnace_art: {
    id: 'crimson_furnace_art',
    name: '赤炉功',
    phase: Element.Fire,
    description: '丹火内蕴，炼丹成功率加成。',
    grade: TechniqueGrade.Yellow,
    requiredRealm: Realm.FoundationEstablishment,
    qiBonus: 2,
    insightBonus: 1,
  },
  purple_cloud_art: {
    id: 'purple_cloud_art',
    name: '紫云功',
    phase: Element.Fire,
    description: '火云紫气，金丹辅修。',
    grade: TechniqueGrade.Yellow,
    requiredRealm: Realm.FoundationEstablishment,
    qiBonus: 3,
    insightBonus: 1,
    sideEffect: '火毒内蕴，丹毒风险微增',
  },
  ice_heart_method: {
    id: 'ice_heart_method',
    name: '冰心诀',
    phase: Element.Water,
    description: '冰心凝意，心魔克制。',
    grade: TechniqueGrade.Yellow,
    requiredRealm: Realm.QiCondensation,
    qiBonus: 1,
    insightBonus: 3,
  },
  mountain_seal_art: {
    id: 'mountain_seal_art',
    name: '山镇印',
    phase: Element.Earth,
    description: '山岳为印，攻防兼备。',
    grade: TechniqueGrade.Yellow,
    requiredRealm: Realm.FoundationEstablishment,
    qiBonus: 2,
    insightBonus: 1,
  },
  swift_wind_blade: {
    id: 'swift_wind_blade',
    name: '疾风刀',
    phase: Element.Metal,
    description: '风刃如刀，远程斗法。',
    grade: TechniqueGrade.Yellow,
    requiredRealm: Realm.QiCondensation,
    qiBonus: 2,
    insightBonus: 1,
    sideEffect: '锋芒过盛，易招杀劫',
  },
  wood_spirit_body: {
    id: 'wood_spirit_body',
    name: '木灵体',
    phase: Element.Wood,
    description: '木气化身，药性亲和。',
    grade: TechniqueGrade.Yellow,
    requiredRealm: Realm.FoundationEstablishment,
    qiBonus: 1,
    insightBonus: 2,
  },
  flowing_river_method: {
    id: 'flowing_river_method',
    name: '流河诀',
    phase: Element.Water,
    description: '水行绵延，气如长河。',
    grade: TechniqueGrade.Yellow,
    requiredRealm: Realm.QiCondensation,
    qiBonus: 2,
    insightBonus: 2,
  },
  flame_ring_art: {
    id: 'flame_ring_art',
    name: '火环术',
    phase: Element.Fire,
    description: '火环护体，攻守兼备。',
    grade: TechniqueGrade.Yellow,
    requiredRealm: Realm.FoundationEstablishment,
    qiBonus: 2,
    insightBonus: 1,
  },

  // ──────────────── 玄级 (Mystic Grade) ────────────────
  void_heart_method: {
    id: 'void_heart_method',
    name: '虚心诀',
    phase: Element.Earth,
    description: '放空执念，心魔抑制加成，但修为进展极缓。',
    grade: TechniqueGrade.Mystic,
    requiredRealm: Realm.FoundationEstablishment,
    qiBonus: 1,
    insightBonus: 4,
    sideEffect: '修为进展极缓',
  },
  heavenly_circulation: {
    id: 'heavenly_circulation',
    name: '周天运转法',
    phase: null,
    description: '不偏五行，大周天运转，中后期通用功法。',
    grade: TechniqueGrade.Mystic,
    requiredRealm: Realm.FoundationEstablishment,
    qiBonus: 3,
    insightBonus: 3,
  },
  demonic_flame_art: {
    id: 'demonic_flame_art',
    name: '魔焰诀',
    phase: Element.Fire,
    description: '速成但危险，修为涨速快，心魔与丹毒风险均高。',
    grade: TechniqueGrade.Mystic,
    requiredRealm: Realm.FoundationEstablishment,
    qiBonus: 5,
    insightBonus: 0,
    sideEffect: '心魔与丹毒风险均高',
  },
  golden_sword_intent: {
    id: 'golden_sword_intent',
    name: '金剑意',
    phase: Element.Metal,
    description: '金性至锐，剑意无双。',
    grade: TechniqueGrade.Mystic,
    requiredRealm: Realm.FoundationEstablishment,
    qiBonus: 3,
    insightBonus: 3,
    sideEffect: '金锐伤情，修者性情渐趋冷酷',
  },
  fire_phoenix_art: {
    id: 'fire_phoenix_art',
    name: '火凤功',
    phase: Element.Fire,
    description: '浴火重生，金丹火候。',
    grade: TechniqueGrade.Mystic,
    requiredRealm: Realm.GoldenCore,
    qiBonus: 4,
    insightBonus: 2,
    sideEffect: '火凤涅槃之苦，每次运转皆受灼痛',
  },
  deep_sea_art: {
    id: 'deep_sea_art',
    name: '深海功',
    phase: Element.Water,
    description: '海纳百川，元婴辅修。',
    grade: TechniqueGrade.Mystic,
    requiredRealm: Realm.FoundationEstablishment,
    qiBonus: 3,
    insightBonus: 3,
  },
  earth_spirit_seal: {
    id: 'earth_spirit_seal',
    name: '地灵印',
    phase: Element.Earth,
    description: '大地之力，防御极致。',
    grade: TechniqueGrade.Mystic,
    requiredRealm: Realm.GoldenCore,
    qiBonus: 2,
    insightBonus: 3,
  },
  thousand_wood_art: {
    id: 'thousand_wood_art',
    name: '千木功',
    phase: Element.Wood,
    description: '万木归一，续命延寿。',
    grade: TechniqueGrade.Mystic,
    requiredRealm: Realm.FoundationEstablishment,
    qiBonus: 2,
    insightBonus: 3,
  },
  thunder_tribulation_art: {
    id: 'thunder_tribulation_art',
    name: '雷劫功',
    phase: null,
    description: '天雷淬体，渡劫辅修。',
    grade: TechniqueGrade.Mystic,
    requiredRealm: Realm.GoldenCore,
    qiBonus: 3,
    insightBonus: 4,
    sideEffect: '天雷淬体之痛，体质弱者恐有反噬',
  },
  moon_shadow_art: {
    id: 'moon_shadow_art',
    name: '月影术',
    phase: Element.Water,
    description: '月华如水，夜修加成。',
    grade: TechniqueGrade.Mystic,
    requiredRealm: Realm.FoundationEstablishment,
    qiBonus: 3,
    insightBonus: 3,
  },
  blazing_sword_art: {
    id: 'blazing_sword_art',
    name: '炎剑功',
    phase: Element.Fire,
    description: '火行剑意，刚猛绝伦。',
    grade: TechniqueGrade.Mystic,
    requiredRealm: Realm.GoldenCore,
    qiBonus: 4,
    insightBonus: 2,
    sideEffect: '火毒侵脉，需辅以清凉丹药',
  },

  // ──────────────── 地级 (Earth Grade) ────────────────
  heavenly_sword_method: {
    id: 'heavenly_sword_method',
    name: '天剑诀',
    phase: Element.Metal,
    description: '天道剑意，化神锋芒。',
    grade: TechniqueGrade.Earth,
    requiredRealm: Realm.GoldenCore,
    qiBonus: 5,
    insightBonus: 4,
    sideEffect: '天道无情，修者六欲渐消',
  },
  nine_sun_art: {
    id: 'nine_sun_art',
    name: '九阳功',
    phase: Element.Fire,
    description: '九阳真火，炼丹极致。',
    grade: TechniqueGrade.Earth,
    requiredRealm: Realm.GoldenCore,
    qiBonus: 5,
    insightBonus: 3,
    sideEffect: '阳火灼阴，寿元消耗加剧',
  },
  void_sea_method: {
    id: 'void_sea_method',
    name: '虚海诀',
    phase: Element.Water,
    description: '虚空之海，合体辅修。',
    grade: TechniqueGrade.Earth,
    requiredRealm: Realm.GoldenCore,
    qiBonus: 4,
    insightBonus: 5,
  },
  eternal_earth_art: {
    id: 'eternal_earth_art',
    name: '厚土功',
    phase: Element.Earth,
    description: '万劫不灭，肉身大成。',
    grade: TechniqueGrade.Earth,
    requiredRealm: Realm.NascentSoul,
    qiBonus: 3,
    insightBonus: 4,
  },
  life_and_death_art: {
    id: 'life_and_death_art',
    name: '生死诀',
    phase: Element.Wood,
    description: '生死轮回，大乘辅修。',
    grade: TechniqueGrade.Earth,
    requiredRealm: Realm.NascentSoul,
    qiBonus: 4,
    insightBonus: 5,
    sideEffect: '生死之力逆乱，偶有神识恍惚',
  },
  star_fall_art: {
    id: 'star_fall_art',
    name: '陨星功',
    phase: Element.Fire,
    description: '陨星之力，斗法无敌。',
    grade: TechniqueGrade.Earth,
    requiredRealm: Realm.GoldenCore,
    qiBonus: 6,
    insightBonus: 2,
    sideEffect: '陨星之力暴烈，经脉易损',
  },
  demon_suppression_seal: {
    id: 'demon_suppression_seal',
    name: '镇魔印',
    phase: Element.Earth,
    description: '伏魔镇妖，天劫护体。',
    grade: TechniqueGrade.Earth,
    requiredRealm: Realm.NascentSoul,
    qiBonus: 3,
    insightBonus: 4,
  },

  // ──────────────── 天级 (Heaven Grade) ────────────────
  chaos_art: {
    id: 'chaos_art',
    name: '混沌诀',
    phase: null,
    description: '混沌初开，万法归一。',
    grade: TechniqueGrade.Heaven,
    requiredRealm: Realm.NascentSoul,
    qiBonus: 7,
    insightBonus: 7,
    sideEffect: '混沌之力难以驾驭，修为不稳时有走火之险',
  },
  heavenly_tribulation_method: {
    id: 'heavenly_tribulation_method',
    name: '天劫诀',
    phase: null,
    description: '引天雷入体，渡劫无惧。',
    grade: TechniqueGrade.Heaven,
    requiredRealm: Realm.NascentSoul,
    qiBonus: 6,
    insightBonus: 8,
    sideEffect: '天雷引体，非大毅力者不可轻修',
  },
  reincarnation_art: {
    id: 'reincarnation_art',
    name: '轮回功',
    phase: null,
    description: '轮回不息，长生之路。',
    grade: TechniqueGrade.Heaven,
    requiredRealm: Realm.NascentSoul,
    qiBonus: 5,
    insightBonus: 9,
    sideEffect: '轮回之念侵心，偶有前世记忆错乱',
  },
  starry_sky_method: {
    id: 'starry_sky_method',
    name: '星空诀',
    phase: null,
    description: '星空为炉，天地为鼎。',
    grade: TechniqueGrade.Heaven,
    requiredRealm: Realm.NascentSoul,
    qiBonus: 8,
    insightBonus: 6,
    sideEffect: '星空之力浩瀚，肉身负荷极大',
  },
  origin_art: {
    id: 'origin_art',
    name: '太初诀',
    phase: null,
    description: '返璞归真，道之根本。',
    grade: TechniqueGrade.Heaven,
    requiredRealm: Realm.NascentSoul,
    qiBonus: 6,
    insightBonus: 10,
    sideEffect: '太初之力归元，一切加成归零后重聚，非悟道者不可修',
  },
};

export const TECHNIQUE_BY_ELEMENT: Record<Element, string> = {
  [Element.Wood]: 'wood_breathing',
  [Element.Fire]: 'fire_breathing',
  [Element.Earth]: 'earth_breathing',
  [Element.Metal]: 'metal_breathing',
  [Element.Water]: 'water_breathing',
};
