import { Location } from '../game/types';

export const LOCATIONS: Record<string, Location> = {
  'home': {
    id: 'home',
    name: '居处',
    availableActions: [
      'kuzuo',
      'tuna',
      'tiaoxi',
      'bianyao',
      'yinqi',
      'inspect_root',
      'attune_technique',
      'study_qi_formula',
      'study_steady_formula',
      'study_cleansing_formula',
      'brew_qi_pill',
      'brew_stabilizing_powder',
      'brew_cleansing_pill',
      'take_qi_pill',
      'take_stabilizing_powder',
      'take_cleansing_pill',
      'study_meridian_cleansing_formula',
      'brew_meridian_cleansing_pill',
      'take_meridian_cleansing_pill',
      'study_foundation_strengthening_formula',
      'brew_foundation_strengthening_pill',
      'take_foundation_strengthening_pill',
      'study_spirit_gathering_formula',
      'brew_spirit_gathering_pill',
      'take_spirit_gathering_pill',
      'study_warm_furnace_formula',
      'brew_warm_furnace_pill',
      'take_warm_furnace_pill',
      'study_night_sitting_formula',
      'brew_night_sitting_pill',
      'take_night_sitting_pill',
      'study_cloud_gathering_formula',
      'brew_cloud_gathering_pill',
      'take_cloud_gathering_pill',
      'study_iron_body_formula',
      'brew_iron_body_pill',
      'take_iron_body_pill',
      'study_demon_bane_formula',
      'brew_demon_bane_pill',
      'take_demon_bane_pill',
      'study_foundation_explosion_formula',
      'brew_foundation_explosion_pill',
      'take_foundation_explosion_pill',
      'study_spirit_vein_formula',
      'brew_spirit_vein_pill',
      'take_spirit_vein_pill',
      'study_shadow_escape_formula',
      'brew_shadow_escape_pill',
      'take_shadow_escape_pill',
      'study_longevity_formula',
      'brew_longevity_pill',
      'take_longevity_pill',
      'study_fire_furnace_formula',
      'brew_fire_furnace_pill',
      'take_fire_furnace_pill',
      'study_nine_turn_foundation_formula',
      'brew_nine_turn_foundation_pill',
      'take_nine_turn_foundation_pill',
      'study_buddha_heart_formula',
      'brew_buddha_heart_pill',
      'take_buddha_heart_pill',
      'stabilize_bottleneck',
      'withdraw_foundation',
      'breakthrough_qi_2',
      'breakthrough_qi_3',
      'breakthrough_qi_4',
      'breakthrough_qi_5',
      'breakthrough_qi_6',
      'breakthrough_qi_7',
      'breakthrough_qi_8',
      'breakthrough_qi_9',
      'breakthrough_foundation',
      'rike_tuna',
      'short_retreat',
      'foundation_daily_practice',
      'foundation_meditation',
      'establish_dwelling',
      'upgrade_dwelling',
      'install_formation',
      'recruit_servant',
      'recruit_disciple',
      'assign_herb_gathering',
      'assign_patrol_duty',
      'collect_follower_income',
      'breakthrough_golden_core',
      'breakthrough_nascent_soul',
      'breakthrough_spirit_transformation',
      'breakthrough_integration',
      'breakthrough_mahayana',
      'breakthrough_tribulation',
      'golden_core_practice',
      'nascent_soul_practice',
      'spirit_transformation_practice',
      'integration_practice',
      'mahayana_practice',
      'tribulation_practice',
      'confront_demon',
      'suppress_demon',
      'ignore_demon',
    ],
    eventWeights: {
      'find_jade_slip': 1.5,
      'dantoxin_in_meridians': 1.4,
      'dantoxin_meridian_decay': 1.4,
      'alchemist_insight': 1.2,
      'foundation_scar_aches': 1.3,
      'winter_stillness': 1.2,
      'foundation_scar_lingering': 1.3,
      'foundation_establishment_morning': 2.0,
    },
    qiDensity: 1,
    danger: 0,
    priceModifier: 1.0,
  },
  'mountain_path': {
    id: 'mountain_path',
    name: '山路',
    availableActions: ['caiyao', 'xunshan'],
    eventWeights: {
      'wounded_cultivator': 1.4,
      'rain_after_sprouts': 1.3,
      'wounded_cultivator_return': 1.2,
      'wounded_cultivator_grudge': 1.3,
    },
    qiDensity: 1.2,
    danger: 2,
    priceModifier: 1.0,
  },
  'market': {
    id: 'market',
    name: '坊市',
    availableActions: ['trade', 'gossip', 'borrow_foundation_pill', 'open_market_stall', 'buy_rare_herbs'],
    eventWeights: {
      'market_rumor': 1.2,
      'market_price_rise': 1.2,
      'market_foundation_debt': 1.4,
      'outer_gate_rules': 1.2,
      'foundation_debt_collector': 1.5,
    },
    qiDensity: 0.8,
    danger: 1,
    priceModifier: 1.0,
  },
  'outer_gate': {
    id: 'outer_gate',
    name: '外门',
    availableActions: [
      'sect_chore',
      'sect_errand',
      'sect_supply',
      'sect_roll_call',
      'sect_patrol',
      'listen_lesson',
      'gossip',
      'seek_foundation_guardian',
      'inner_gate_rumor',
    ],
    eventWeights: {
      'outer_gate_rules': 1.4,
      'outer_gate_register': 1.5,
      'outer_gate_guardian_account': 1.4,
      'outer_gate_missed_roll_call': 1.5,
      'outer_gate_patrol_report': 1.3,
      'market_rumor': 0.5,
      'guardian_favor_recalled': 1.4,
    },
    qiDensity: 0.9,
    danger: 1,
    priceModifier: 1.05,
  },
  'cave_dwelling': {
    id: 'cave_dwelling',
    name: '洞府',
    availableActions: [
      'foundation_daily_practice',
      'foundation_meditation',
      'short_retreat',
      'study_meridian_cleansing_formula',
      'brew_meridian_cleansing_pill',
      'take_meridian_cleansing_pill',
      'study_foundation_strengthening_formula',
      'brew_foundation_strengthening_pill',
      'take_foundation_strengthening_pill',
      'study_spirit_gathering_formula',
      'brew_spirit_gathering_pill',
      'take_spirit_gathering_pill',
      'study_warm_furnace_formula',
      'brew_warm_furnace_pill',
      'take_warm_furnace_pill',
      'study_night_sitting_formula',
      'brew_night_sitting_pill',
      'take_night_sitting_pill',
      'study_cloud_gathering_formula',
      'brew_cloud_gathering_pill',
      'take_cloud_gathering_pill',
      'study_iron_body_formula',
      'brew_iron_body_pill',
      'take_iron_body_pill',
      'study_demon_bane_formula',
      'brew_demon_bane_pill',
      'take_demon_bane_pill',
      'study_foundation_explosion_formula',
      'brew_foundation_explosion_pill',
      'take_foundation_explosion_pill',
      'study_spirit_vein_formula',
      'brew_spirit_vein_pill',
      'take_spirit_vein_pill',
      'study_shadow_escape_formula',
      'brew_shadow_escape_pill',
      'take_shadow_escape_pill',
      'study_longevity_formula',
      'brew_longevity_pill',
      'take_longevity_pill',
      'study_fire_furnace_formula',
      'brew_fire_furnace_pill',
      'take_fire_furnace_pill',
      'study_nine_turn_foundation_formula',
      'brew_nine_turn_foundation_pill',
      'take_nine_turn_foundation_pill',
      'study_buddha_heart_formula',
      'brew_buddha_heart_pill',
      'take_buddha_heart_pill',
      'upgrade_dwelling',
      'install_formation',
      'recruit_servant',
      'recruit_disciple',
      'assign_herb_gathering',
      'assign_patrol_duty',
      'collect_follower_income',
    ],
    eventWeights: { find_jade_slip: 1.2, alchemist_insight: 1.0, winter_stillness: 1.2, technique_insight: 1.3, qi_deviation: 0.8, foundation_dream: 1.0 },
    qiDensity: 2,
    danger: 0,
    priceModifier: 1.0,
  },
  'inner_gate': {
    id: 'inner_gate',
    name: '内门',
    availableActions: [
      'inner_gate_task',
      'report_task_completion',
      'attend_sect_ceremony',
      'inner_gate_rumor',
    ],
    eventWeights: {
      'inner_gate_admission': 1.5,
      'sect_discipline_hearing': 1.4,
      'fellow_disciple_rivalry': 1.2,
    },
    qiDensity: 3,
    danger: 0,
    priceModifier: 0.95,
  },
  'stream_valley': {
    id: 'stream_valley',
    name: '溪谷',
    availableActions: [
      'caiyao',
      'water_meditation',
      'collect_night_dew',
    ],
    eventWeights: {
      'stream_valley_meditation': 1.3,
      'stream_valley_herb_find': 1.2,
      'stream_valley_encounter': 1.1,
      'mountain_elder_visit': 1.4,
    },
    qiDensity: 1.5,
    danger: 1,
    priceModifier: 1.0,
  },
  'abandoned_temple': {
    id: 'abandoned_temple',
    name: '废观',
    availableActions: [
      'explore_ruins',
      'sweep_temple',
      'read_stone_tablet',
    ],
    eventWeights: {
      'temple_old_talisman': 1.3,
      'temple_forbidden_knowledge': 1.2,
      'temple_wandering_lecturer': 1.4,
      'temple_candle_heart': 1.1,
    },
    qiDensity: 1.8,
    danger: 2,
    priceModifier: 1.0,
  },
  'herb_slope': {
    id: 'herb_slope',
    name: '药坡',
    availableActions: [
      'caiyao',
      'identify_herb',
      'protect_seedling',
    ],
    eventWeights: {
      'herb_slope_seasonal_bloom': 1.5,
      'herb_slope_pest': 1.2,
      'herb_slope_rival_gatherer': 1.3,
    },
    qiDensity: 1.3,
    danger: 1,
    priceModifier: 1.0,
  },
  'ferry_crossing': {
    id: 'ferry_crossing',
    name: '渡口',
    availableActions: [
      'listen_traveler',
      'hire_boat',
      'kuzuo',
      'tiaoxi',
    ],
    eventWeights: {
      'ferry_foreign_news': 1.3,
      'ferry_missing_person': 1.2,
      'ferry_tax': 1.4,
      'ferry_patrol_encounter': 1.2,
    },
    qiDensity: 0.7,
    danger: 2,
    priceModifier: 1.1,
  },
  'spirit_field': {
    id: 'spirit_field',
    name: '灵田',
    availableActions: [
      'plant_herb',
      'harvest_herb',
      'tend_field',
    ],
    eventWeights: {
      'spirit_field_blight': 1.3,
      'spirit_field_spirit_rain': 1.5,
      'spirit_field_pest_infestation': 1.2,
    },
    qiDensity: 1.4,
    danger: 0,
    priceModifier: 1.0,
    seasonalModifiers: {
      Spring: 1.3,
      Summer: 1.1,
      Autumn: 0.9,
      Winter: 0.7,
    },
  },
  'pill_hall': {
    id: 'pill_hall',
    name: '丹房',
    availableActions: [
      'use_furnace',
      'study_advanced_formula',
    ],
    eventWeights: {
      'pill_hall_furnace_accident': 1.2,
      'pill_hall_senior_guidance': 1.4,
      'pill_hall_waste_residue': 1.1,
    },
    qiDensity: 1.0,
    danger: 0,
    priceModifier: 0.95,
  },
  'sword_pavilion': {
    id: 'sword_pavilion',
    name: '剑阁',
    availableActions: [
      'practice_sword',
      'observe_sword_intent',
    ],
    eventWeights: {
      'sword_pavilion_sword_cry': 1.3,
      'sword_pavilion_senior_duel': 1.2,
      'sword_pavilion_lost_technique': 1.5,
    },
    qiDensity: 2.5,
    danger: 0,
    priceModifier: 1.1,
  },
  'sect_hall': {
    id: 'sect_hall',
    name: '宗门大殿',
    availableActions: [
      'attend_ceremony',
      'receive_mission',
    ],
    eventWeights: {
      'sect_hall_announcement': 1.5,
      'sect_hall_discipline_summon': 1.3,
      'sect_hall_reward_ceremony': 1.2,
    },
    qiDensity: 2.0,
    danger: 0,
    priceModifier: 1.0,
  },
  'deep_temple': {
    id: 'deep_temple',
    name: '荒庙深处',
    availableActions: [
      'search_altar',
      'meditate_dark',
    ],
    eventWeights: {
      'deep_temple_whisper': 1.4,
      'deep_temple_shadow_encounter': 1.3,
      'deep_temple_hidden_scroll': 1.5,
    },
    qiDensity: 2.2,
    danger: 3,
    priceModifier: 1.0,
    seasonalModifiers: {
      Spring: 1.0,
      Summer: 1.0,
      Autumn: 1.2,
      Winter: 1.4,
    },
  },
  'mountain_cave': {
    id: 'mountain_cave',
    name: '山腹溶洞',
    availableActions: [
      'mine_crystal',
      'explore_depths',
    ],
    eventWeights: {
      'mountain_cave_collapse': 1.3,
      'mountain_cave_crystal_vein': 1.4,
      'mountain_cave_underground_river': 1.2,
    },
    qiDensity: 3.0,
    danger: 3,
    priceModifier: 1.0,
    seasonalModifiers: {
      Spring: 1.1,
      Summer: 1.0,
      Autumn: 1.0,
      Winter: 1.2,
    },
  },
  'tea_house': {
    id: 'tea_house',
    name: '镇外茶肆',
    availableActions: [
      'drink_tea',
      'listen_rumor',
      'gamble_dice',
    ],
    eventWeights: {
      'tea_house_stranger': 1.5,
      'tea_house_gambler_quarrel': 1.3,
      'tea_house_merchant_tip': 1.2,
    },
    qiDensity: 0.6,
    danger: 1,
    priceModifier: 1.05,
  },
  'demonic_forest': {
    id: 'demonic_forest',
    name: '妖兽林',
    availableActions: [
      'hunt_beast',
      'gather_demonic_herb',
      'set_trap',
    ],
    eventWeights: {
      'demonic_forest_beast_ambush': 1.5,
      'demonic_forest_rare_herb': 1.3,
      'demonic_forest_terrifying_roar': 1.2,
    },
    qiDensity: 1.8,
    danger: 4,
    priceModifier: 1.0,
    seasonalModifiers: {
      Spring: 1.2,
      Summer: 1.3,
      Autumn: 1.0,
      Winter: 0.8,
    },
  },
  'celestial_cliff': {
    id: 'celestial_cliff',
    name: '天柱崖',
    availableActions: [
      'cliff_meditation',
      'face_heavenly_wind',
    ],
    eventWeights: {
      'celestial_cliff_wind_test': 1.4,
      'celestial_cliff_breakthrough_sign': 1.5,
      'celestial_cliff_falling_danger': 1.3,
    },
    qiDensity: 4.0,
    danger: 2,
    priceModifier: 1.0,
    seasonalModifiers: {
      Spring: 1.0,
      Summer: 1.1,
      Autumn: 1.2,
      Winter: 1.4,
    },
  },
  'core_gate': {
    id: 'core_gate',
    name: '核心峰',
    availableActions: [
      'core_gate_cultivation',
      'core_gate_exchange',
      'seek_elder_guidance',
    ],
    eventWeights: {
      'core_gate_senior_guidance': 1.4,
      'core_gate_technique_scroll': 1.3,
    },
    qiDensity: 4.0,
    danger: 0,
    priceModifier: 0.90,
  },
  'spirit_lake': {
    id: 'spirit_lake',
    name: '灵湖',
    availableActions: [
      'spirit_lake_meditation',
      'dive_for_treasure',
    ],
    eventWeights: {
      'spirit_lake_reflection': 1.3,
      'spirit_lake_treasure': 1.2,
    },
    qiDensity: 3.5,
    danger: 1,
    priceModifier: 1.0,
  },
  'thunder_peak': {
    id: 'thunder_peak',
    name: '雷峰',
    availableActions: [
      'face_tribulation',
      'thunder_cultivation',
    ],
    eventWeights: {
      'thunder_peak_strike': 1.4,
      'thunder_peak_insight': 1.3,
    },
    qiDensity: 5.0,
    danger: 3,
    priceModifier: 1.0,
    seasonalModifiers: {
      Spring: 1.0,
      Summer: 1.5,
      Autumn: 1.0,
      Winter: 0.8,
    },
  },
  'ancient_battlefield': {
    id: 'ancient_battlefield',
    name: '古战场',
    availableActions: [
      'search_battlefield',
      'commune_with_remnants',
    ],
    eventWeights: {
      'ancient_battlefield_remnant': 1.4,
      'ancient_battlefield_treasure': 1.3,
    },
    qiDensity: 3.0,
    danger: 4,
    priceModifier: 1.2,
  },
  'void_rift': {
    id: 'void_rift',
    name: '虚空裂隙',
    availableActions: [
      'explore_void',
      'gather_void_essence',
    ],
    eventWeights: {
      'void_rift_anomaly': 1.4,
      'void_rift_spatial_treasure': 1.3,
    },
    qiDensity: 6.0,
    danger: 5,
    priceModifier: 1.5,
  },
  'celestial_pavilion': {
    id: 'celestial_pavilion',
    name: '天阁',
    availableActions: [
      'study_celestial_script',
      'meditate_on_dao',
    ],
    eventWeights: {
      'celestial_pavilion_revelation': 1.4,
      'celestial_pavilion_guardian': 1.3,
    },
    qiDensity: 4.5,
    danger: 0,
    priceModifier: 0.85,
  },
  'demon_seal_ground': {
    id: 'demon_seal_ground',
    name: '镇魔地',
    availableActions: [
      'patrol_seal',
      'gather_demonic_material',
    ],
    eventWeights: {
      'demon_seal_weakening': 1.4,
      'demon_seal_breach': 1.5,
    },
    qiDensity: 2.5,
    danger: 4,
    priceModifier: 1.0,
    seasonalModifiers: {
      Spring: 1.0,
      Summer: 1.0,
      Autumn: 1.0,
      Winter: 1.3,
    },
  },
  'spirit_mountain': {
    id: 'spirit_mountain',
    name: '灵山',
    availableActions: [
      'spirit_mountain_retreat',
      'comprehend_dao',
    ],
    eventWeights: {
      'spirit_mountain_enlightenment': 1.4,
      'spirit_mountain_test': 1.3,
    },
    qiDensity: 7.0,
    danger: 2,
    priceModifier: 0.80,
  },
  'tribulation_platform': {
    id: 'tribulation_platform',
    name: '渡劫台',
    availableActions: [
      'face_heavenly_tribulation',
      'stabilize_dao_foundation',
    ],
    eventWeights: {
      'tribulation_platform_thunder': 1.5,
      'tribulation_platform_breakthrough': 1.4,
    },
    qiDensity: 8.0,
    danger: 5,
    priceModifier: 2.0,
  },
  'immortal_garden': {
    id: 'immortal_garden',
    name: '仙园',
    availableActions: [
      'gather_immortal_herb',
      'meditate_garden',
    ],
    eventWeights: {
      'immortal_garden_rare_herb': 1.3,
      'immortal_garden_spirit_beast': 1.2,
    },
    qiDensity: 5.5,
    danger: 1,
    priceModifier: 1.0,
    seasonalModifiers: {
      Spring: 1.5,
      Summer: 1.2,
      Autumn: 1.0,
      Winter: 0.7,
    },
  },
};
