import { Location } from '../game/types';

export const LOCATIONS: Record<string, Location> = {
  'home': {
    id: 'home',
    name: '居处',
    availableActions: [
      'kuzuo',
      'tuna',
      'tiaoxi',
      'bianyao',
      'yinqi',
      'inspect_root',
      'attune_technique',
      'study_qi_formula',
      'study_steady_formula',
      'study_cleansing_formula',
      'brew_qi_pill',
      'brew_stabilizing_powder',
      'brew_cleansing_pill',
      'take_qi_pill',
      'take_stabilizing_powder',
      'take_cleansing_pill',
      'stabilize_bottleneck',
      'withdraw_foundation',
      'breakthrough_qi_2',
      'breakthrough_qi_3',
      'breakthrough_foundation',
      'rike_tuna',
      'short_retreat',
    ],
    eventWeights: {
      'find_jade_slip': 1.5,
      'dantoxin_in_meridians': 1.4,
      'foundation_scar_aches': 1.3,
      'winter_stillness': 1.2,
    },
    qiDensity: 1,
    danger: 0,
    priceModifier: 1.0,
  },
  'mountain_path': {
    id: 'mountain_path',
    name: '山路',
    availableActions: ['caiyao', 'xunshan'],
    eventWeights: {
      'wounded_cultivator': 1.4,
      'rain_after_sprouts': 1.3,
      'wounded_cultivator_return': 1.2,
      'wounded_cultivator_grudge': 1.3,
    },
    qiDensity: 1.2,
    danger: 2,
    priceModifier: 1.0,
  },
  'market': {
    id: 'market',
    name: '坊市',
    availableActions: ['trade', 'gossip', 'borrow_foundation_pill'],
    eventWeights: {
      'market_rumor': 1.2,
      'market_price_rise': 1.2,
      'market_foundation_debt': 1.4,
      'outer_gate_rules': 1.2,
    },
    qiDensity: 0.8,
    danger: 1,
    priceModifier: 1.0,
  },
  'outer_gate': {
    id: 'outer_gate',
    name: '外门',
    availableActions: ['sect_chore', 'sect_errand', 'sect_supply', 'listen_lesson', 'gossip', 'seek_foundation_guardian'],
    eventWeights: {
      'outer_gate_rules': 1.4,
      'outer_gate_register': 1.5,
      'outer_gate_guardian_account': 1.4,
      'market_rumor': 0.5,
    },
    qiDensity: 0.9,
    danger: 1,
    priceModifier: 1.05,
  }
};
