/**
 * 秘境定义 — 四个秘境的静态配置
 */

import { Realm } from '../game/types';

export interface SecretRealmDef {
  id: string;
  name: string;
  description: string;
  requiredRealm: Realm;
  requiredFlags?: string[];
  dangerLevel: number;       // 1-5
  qiReward: number;
  insightReward: number;
  herbReward: number;
  coinReward: number;
  rareLootChance: number;    // 0-1
  rareLootId: string;        // flag set when rare loot found
  eventChainId: string;      // associated event chain
}

export const SECRET_REALMS: Record<string, SecretRealmDef> = {
  misty_herb_valley: {
    id: 'misty_herb_valley',
    name: '雾中药谷',
    description: '山雾深处，药香不散。传闻有古修遗留的药圃，但雾中路径难辨。',
    requiredRealm: Realm.QiCondensation,
    requiredFlags: ['heard_herb_slope_hint'],
    dangerLevel: 2,
    qiReward: 0,
    insightReward: 3,
    herbReward: 8,
    coinReward: 0,
    rareLootChance: 0.20,
    rareLootId: 'rare_herb_manual',
    eventChainId: 'herb_valley_discovery',
  },
  ancient_ruins: {
    id: 'ancient_ruins',
    name: '古修遗迹',
    description: '山腹中空，石壁上有残缺阵纹。前人留下的洞府，可能仍有造化。',
    requiredRealm: Realm.FoundationEstablishment,
    requiredFlags: ['sect_rank_inner'],
    dangerLevel: 3,
    qiReward: 20,
    insightReward: 8,
    herbReward: 0,
    coinReward: 10,
    rareLootChance: 0.15,
    rareLootId: 'ancient_technique_fragment',
    eventChainId: 'ruins_guardian',
  },
  demonic_cave: {
    id: 'demonic_cave',
    name: '魔气洞窟',
    description: '地底裂隙中涌出浑浊魔气。危险，但魔气中也蕴含奇特的机缘。',
    requiredRealm: Realm.FoundationEstablishment,
    requiredFlags: [],
    dangerLevel: 4,
    qiReward: 30,
    insightReward: 0,
    herbReward: 5,
    coinReward: 15,
    rareLootChance: 0.10,
    rareLootId: 'demon_core',
    eventChainId: 'demonic_whispers',
  },
  heavenly_peak: {
    id: 'heavenly_peak',
    name: '天柱峰',
    description: '山巅直入云霄，天地灵气在此汇聚。唯有金丹以上修士方可涉足。',
    requiredRealm: Realm.GoldenCore,
    dangerLevel: 5,
    qiReward: 50,
    insightReward: 20,
    herbReward: 0,
    coinReward: 30,
    rareLootChance: 0.08,
    rareLootId: 'heavenly_tribute',
    eventChainId: 'heavenly_trial',
  },
  spirit_field_maze: {
    id: 'spirit_field_maze',
    name: '灵田迷阵',
    description: '灵田之下藏有上古阵法，阵中有阵，步步生花。',
    requiredRealm: Realm.QiCondensation,
    dangerLevel: 2,
    qiReward: 5,
    insightReward: 5,
    herbReward: 12,
    coinReward: 0,
    rareLootChance: 0.15,
    rareLootId: 'ancient_formation_manual',
    eventChainId: 'spirit_field_maze_discovery',
  },
  demonic_forest_depths: {
    id: 'demonic_forest_depths',
    name: '妖林深处',
    description: '妖兽林深处有古树成精，林中瘴气弥漫，危机与奇药并存。',
    requiredRealm: Realm.FoundationEstablishment,
    dangerLevel: 4,
    qiReward: 10,
    insightReward: 5,
    herbReward: 15,
    coinReward: 5,
    rareLootChance: 0.12,
    rareLootId: 'demonic_herb_essence',
    eventChainId: 'demonic_forest_exploration',
  },
  heavenly_wind_realm: {
    id: 'heavenly_wind_realm',
    name: '天风界',
    description: '天柱崖顶破空而入的小界，风刀霜剑，唯勇者可入。',
    requiredRealm: Realm.FoundationEstablishment,
    requiredFlags: ['visited_celestial_cliff'],
    dangerLevel: 5,
    qiReward: 40,
    insightReward: 15,
    herbReward: 0,
    coinReward: 20,
    rareLootChance: 0.10,
    rareLootId: 'wind_spirit_essence',
    eventChainId: 'heavenly_wind_trial',
  },
  underground_palace: {
    id: 'underground_palace',
    name: '地下仙府',
    description: '山腹溶洞深处发现古修仙府，阵法犹在，宝物与禁制并存。',
    requiredRealm: Realm.GoldenCore,
    dangerLevel: 5,
    qiReward: 60,
    insightReward: 25,
    herbReward: 10,
    coinReward: 40,
    rareLootChance: 0.08,
    rareLootId: 'immortal_legacy',
    eventChainId: 'underground_palace_discovery',
  },
  thunder_tribulation_realm: {
    id: 'thunder_tribulation_realm',
    name: '天雷秘境',
    description: '雷峰之上，天雷汇聚成域。雷光中蕴含天劫真意，唯有元婴修士方可承受其威。',
    requiredRealm: Realm.NascentSoul,
    dangerLevel: 5,
    qiReward: 80,
    insightReward: 30,
    herbReward: 5,
    coinReward: 50,
    rareLootChance: 0.06,
    rareLootId: 'thunder_tribulation_legacy',
    eventChainId: 'thunder_tribulation_trial',
  },
  spirit_transformation_ruins: {
    id: 'spirit_transformation_ruins',
    name: '化神遗迹',
    description: '上古化神期大能坐化之地，残留神识碎片与功法传承。化神境方有一线机缘。',
    requiredRealm: Realm.SpiritTransformation,
    dangerLevel: 5,
    qiReward: 120,
    insightReward: 50,
    herbReward: 15,
    coinReward: 80,
    rareLootChance: 0.05,
    rareLootId: 'spirit_transform_technique',
    eventChainId: 'spirit_transform_discovery',
  },
  integration_void: {
    id: 'integration_void',
    name: '合体虚空',
    description: '虚空裂隙深处的异度空间，时空法则紊乱。合体期修士方可在此稳固自身，参悟天地合一之理。',
    requiredRealm: Realm.Integration,
    dangerLevel: 5,
    qiReward: 200,
    insightReward: 80,
    herbReward: 10,
    coinReward: 150,
    rareLootChance: 0.04,
    rareLootId: 'void_integration_essence',
    eventChainId: 'void_integration_trial',
  },
  mahayana_sanctum: {
    id: 'mahayana_sanctum',
    name: '大乘圣殿',
    description: '灵山之巅的太古圣殿，大乘期前辈留下的道韵犹存。唯有大乘修士方可入内承受道压。',
    requiredRealm: Realm.Mahayana,
    dangerLevel: 5,
    qiReward: 350,
    insightReward: 120,
    herbReward: 20,
    coinReward: 200,
    rareLootChance: 0.03,
    rareLootId: 'mahayana_scripture',
    eventChainId: 'mahayana_sanctum_trial',
  },
  tribulation_heaven: {
    id: 'tribulation_heaven',
    name: '渡劫天域',
    description: '渡劫台之上的天域，天劫之力凝聚为界。渡劫期修士方可踏入，直面天道考验。',
    requiredRealm: Realm.Tribulation,
    dangerLevel: 5,
    qiReward: 500,
    insightReward: 200,
    herbReward: 30,
    coinReward: 500,
    rareLootChance: 0.02,
    rareLootId: 'ascension_key',
    eventChainId: 'tribulation_heaven_trial',
  },
  dragon_palace: {
    id: 'dragon_palace',
    name: '伏潮旧宫',
    description: '灵湖深处通往的远古遗址，潮气充沛，奇珍遍布。需得伏潮旧宫线索方可寻得入口。',
    requiredRealm: Realm.GoldenCore,
    requiredFlags: ['heard_dragon_palace_hint'],
    dangerLevel: 4,
    qiReward: 60,
    insightReward: 30,
    herbReward: 20,
    coinReward: 100,
    rareLootChance: 0.08,
    rareLootId: 'dragon_pearl',
    eventChainId: 'dragon_palace_exploration',
  },
};
