import { Action, Realm } from '../../game/types';
import { PILL_RECIPES } from '../alchemy';
import { BREAKTHROUGH_RULES } from '../breakthroughs';

export const SMALL_QI_PILL_COST = PILL_RECIPES.small_qi_pill.requiredResources;
export const STABILIZING_POWDER_COST = PILL_RECIPES.stabilizing_powder.requiredResources;
export const CLEANSING_PILL_COST = PILL_RECIPES.cleansing_pill.requiredResources;
export const MERIDIAN_CLEANSING_PILL_COST = PILL_RECIPES.meridian_cleansing_pill.requiredResources;
export const FOUNDATION_STRENGTHENING_PILL_COST = PILL_RECIPES.foundation_strengthening_pill.requiredResources;
export const SPIRIT_GATHERING_PILL_COST = PILL_RECIPES.spirit_gathering_pill.requiredResources;
export const WARM_FURNACE_PILL_COST = PILL_RECIPES.warm_furnace_pill.requiredResources;
export const NIGHT_SITTING_PILL_COST = PILL_RECIPES.night_sitting_pill.requiredResources;
export const CLOUD_GATHERING_PILL_COST = PILL_RECIPES.cloud_gathering_pill.requiredResources;
export const IRON_BODY_PILL_COST = PILL_RECIPES.iron_body_pill.requiredResources;
export const DEMON_BANE_PILL_COST = PILL_RECIPES.demon_bane_pill.requiredResources;
export const FOUNDATION_EXPLOSION_PILL_COST = PILL_RECIPES.foundation_explosion_pill.requiredResources;
export const SPIRIT_VEIN_PILL_COST = PILL_RECIPES.spirit_vein_pill.requiredResources;
export const SHADOW_ESCAPE_PILL_COST = PILL_RECIPES.shadow_escape_pill.requiredResources;
export const LONGEVITY_PILL_COST = PILL_RECIPES.longevity_pill.requiredResources;
export const FIRE_FURNACE_PILL_COST = PILL_RECIPES.fire_furnace_pill.requiredResources;
export const NINE_TURN_FOUNDATION_PILL_COST = PILL_RECIPES.nine_turn_foundation_pill.requiredResources;
export const BUDDHA_HEART_PILL_COST = PILL_RECIPES.buddha_heart_pill.requiredResources;
export const GOLDEN_CORE_FORMATION_PILL_COST = PILL_RECIPES.golden_core_formation_pill.requiredResources;
export const GOLDEN_CORE_STRENGTHENING_PILL_COST = PILL_RECIPES.golden_core_strengthening_pill.requiredResources;
export const GOLDEN_CORE_FIRE_PILL_COST = PILL_RECIPES.golden_core_fire_pill.requiredResources;
export const NASCENT_SOUL_NURTURING_PILL_COST = PILL_RECIPES.nascent_soul_nurturing_pill.requiredResources;
export const NASCENT_SOUL_SEPARATION_PILL_COST = PILL_RECIPES.nascent_soul_separation_pill.requiredResources;
export const NASCENT_SOUL_PROTECTION_PILL_COST = PILL_RECIPES.nascent_soul_protection_pill.requiredResources;
export const SPIRIT_TRANSFORM_PILL_COST = PILL_RECIPES.spirit_transform_pill.requiredResources;
export const SPIRIT_TRANSFORM_FIRE_PILL_COST = PILL_RECIPES.spirit_transform_fire_pill.requiredResources;
export const INTEGRATION_PILL_COST = PILL_RECIPES.integration_pill.requiredResources;
export const INTEGRATION_BODY_PILL_COST = PILL_RECIPES.integration_body_pill.requiredResources;
export const MAHAYANA_PILL_COST = PILL_RECIPES.mahayana_pill.requiredResources;
export const MAHAYANA_ENLIGHTENMENT_PILL_COST = PILL_RECIPES.mahayana_enlightenment_pill.requiredResources;
export const TRIBULATION_PROTECTION_PILL_COST = PILL_RECIPES.tribulation_protection_pill.requiredResources;
export const HEAVENLY_TRIBULATION_PILL_COST = PILL_RECIPES.heavenly_tribulation_pill.requiredResources;
export const TRIBULATION_SOUL_PILL_COST = PILL_RECIPES.tribulation_soul_pill.requiredResources;

export const QI_LAYER_2_COST = BREAKTHROUGH_RULES.qi_layer_2.requiredResources;
export const QI_LAYER_3_COST = BREAKTHROUGH_RULES.qi_layer_3.requiredResources;
export const QI_LAYER_4_COST = BREAKTHROUGH_RULES.qi_layer_4.requiredResources;
export const QI_LAYER_5_COST = BREAKTHROUGH_RULES.qi_layer_5.requiredResources;
export const QI_LAYER_6_COST = BREAKTHROUGH_RULES.qi_layer_6.requiredResources;
export const QI_LAYER_7_COST = BREAKTHROUGH_RULES.qi_layer_7.requiredResources;
export const QI_LAYER_8_COST = BREAKTHROUGH_RULES.qi_layer_8.requiredResources;
export const QI_LAYER_9_COST = BREAKTHROUGH_RULES.qi_layer_9.requiredResources;
export const FOUNDATION_COST = BREAKTHROUGH_RULES.foundation.requiredResources;
export const GOLDEN_CORE_COST = BREAKTHROUGH_RULES.golden_core.requiredResources;
export const NASCENT_SOUL_COST = BREAKTHROUGH_RULES.nascent_soul.requiredResources;
export const SPIRIT_TRANSFORMATION_COST = BREAKTHROUGH_RULES.spirit_transformation.requiredResources;
export const INTEGRATION_COST = BREAKTHROUGH_RULES.integration.requiredResources;
export const MAHAYANA_COST = BREAKTHROUGH_RULES.mahayana.requiredResources;
export const TRIBULATION_COST = BREAKTHROUGH_RULES.tribulation.requiredResources;

