import { Action, Realm } from '../../game/types';
import { SMALL_QI_PILL_COST, STABILIZING_POWDER_COST, CLEANSING_PILL_COST, MERIDIAN_CLEANSING_PILL_COST, FOUNDATION_STRENGTHENING_PILL_COST, SPIRIT_GATHERING_PILL_COST, WARM_FURNACE_PILL_COST, NIGHT_SITTING_PILL_COST, CLOUD_GATHERING_PILL_COST, IRON_BODY_PILL_COST, DEMON_BANE_PILL_COST, FOUNDATION_EXPLOSION_PILL_COST, SPIRIT_VEIN_PILL_COST, SHADOW_ESCAPE_PILL_COST, LONGEVITY_PILL_COST, FIRE_FURNACE_PILL_COST, NINE_TURN_FOUNDATION_PILL_COST, BUDDHA_HEART_PILL_COST, HEAVENLY_TRIBULATION_PILL_COST } from './_costs';

export const ALCHEMY_ACTIONS: Record<string, Action> = {
study_qi_formula: {
    id: 'study_qi_formula',
    actionGroup: 'alchemy',
    name: '辨小丹方',
    cost: { essence: 10, herbs: 2, insight: 2 },
    output: {},
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_small_qi_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
study_steady_formula: {
    id: 'study_steady_formula',
    actionGroup: 'alchemy',
    name: '辨稳息方',
    cost: { essence: 15, herbs: 3, insight: 3 },
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_small_qi_pill'],
      forbiddenFlags: ['known_recipe_stabilizing_powder'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
brew_qi_pill: {
    id: 'brew_qi_pill',
    actionGroup: 'alchemy',
    name: '炼小聚气丸',
    cost: SMALL_QI_PILL_COST,
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_small_qi_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
brew_stabilizing_powder: {
    id: 'brew_stabilizing_powder',
    actionGroup: 'alchemy',
    name: '炼稳息散',
    cost: STABILIZING_POWDER_COST,
    output: {},
    cooldown: 35,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_stabilizing_powder'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
study_cleansing_formula: {
    id: 'study_cleansing_formula',
    actionGroup: 'alchemy',
    name: '辨清躁方',
    cost: { essence: 20, herbs: 3, insight: 4 },
    output: {},
    cooldown: 25,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_small_qi_pill'],
      forbiddenFlags: ['known_recipe_cleansing_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
brew_cleansing_pill: {
    id: 'brew_cleansing_pill',
    actionGroup: 'alchemy',
    name: '炼清躁丸',
    cost: CLEANSING_PILL_COST,
    output: {},
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_cleansing_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
take_qi_pill: {
    id: 'take_qi_pill',
    actionGroup: 'alchemy',
    name: '服小聚气丸',
    cost: { qiPills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_qi_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
take_stabilizing_powder: {
    id: 'take_stabilizing_powder',
    actionGroup: 'alchemy',
    name: '服稳息散',
    cost: { stabilizingPowders: 1 },
    output: {},
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_stabilizing_powder'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
take_cleansing_pill: {
    id: 'take_cleansing_pill',
    actionGroup: 'alchemy',
    name: '服清躁丸',
    cost: { cleansingPills: 1 },
    output: {},
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_cleansing_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
study_meridian_cleansing_formula: {
    id: 'study_meridian_cleansing_formula',
    actionGroup: 'alchemy',
    name: '辨通脉方',
    cost: { essence: 25, herbs: 4, insight: 5 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_meridian_cleansing_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
brew_meridian_cleansing_pill: {
    id: 'brew_meridian_cleansing_pill',
    actionGroup: 'alchemy',
    name: '炼通脉丸',
    cost: MERIDIAN_CLEANSING_PILL_COST,
    output: {},
    cooldown: 50,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_meridian_cleansing_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
take_meridian_cleansing_pill: {
    id: 'take_meridian_cleansing_pill',
    actionGroup: 'alchemy',
    name: '服通脉丸',
    cost: { meridianCleansingPills: 1 },
    output: {},
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_meridian_cleansing_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
study_foundation_strengthening_formula: {
    id: 'study_foundation_strengthening_formula',
    actionGroup: 'alchemy',
    name: '辨固基方',
    cost: { essence: 20, herbs: 3, insight: 4 },
    output: {},
    cooldown: 25,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_foundation_strengthening_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
brew_foundation_strengthening_pill: {
    id: 'brew_foundation_strengthening_pill',
    actionGroup: 'alchemy',
    name: '炼固基丹',
    cost: FOUNDATION_STRENGTHENING_PILL_COST,
    output: {},
    cooldown: 45,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_foundation_strengthening_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
take_foundation_strengthening_pill: {
    id: 'take_foundation_strengthening_pill',
    actionGroup: 'alchemy',
    name: '服固基丹',
    cost: { foundationStrengtheningPills: 1 },
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_foundation_strengthening_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
study_spirit_gathering_formula: {
    id: 'study_spirit_gathering_formula',
    actionGroup: 'alchemy',
    name: '辨聚灵方',
    cost: { essence: 20, herbs: 3, insight: 4 },
    output: {},
    cooldown: 25,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_spirit_gathering_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
brew_spirit_gathering_pill: {
    id: 'brew_spirit_gathering_pill',
    actionGroup: 'alchemy',
    name: '炼聚灵丸',
    cost: SPIRIT_GATHERING_PILL_COST,
    output: {},
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_spirit_gathering_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
take_spirit_gathering_pill: {
    id: 'take_spirit_gathering_pill',
    actionGroup: 'alchemy',
    name: '服聚灵丸',
    cost: { spiritGatheringPills: 1 },
    output: {},
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_spirit_gathering_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
identify_herb: {
    id: 'identify_herb',
    actionGroup: 'exploration',
    name: '辨药性',
    cost: { essence: 5, herbs: 2 },
    output: { insight: 2 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'herb_slope',
    },
  },
protect_seedling: {
    id: 'protect_seedling',
    actionGroup: 'exploration',
    name: '护苗',
    cost: { essence: 10, herbs: 1 },
    output: {},
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'herb_slope',
      requiredFlags: ['marked_herb_patch'],
    },
  },
study_warm_furnace_formula: {
    id: 'study_warm_furnace_formula',
    actionGroup: 'alchemy',
    name: '辨暖炉方',
    cost: { essence: 20, herbs: 3, insight: 3 },
    output: {},
    cooldown: 25,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_warm_furnace_pill'],
      requiredRealm: Realm.QiCondensation,
      requiredLocation: 'home',
    },
  },
brew_warm_furnace_pill: {
    id: 'brew_warm_furnace_pill',
    actionGroup: 'alchemy',
    name: '炼暖炉丹',
    cost: WARM_FURNACE_PILL_COST,
    output: {},
    cooldown: 35,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_warm_furnace_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
take_warm_furnace_pill: {
    id: 'take_warm_furnace_pill',
    actionGroup: 'alchemy',
    name: '服暖炉丹',
    cost: { warmFurnacePills: 1 },
    output: {},
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_warm_furnace_pill'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
study_night_sitting_formula: {
    id: 'study_night_sitting_formula',
    actionGroup: 'alchemy',
    name: '辨夜坐方',
    cost: { essence: 25, herbs: 4, insight: 5 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_night_sitting_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
brew_night_sitting_pill: {
    id: 'brew_night_sitting_pill',
    actionGroup: 'alchemy',
    name: '炼夜坐丸',
    cost: NIGHT_SITTING_PILL_COST,
    output: {},
    cooldown: 45,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_night_sitting_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
take_night_sitting_pill: {
    id: 'take_night_sitting_pill',
    actionGroup: 'alchemy',
    name: '服夜坐丸',
    cost: { nightSittingPills: 1 },
    output: {},
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_night_sitting_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
plant_herb: {
    id: 'plant_herb',
    actionGroup: 'exploration',
    name: '种药',
    cost: { herbs: 1, essence: 5 },
    output: { insight: 1 },
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'spirit_field',
    },
  },
harvest_herb: {
    id: 'harvest_herb',
    actionGroup: 'exploration',
    name: '收药',
    cost: { essence: 5 },
    output: { herbs: 3 },
    cooldown: 3,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'spirit_field',
    },
  },
tend_field: {
    id: 'tend_field',
    actionGroup: 'exploration',
    name: '照料灵田',
    cost: { essence: 3 },
    output: { herbs: 1, insight: 1 },
    cooldown: 2,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'spirit_field',
    },
  },
use_furnace: {
    id: 'use_furnace',
    actionGroup: 'exploration',
    name: '借炉炼丹',
    cost: { coins: 5, essence: 10 },
    output: { insight: 2 },
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'pill_hall',
    },
  },
study_advanced_formula: {
    id: 'study_advanced_formula',
    actionGroup: 'exploration',
    name: '参悟高阶丹方',
    cost: { insight: 3, herbs: 2 },
    output: { insight: 3 },
    cooldown: 8,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_foundation_strengthening_pill'],
      requiredLocation: 'pill_hall',
      requiredRealm: Realm.FoundationEstablishment,
    },
  },
gather_demonic_herb: {
    id: 'gather_demonic_herb',
    actionGroup: 'exploration',
    name: '采集魔药',
    cost: { essence: 10 },
    output: { herbs: 4 },
    cooldown: 3,
    riskProbability: 0.2,
    conditions: {
      requiredLocation: 'demonic_forest',
    },
  },
study_cloud_gathering_formula: {
    id: 'study_cloud_gathering_formula',
    actionGroup: 'alchemy',
    name: '辨聚云方',
    cost: { essence: 25, herbs: 2, insight: 3 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_cloud_gathering_pill'],
      requiredFlags: ['known_recipe_foundation_strengthening_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
brew_cloud_gathering_pill: {
    id: 'brew_cloud_gathering_pill',
    actionGroup: 'alchemy',
    name: '炼聚云丸',
    cost: CLOUD_GATHERING_PILL_COST,
    output: {},
    cooldown: 3,
    riskProbability: 0.1,
    conditions: {
      requiredFlags: ['known_recipe_cloud_gathering_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
take_cloud_gathering_pill: {
    id: 'take_cloud_gathering_pill',
    actionGroup: 'alchemy',
    name: '服聚云丸',
    cost: { cloudGatheringPills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_cloud_gathering_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
study_iron_body_formula: {
    id: 'study_iron_body_formula',
    actionGroup: 'alchemy',
    name: '辨铁身方',
    cost: { essence: 30, herbs: 2, insight: 4 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_iron_body_pill'],
      requiredFlags: ['known_recipe_foundation_strengthening_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
brew_iron_body_pill: {
    id: 'brew_iron_body_pill',
    actionGroup: 'alchemy',
    name: '炼铁身丹',
    cost: IRON_BODY_PILL_COST,
    output: {},
    cooldown: 3,
    riskProbability: 0.1,
    conditions: {
      requiredFlags: ['known_recipe_iron_body_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
take_iron_body_pill: {
    id: 'take_iron_body_pill',
    actionGroup: 'alchemy',
    name: '服铁身丹',
    cost: { ironBodyPills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_iron_body_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
study_demon_bane_formula: {
    id: 'study_demon_bane_formula',
    actionGroup: 'alchemy',
    name: '辨驱魔方',
    cost: { essence: 35, herbs: 2, insight: 5 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_demon_bane_pill'],
      requiredFlags: ['known_recipe_meridian_cleansing_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
brew_demon_bane_pill: {
    id: 'brew_demon_bane_pill',
    actionGroup: 'alchemy',
    name: '炼驱魔丹',
    cost: DEMON_BANE_PILL_COST,
    output: {},
    cooldown: 3,
    riskProbability: 0.1,
    conditions: {
      requiredFlags: ['known_recipe_demon_bane_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
take_demon_bane_pill: {
    id: 'take_demon_bane_pill',
    actionGroup: 'alchemy',
    name: '服驱魔丹',
    cost: { demonBanePills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_demon_bane_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
study_foundation_explosion_formula: {
    id: 'study_foundation_explosion_formula',
    actionGroup: 'alchemy',
    name: '辨破基方',
    cost: { essence: 40, herbs: 2, insight: 6 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_foundation_explosion_pill'],
      requiredFlags: ['known_recipe_foundation_strengthening_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
brew_foundation_explosion_pill: {
    id: 'brew_foundation_explosion_pill',
    actionGroup: 'alchemy',
    name: '炼破基丹',
    cost: FOUNDATION_EXPLOSION_PILL_COST,
    output: {},
    cooldown: 3,
    riskProbability: 0.1,
    conditions: {
      requiredFlags: ['known_recipe_foundation_explosion_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
take_foundation_explosion_pill: {
    id: 'take_foundation_explosion_pill',
    actionGroup: 'alchemy',
    name: '服破基丹',
    cost: { foundationExplosionPills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_foundation_explosion_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
study_spirit_vein_formula: {
    id: 'study_spirit_vein_formula',
    actionGroup: 'alchemy',
    name: '辨通灵方',
    cost: { essence: 30, herbs: 2, insight: 4 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_spirit_vein_pill'],
      requiredFlags: ['known_recipe_meridian_cleansing_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
brew_spirit_vein_pill: {
    id: 'brew_spirit_vein_pill',
    actionGroup: 'alchemy',
    name: '炼通灵丸',
    cost: SPIRIT_VEIN_PILL_COST,
    output: {},
    cooldown: 3,
    riskProbability: 0.1,
    conditions: {
      requiredFlags: ['known_recipe_spirit_vein_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
take_spirit_vein_pill: {
    id: 'take_spirit_vein_pill',
    actionGroup: 'alchemy',
    name: '服通灵丸',
    cost: { spiritVeinPills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_spirit_vein_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
study_shadow_escape_formula: {
    id: 'study_shadow_escape_formula',
    actionGroup: 'alchemy',
    name: '辨影遁方',
    cost: { essence: 30, herbs: 2, insight: 4 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_shadow_escape_pill'],
      requiredFlags: ['known_recipe_spirit_gathering_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
brew_shadow_escape_pill: {
    id: 'brew_shadow_escape_pill',
    actionGroup: 'alchemy',
    name: '炼影遁丸',
    cost: SHADOW_ESCAPE_PILL_COST,
    output: {},
    cooldown: 3,
    riskProbability: 0.1,
    conditions: {
      requiredFlags: ['known_recipe_shadow_escape_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
take_shadow_escape_pill: {
    id: 'take_shadow_escape_pill',
    actionGroup: 'alchemy',
    name: '服影遁丸',
    cost: { shadowEscapePills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_shadow_escape_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
study_longevity_formula: {
    id: 'study_longevity_formula',
    actionGroup: 'alchemy',
    name: '辨延寿方',
    cost: { essence: 50, herbs: 2, insight: 8 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_longevity_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
brew_longevity_pill: {
    id: 'brew_longevity_pill',
    actionGroup: 'alchemy',
    name: '炼延寿丹',
    cost: LONGEVITY_PILL_COST,
    output: {},
    cooldown: 3,
    riskProbability: 0.1,
    conditions: {
      requiredFlags: ['known_recipe_longevity_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
take_longevity_pill: {
    id: 'take_longevity_pill',
    actionGroup: 'alchemy',
    name: '服延寿丹',
    cost: { longevityPills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_longevity_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
study_fire_furnace_formula: {
    id: 'study_fire_furnace_formula',
    actionGroup: 'alchemy',
    name: '辨火炉方',
    cost: { essence: 30, herbs: 2, insight: 3 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_fire_furnace_pill'],
      requiredFlags: ['known_recipe_warm_furnace_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
brew_fire_furnace_pill: {
    id: 'brew_fire_furnace_pill',
    actionGroup: 'alchemy',
    name: '炼火炉丹',
    cost: FIRE_FURNACE_PILL_COST,
    output: {},
    cooldown: 3,
    riskProbability: 0.1,
    conditions: {
      requiredFlags: ['known_recipe_fire_furnace_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
take_fire_furnace_pill: {
    id: 'take_fire_furnace_pill',
    actionGroup: 'alchemy',
    name: '服火炉丹',
    cost: { fireFurnacePills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_fire_furnace_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
study_nine_turn_foundation_formula: {
    id: 'study_nine_turn_foundation_formula',
    actionGroup: 'alchemy',
    name: '辨重炉筑基方',
    cost: { essence: 60, herbs: 2, insight: 10 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_nine_turn_foundation_pill'],
      requiredFlags: ['known_recipe_foundation_strengthening_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
brew_nine_turn_foundation_pill: {
    id: 'brew_nine_turn_foundation_pill',
    actionGroup: 'alchemy',
    name: '炼重炉筑基丹',
    cost: NINE_TURN_FOUNDATION_PILL_COST,
    output: {},
    cooldown: 3,
    riskProbability: 0.1,
    conditions: {
      requiredFlags: ['known_recipe_nine_turn_foundation_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
take_nine_turn_foundation_pill: {
    id: 'take_nine_turn_foundation_pill',
    actionGroup: 'alchemy',
    name: '服重炉筑基丹',
    cost: { nineTurnFoundationPills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_nine_turn_foundation_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
study_buddha_heart_formula: {
    id: 'study_buddha_heart_formula',
    actionGroup: 'alchemy',
    name: '辨定神方',
    cost: { essence: 35, herbs: 2, insight: 5 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_buddha_heart_pill'],
      requiredFlags: ['known_recipe_cleansing_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
brew_buddha_heart_pill: {
    id: 'brew_buddha_heart_pill',
    actionGroup: 'alchemy',
    name: '炼定神丸',
    cost: BUDDHA_HEART_PILL_COST,
    output: {},
    cooldown: 3,
    riskProbability: 0.1,
    conditions: {
      requiredFlags: ['known_recipe_buddha_heart_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
take_buddha_heart_pill: {
    id: 'take_buddha_heart_pill',
    actionGroup: 'alchemy',
    name: '服定神丸',
    cost: { buddhaHeartPills: 1 },
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_buddha_heart_pill'],
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'home',
    },
  },
gather_void_essence: {
    id: 'gather_void_essence',
    actionGroup: 'exploration',
    name: '采集虚灵',
    cost: { essence: 40, qi: 20 },
    output: { qi: 25, herbs: 8 },
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.Integration,
      requiredLocation: 'void_rift',
    },
  },
gather_demonic_material: {
    id: 'gather_demonic_material',
    actionGroup: 'exploration',
    name: '采集魔材',
    cost: { essence: 20 },
    output: { herbs: 6 },
    cooldown: 10,
    riskProbability: 0.15,
    conditions: {
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'demon_seal_ground',
    },
  },
gather_immortal_herb: {
    id: 'gather_immortal_herb',
    actionGroup: 'exploration',
    name: '采仙草',
    cost: { essence: 20 },
    output: { herbs: 8, insight: 1 },
    cooldown: 8,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'immortal_garden',
    },
  },
meditate_garden: {
    id: 'meditate_garden',
    actionGroup: 'cultivation',
    name: '仙园悟道',
    cost: { essence: 30, qi: 10 },
    output: { qi: 15, insight: 5 },
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'immortal_garden',
    },
  },
study_heavenly_tribulation_formula: {
    id: 'study_heavenly_tribulation_formula',
    actionGroup: 'alchemy',
    name: '辨天劫丹方',
    cost: { essence: 100, herbs: 25, insight: 30 },
    output: {},
    cooldown: 80,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_heavenly_tribulation_pill'],
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'home',
    },
  },
brew_heavenly_tribulation_pill: {
    id: 'brew_heavenly_tribulation_pill',
    actionGroup: 'alchemy',
    name: '炼天劫丹',
    cost: HEAVENLY_TRIBULATION_PILL_COST,
    output: {},
    cooldown: 120,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_heavenly_tribulation_pill'],
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'home',
    },
  },
take_heavenly_tribulation_pill: {
    id: 'take_heavenly_tribulation_pill',
    actionGroup: 'alchemy',
    name: '服天劫丹',
    cost: { heavenlyTribulationPills: 1 },
    output: {},
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_heavenly_tribulation_pill'],
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'home',
    },
  }
};
