import { Action, Realm } from '../../game/types';
// NOTE: QI_LAYER_*_COST and FOUNDATION_COST removed — breakthrough costs are now
// defined inline to separate actual cost (essence spend) from minResources (gate).

export const BREAKTHROUGH_ACTIONS: Record<string, Action> = {
yinqi: {
    id: 'yinqi',
    actionGroup: 'cultivation',
    name: '引气入体',
    cost: { qi: 15, insight: 3, essence: 30 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['unlocked_rike_tuna'],
      requiredRealm: Realm.Mortal,
    },
    isGlobalAction: true, // Breakthrough — internal cultivation event, not location-bound
  },
withdraw_foundation: {
    id: 'withdraw_foundation',
    actionGroup: 'breakthrough',
    name: '筑基收功',
    cost: { essence: 25, qi: 6 },
    output: {},
    cooldown: 80,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_foundation'],
      forbiddenFlags: ['reached_foundation'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
  },
stabilize_bottleneck: {
    id: 'stabilize_bottleneck',
    actionGroup: 'basic',
    name: '稳固关口',
    cost: { essence: 35, qi: 3, insight: 1 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
    },
    isGlobalAction: true, // Internal cultivation state — not location-dependent
  },
breakthrough_qi_2: {
    id: 'breakthrough_qi_2',
    actionGroup: 'breakthrough',
    name: '冲炼气二层',
    cost: { essence: 30, qi: 30, insight: 3 },
    output: {},
    cooldown: 60,
    riskProbability: 0,
    conditions: {
      minResources: { qi: 30, insight: 3 },
      requiredFlags: ['prepared_qi_layer_2'],
      forbiddenFlags: ['reached_qi_layer_2'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
    isGlobalAction: true,
  },
breakthrough_qi_3: {
    id: 'breakthrough_qi_3',
    actionGroup: 'breakthrough',
    name: '冲炼气三层',
    cost: { essence: 35, qi: 45, insight: 5 },
    output: {},
    cooldown: 70,
    riskProbability: 0,
    conditions: {
      minResources: { qi: 45, insight: 5 },
      requiredFlags: ['prepared_qi_layer_3'],
      forbiddenFlags: ['reached_qi_layer_3'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
    isGlobalAction: true,
  },
breakthrough_qi_4: {
    id: 'breakthrough_qi_4',
    actionGroup: 'breakthrough',
    name: '冲炼气四层',
    cost: { essence: 40, qi: 60, insight: 8 },
    output: {},
    cooldown: 80,
    riskProbability: 0,
    conditions: {
      minResources: { qi: 60, insight: 8 },
      requiredFlags: ['prepared_qi_layer_4'],
      forbiddenFlags: ['reached_qi_layer_4'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
    isGlobalAction: true,
  },
breakthrough_qi_5: {
    id: 'breakthrough_qi_5',
    actionGroup: 'breakthrough',
    name: '冲炼气五层',
    cost: { essence: 45, qi: 75, insight: 10 },
    output: {},
    cooldown: 90,
    riskProbability: 0,
    conditions: {
      minResources: { qi: 75, insight: 10 },
      requiredFlags: ['prepared_qi_layer_5'],
      forbiddenFlags: ['reached_qi_layer_5'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
    isGlobalAction: true,
  },
breakthrough_qi_6: {
    id: 'breakthrough_qi_6',
    actionGroup: 'breakthrough',
    name: '冲炼气六层',
    cost: { essence: 50, qi: 90, insight: 12 },
    output: {},
    cooldown: 100,
    riskProbability: 0,
    conditions: {
      minResources: { qi: 90, insight: 12 },
      requiredFlags: ['prepared_qi_layer_6'],
      forbiddenFlags: ['reached_qi_layer_6'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
    isGlobalAction: true,
  },
breakthrough_qi_7: {
    id: 'breakthrough_qi_7',
    actionGroup: 'breakthrough',
    name: '冲炼气七层',
    cost: { essence: 50, qi: 110, insight: 15 },
    output: {},
    cooldown: 110,
    riskProbability: 0,
    conditions: {
      minResources: { qi: 110, insight: 15 },
      requiredFlags: ['prepared_qi_layer_7'],
      forbiddenFlags: ['reached_qi_layer_7'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
    isGlobalAction: true,
  },
breakthrough_qi_8: {
    id: 'breakthrough_qi_8',
    actionGroup: 'breakthrough',
    name: '冲炼气八层',
    cost: { essence: 55, qi: 130, insight: 18 },
    output: {},
    cooldown: 120,
    riskProbability: 0,
    conditions: {
      minResources: { qi: 130, insight: 18 },
      requiredFlags: ['prepared_qi_layer_8'],
      forbiddenFlags: ['reached_qi_layer_8'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
    isGlobalAction: true,
  },
breakthrough_qi_9: {
    id: 'breakthrough_qi_9',
    actionGroup: 'breakthrough',
    name: '冲炼气九层',
    cost: { essence: 60, qi: 150, insight: 22 },
    output: {},
    cooldown: 130,
    riskProbability: 0,
    conditions: {
      minResources: { qi: 150, insight: 22 },
      requiredFlags: ['prepared_qi_layer_9'],
      forbiddenFlags: ['reached_qi_layer_9'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
    isGlobalAction: true,
  },
breakthrough_foundation: {
    id: 'breakthrough_foundation',
    actionGroup: 'breakthrough',
    name: '冲筑基',
    cost: { essence: 80, qi: 160, insight: 25 },
    output: {},
    cooldown: 120,
    riskProbability: 0,
    conditions: {
      minResources: { qi: 160, insight: 25 },
      requiredFlags: ['prepared_foundation'],
      forbiddenFlags: ['reached_foundation'],
      requiredLocation: 'home',
      requiredRealm: Realm.QiCondensation,
    },
    isGlobalAction: true,
  },
attempt_ascension: {
    id: 'attempt_ascension',
    actionGroup: 'breakthrough',
    name: '尝试飞升',
    cost: { qi: 200 },
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.NascentSoul,
    },
    isGlobalAction: true,
  }
};
