import { Action, Realm } from '../../game/types';

export const COMBAT_ACTIONS: Record<string, Action> = {
practice_sword: {
    id: 'practice_sword',
    actionGroup: 'exploration',
    name: '练剑',
    cost: { essence: 10, qi: 5 },
    output: { insight: 2 },
    cooldown: 3,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'sword_pavilion',
    },
  },
observe_sword_intent: {
    id: 'observe_sword_intent',
    actionGroup: 'exploration',
    name: '观摩剑意',
    cost: { insight: 5 },
    output: { insight: 4 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'sword_pavilion',
      requiredRealm: Realm.FoundationEstablishment,
    },
  },
search_altar: {
    id: 'search_altar',
    actionGroup: 'exploration',
    name: '探查祭坛',
    cost: { essence: 15 },
    output: { insight: 3 },
    cooldown: 8,
    riskProbability: 0.2,
    conditions: {
      requiredLocation: 'deep_temple',
      requiredRealm: Realm.FoundationEstablishment,
    },
  },
meditate_dark: {
    id: 'meditate_dark',
    actionGroup: 'exploration',
    name: '冥思暗堂',
    cost: { essence: 10, qi: 5 },
    output: { insight: 4, qi: 3 },
    cooldown: 5,
    riskProbability: 0.15,
    conditions: {
      requiredLocation: 'deep_temple',
      requiredRealm: Realm.FoundationEstablishment,
    },
  },
explore_depths: {
    id: 'explore_depths',
    actionGroup: 'exploration',
    name: '深入探索',
    cost: { essence: 20, qi: 10 },
    output: { insight: 5, coins: 3 },
    cooldown: 6,
    riskProbability: 0.25,
    conditions: {
      requiredLocation: 'mountain_cave',
      requiredRealm: Realm.FoundationEstablishment,
    },
  },
hunt_beast: {
    id: 'hunt_beast',
    actionGroup: 'exploration',
    name: '猎杀妖兽',
    cost: { essence: 20, qi: 10 },
    output: { coins: 8, herbs: 3 },
    cooldown: 4,
    riskProbability: 0.3,
    conditions: {
      requiredLocation: 'demonic_forest',
      requiredRealm: Realm.FoundationEstablishment,
    },
  },
set_trap: {
    id: 'set_trap',
    actionGroup: 'exploration',
    name: '设置陷阱',
    cost: { coins: 3, essence: 5 },
    output: { coins: 5, herbs: 2 },
    cooldown: 5,
    riskProbability: 0.15,
    conditions: {
      requiredLocation: 'demonic_forest',
    },
  },
face_heavenly_wind: {
    id: 'face_heavenly_wind',
    actionGroup: 'exploration',
    name: '迎天风',
    cost: { qi: 15, essence: 20 },
    output: { qi: 12, insight: 5 },
    cooldown: 8,
    riskProbability: 0.2,
    conditions: {
      requiredLocation: 'celestial_cliff',
      requiredRealm: Realm.FoundationEstablishment,
    },
  },
dive_for_treasure: {
    id: 'dive_for_treasure',
    actionGroup: 'exploration',
    name: '潜湖寻宝',
    cost: { essence: 30, qi: 10 },
    output: { coins: 10, herbs: 5 },
    cooldown: 30,
    riskProbability: 0.2,
    conditions: {
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'spirit_lake',
    },
  },
face_tribulation: {
    id: 'face_tribulation',
    actionGroup: 'exploration',
    name: '引雷淬体',
    cost: { essence: 50, qi: 20 },
    output: { qi: 30, insight: 8 },
    cooldown: 40,
    riskProbability: 0.3,
    conditions: {
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'thunder_peak',
    },
  },
search_battlefield: {
    id: 'search_battlefield',
    actionGroup: 'exploration',
    name: '搜索战场遗迹',
    cost: { essence: 40, qi: 15 },
    output: { coins: 15, herbs: 5, insight: 3 },
    cooldown: 20,
    riskProbability: 0.25,
    conditions: {
      requiredRealm: Realm.SpiritTransformation,
      requiredLocation: 'ancient_battlefield',
    },
  },
commune_with_remnants: {
    id: 'commune_with_remnants',
    actionGroup: 'cultivation',
    name: '感应残灵',
    cost: { essence: 30, qi: 20, insight: 5 },
    output: { insight: 10, qi: 10 },
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.SpiritTransformation,
      requiredLocation: 'ancient_battlefield',
    },
  },
explore_void: {
    id: 'explore_void',
    actionGroup: 'exploration',
    name: '探查虚空',
    cost: { essence: 60, qi: 30 },
    output: { qi: 40, insight: 15 },
    cooldown: 50,
    riskProbability: 0.35,
    conditions: {
      requiredRealm: Realm.Integration,
      requiredLocation: 'void_rift',
    },
  },
face_heavenly_tribulation: {
    id: 'face_heavenly_tribulation',
    actionGroup: 'exploration',
    name: '迎天劫',
    cost: { essence: 100, qi: 50 },
    output: { qi: 80, insight: 30 },
    cooldown: 100,
    riskProbability: 0.4,
    conditions: {
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'tribulation_platform',
    },
  },
confront_demon: {
    id: 'confront_demon',
    actionGroup: 'combat',
    name: '直面心魔',
    cost: { essence: 20, qi: 5 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'home',
    },
    isGlobalAction: true, // Inner demon — internal mental state, not location-bound
  },
suppress_demon: {
    id: 'suppress_demon',
    actionGroup: 'combat',
    name: '压制心魔',
    cost: { essence: 10 },
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'home',
    },
    isGlobalAction: true, // Inner demon — internal mental state, not location-bound
  },
ignore_demon: {
    id: 'ignore_demon',
    actionGroup: 'combat',
    name: '无视心魔',
    cost: {},
    output: {},
    cooldown: 5,
    riskProbability: 0,
    conditions: {},
    isGlobalAction: true, // Inner demon — internal mental state, not location-bound
  }
};
