import { Action, Realm } from '../../game/types';

export const EXPLORATION_ACTIONS: Record<string, Action> = {
caiyao: {
    id: 'caiyao',
    actionGroup: 'exploration',
    name: '采药',
    cost: { essence: 20 },
    output: { herbs: 1 },
    cooldown: 10,
    riskProbability: 0.1,
    conditions: {},
  },
bianyao: {
    id: 'bianyao',
    actionGroup: 'exploration',
    name: '辨药',
    cost: { essence: 5, herbs: 1 },
    output: { insight: 1 },
    cooldown: 5,
    riskProbability: 0,
    conditions: {},
  },
xunshan: {
    id: 'xunshan',
    actionGroup: 'exploration',
    name: '巡山',
    cost: { essence: 30 },
    output: { insight: 1, herbs: 2 },
    cooldown: 20,
    riskProbability: 0.3,
    conditions: {},
  },
trade: {
    id: 'trade',
    actionGroup: 'exploration',
    name: '小买卖',
    cost: { essence: 10 },
    output: { coins: 2 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'market',
    },
  },
gossip: {
    id: 'gossip',
    actionGroup: 'exploration',
    name: '听闻',
    cost: { essence: 10 },
    output: { insight: 1 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'market',
    },
  },
borrow_foundation_pill: {
    id: 'borrow_foundation_pill',
    actionGroup: 'exploration',
    name: '借丹筑基',
    cost: { coins: 12, insight: 3 },
    output: { dantoxin: 12 },
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['bottleneck_foundation'],
      forbiddenFlags: ['borrowed_foundation_aid', 'foundation_pill_debt_open'],
      requiredLocation: 'market',
      requiredRealm: Realm.QiCondensation,
    },
  },
open_market_stall: {
    id: 'open_market_stall',
    actionGroup: 'exploration',
    name: '开摊',
    cost: { coins: 10, herbs: 5 },
    output: { coins: 8, insight: 1 },
    cooldown: 80,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'market',
    },
  },
buy_rare_herbs: {
    id: 'buy_rare_herbs',
    actionGroup: 'exploration',
    name: '买珍药',
    cost: { coins: 15 },
    output: { herbs: 5 },
    cooldown: 60,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'market',
    },
  },
explore_secret_realm: {
    id: 'explore_secret_realm',
    actionGroup: 'exploration',
    name: '探索秘境',
    cost: { essence: 50 },
    output: {},
    cooldown: 200,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'home',
      requiredFlags: ['has_discovered_realm'],
    },
  },
continue_exploration: {
    id: 'continue_exploration',
    actionGroup: 'exploration',
    name: '深入探索',
    cost: { essence: 30, qi: 5 },
    output: {},
    cooldown: 50,
    riskProbability: 0.15,
    conditions: {
      requiredFlags: ['exploring_secret_realm'],
    },
  },
claim_exploration_loot: {
    id: 'claim_exploration_loot',
    actionGroup: 'exploration',
    name: '收取探索成果',
    cost: {},
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['exploration_complete'],
    },
  },
abandon_exploration: {
    id: 'abandon_exploration',
    actionGroup: 'exploration',
    name: '放弃探索',
    cost: {},
    output: {},
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['exploring_secret_realm'],
    },
  },
meditate_detox: {
    id: 'meditate_detox',
    actionGroup: 'basic',
    name: '静坐逼毒',
    cost: { essence: 40 },
    output: { dantoxin: -3 },
    cooldown: 0,
    riskProbability: 0,
    conditions: {
      minResources: { dantoxin: 10, essence: 40 },
      requiredFlags: ['entered_qi_condensation'],
      forbiddenFlags: [],
    },
    isGlobalAction: true, // Detox — internal body process, not location-bound
  },
water_meditation: {
    id: 'water_meditation',
    actionGroup: 'cultivation',
    name: '溪边静坐',
    cost: { essence: 15 },
    output: { qi: 2, insight: 1 },
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'stream_valley',
    },
  },
collect_night_dew: {
    id: 'collect_night_dew',
    actionGroup: 'exploration',
    name: '收夜露',
    cost: { essence: 10 },
    output: { herbs: 2 },
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'stream_valley',
    },
  },
explore_ruins: {
    id: 'explore_ruins',
    actionGroup: 'exploration',
    name: '探查废观',
    cost: { essence: 20 },
    output: { insight: 2 },
    cooldown: 25,
    riskProbability: 0.1,
    conditions: {
      requiredLocation: 'abandoned_temple',
    },
  },
sweep_temple: {
    id: 'sweep_temple',
    actionGroup: 'exploration',
    name: '清扫殿宇',
    cost: { essence: 10 },
    output: { insight: 1 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'abandoned_temple',
    },
  },
read_stone_tablet: {
    id: 'read_stone_tablet',
    actionGroup: 'exploration',
    name: '读石碑',
    cost: { essence: 15, insight: 2 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'abandoned_temple',
      requiredFlags: ['found_jade_slip'],
    },
  },
listen_traveler: {
    id: 'listen_traveler',
    actionGroup: 'exploration',
    name: '听客谈',
    cost: { essence: 10 },
    output: { insight: 2 },
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'ferry_crossing',
    },
  },
hire_boat: {
    id: 'hire_boat',
    actionGroup: 'exploration',
    name: '雇船出行',
    cost: { coins: 5, essence: 20 },
    output: { insight: 3 },
    cooldown: 40,
    riskProbability: 0.1,
    conditions: {
      requiredLocation: 'ferry_crossing',
    },
  },
mine_crystal: {
    id: 'mine_crystal',
    actionGroup: 'exploration',
    name: '采集灵晶',
    cost: { essence: 15 },
    output: { coins: 5, herbs: 2 },
    cooldown: 4,
    riskProbability: 0.1,
    conditions: {
      requiredLocation: 'mountain_cave',
    },
  },
drink_tea: {
    id: 'drink_tea',
    actionGroup: 'exploration',
    name: '饮茶',
    cost: { coins: 2 },
    output: { insight: 1, essence: 3 },
    cooldown: 2,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'tea_house',
    },
  },
listen_rumor: {
    id: 'listen_rumor',
    actionGroup: 'exploration',
    name: '听传闻',
    cost: {},
    output: { insight: 1 },
    cooldown: 3,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'tea_house',
    },
  },
gamble_dice: {
    id: 'gamble_dice',
    actionGroup: 'exploration',
    name: '掷骰赌钱',
    cost: { coins: 3 },
    output: { coins: 5 },
    cooldown: 5,
    riskProbability: 0.5,
    conditions: {
      requiredLocation: 'tea_house',
    },
  },
cliff_meditation: {
    id: 'cliff_meditation',
    actionGroup: 'cultivation',
    name: '悬崖静坐',
    cost: { essence: 15, qi: 10 },
    output: { qi: 8, insight: 3 },
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'celestial_cliff',
      requiredRealm: Realm.FoundationEstablishment,
    },
  },
seek_elder_guidance: {
    id: 'seek_elder_guidance',
    actionGroup: 'sect',
    name: '求教长老',
    cost: { essence: 25, coins: 10 },
    output: { insight: 5, qi: 5 },
    cooldown: 60,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'core_gate',
      requiredFlags: ['sect_rank_core'],
    },
  },
study_celestial_script: {
    id: 'study_celestial_script',
    actionGroup: 'exploration',
    name: '参悟天书',
    cost: { essence: 30, insight: 5 },
    output: { insight: 8, qi: 10 },
    cooldown: 25,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'celestial_pavilion',
    },
  },
meditate_on_dao: {
    id: 'meditate_on_dao',
    actionGroup: 'cultivation',
    name: '悟道',
    cost: { essence: 50, qi: 25 },
    output: { qi: 20, insight: 12 },
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'celestial_pavilion',
    },
  },
comprehend_dao: {
    id: 'comprehend_dao',
    actionGroup: 'cultivation',
    name: '参道',
    cost: { essence: 60, qi: 30, insight: 10 },
    output: { qi: 30, insight: 25 },
    cooldown: 50,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.Mahayana,
      requiredLocation: 'spirit_mountain',
    },
  },
stabilize_dao_foundation: {
    id: 'stabilize_dao_foundation',
    actionGroup: 'exploration',
    name: '稳固道基',
    cost: { essence: 60, qi: 30 },
    output: { qi: 20 },
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'tribulation_platform',
    },
  }
};
