import { Action, Realm } from '../../game/types';
import { GOLDEN_CORE_FORMATION_PILL_COST, GOLDEN_CORE_STRENGTHENING_PILL_COST, GOLDEN_CORE_FIRE_PILL_COST, NASCENT_SOUL_NURTURING_PILL_COST, NASCENT_SOUL_SEPARATION_PILL_COST, NASCENT_SOUL_PROTECTION_PILL_COST, SPIRIT_TRANSFORM_PILL_COST, SPIRIT_TRANSFORM_FIRE_PILL_COST, INTEGRATION_PILL_COST, INTEGRATION_BODY_PILL_COST, MAHAYANA_PILL_COST, MAHAYANA_ENLIGHTENMENT_PILL_COST, TRIBULATION_PROTECTION_PILL_COST, TRIBULATION_SOUL_PILL_COST, GOLDEN_CORE_COST, NASCENT_SOUL_COST, SPIRIT_TRANSFORMATION_COST, INTEGRATION_COST, MAHAYANA_COST, TRIBULATION_COST } from './_costs';

export const HIGHREALM_ACTIONS: Record<string, Action> = {
golden_core_practice: {
    id: 'golden_core_practice',
    actionGroup: 'cultivation',
    name: '金丹日课',
    cost: { essence: 30 },
    output: { qi: 10, insight: 2 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.GoldenCore,
    },
  },
nascent_soul_practice: {
    id: 'nascent_soul_practice',
    actionGroup: 'cultivation',
    name: '元婴日课',
    cost: { essence: 40 },
    output: { qi: 15, insight: 3 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.NascentSoul,
    },
  },
breakthrough_golden_core: {
    id: 'breakthrough_golden_core',
    actionGroup: 'breakthrough',
    name: '冲金丹',
    cost: GOLDEN_CORE_COST,
    output: {},
    cooldown: 200,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_golden_core'],
      forbiddenFlags: ['reached_golden_core'],
      requiredLocation: 'home',
      requiredRealm: Realm.FoundationEstablishment,
    },
    isGlobalAction: true, // Breakthrough — internal cultivation event, not location-bound
  },
breakthrough_nascent_soul: {
    id: 'breakthrough_nascent_soul',
    actionGroup: 'breakthrough',
    name: '冲元婴',
    cost: NASCENT_SOUL_COST,
    output: {},
    cooldown: 300,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_nascent_soul'],
      forbiddenFlags: ['reached_nascent_soul'],
      requiredLocation: 'home',
      requiredRealm: Realm.GoldenCore,
    },
    isGlobalAction: true, // Breakthrough — internal cultivation event, not location-bound
  },
spirit_transformation_practice: {
    id: 'spirit_transformation_practice',
    actionGroup: 'cultivation',
    name: '化神日课',
    cost: { essence: 50 },
    output: { qi: 20, insight: 4 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.SpiritTransformation,
    },
  },
integration_practice: {
    id: 'integration_practice',
    actionGroup: 'cultivation',
    name: '合体日课',
    cost: { essence: 60 },
    output: { qi: 25, insight: 5 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.Integration,
    },
  },
mahayana_practice: {
    id: 'mahayana_practice',
    actionGroup: 'cultivation',
    name: '大乘日课',
    cost: { essence: 70 },
    output: { qi: 30, insight: 6 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.Mahayana,
    },
  },
tribulation_practice: {
    id: 'tribulation_practice',
    actionGroup: 'cultivation',
    name: '渡劫日课',
    cost: { essence: 80 },
    output: { qi: 40, insight: 8 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.Tribulation,
    },
  },
breakthrough_spirit_transformation: {
    id: 'breakthrough_spirit_transformation',
    actionGroup: 'breakthrough',
    name: '冲化神',
    cost: SPIRIT_TRANSFORMATION_COST,
    output: {},
    cooldown: 400,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_spirit_transformation'],
      forbiddenFlags: ['reached_spirit_transformation'],
      requiredLocation: 'home',
      requiredRealm: Realm.NascentSoul,
    },
    isGlobalAction: true, // Breakthrough — internal cultivation event, not location-bound
  },
breakthrough_integration: {
    id: 'breakthrough_integration',
    actionGroup: 'breakthrough',
    name: '冲合体',
    cost: INTEGRATION_COST,
    output: {},
    cooldown: 500,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_integration'],
      forbiddenFlags: ['reached_integration'],
      requiredLocation: 'home',
      requiredRealm: Realm.SpiritTransformation,
    },
    isGlobalAction: true, // Breakthrough — internal cultivation event, not location-bound
  },
breakthrough_mahayana: {
    id: 'breakthrough_mahayana',
    actionGroup: 'breakthrough',
    name: '冲大乘',
    cost: MAHAYANA_COST,
    output: {},
    cooldown: 600,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_mahayana'],
      forbiddenFlags: ['reached_mahayana'],
      requiredLocation: 'home',
      requiredRealm: Realm.Integration,
    },
    isGlobalAction: true, // Breakthrough — internal cultivation event, not location-bound
  },
breakthrough_tribulation: {
    id: 'breakthrough_tribulation',
    actionGroup: 'breakthrough',
    name: '冲渡劫',
    cost: TRIBULATION_COST,
    output: {},
    cooldown: 800,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['prepared_tribulation'],
      forbiddenFlags: ['reached_tribulation'],
      requiredLocation: 'home',
      requiredRealm: Realm.Mahayana,
    },
    isGlobalAction: true, // Breakthrough — internal cultivation event, not location-bound
  },
core_gate_cultivation: {
    id: 'core_gate_cultivation',
    actionGroup: 'cultivation',
    name: '核心峰修炼',
    cost: { essence: 30, qi: 5 },
    output: { qi: 15, insight: 3 },
    cooldown: 10,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'core_gate',
    },
  },
core_gate_exchange: {
    id: 'core_gate_exchange',
    actionGroup: 'sect',
    name: '核心峰兑换',
    cost: { coins: 20 },
    output: { herbs: 8, insight: 2 },
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'core_gate',
    },
  },
spirit_lake_meditation: {
    id: 'spirit_lake_meditation',
    actionGroup: 'cultivation',
    name: '灵湖静修',
    cost: { essence: 20 },
    output: { qi: 8, insight: 2 },
    cooldown: 12,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'spirit_lake',
    },
  },
spirit_mountain_retreat: {
    id: 'spirit_mountain_retreat',
    actionGroup: 'exploration',
    name: '灵山闭关',
    cost: { essence: 80, qi: 40 },
    output: { qi: 60, insight: 20 },
    cooldown: 60,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.Mahayana,
      requiredLocation: 'spirit_mountain',
    },
  },
study_golden_core_formation_formula: {
    id: 'study_golden_core_formation_formula',
    actionGroup: 'alchemy',
    name: '辨凝丹方',
    cost: { essence: 30, herbs: 5, insight: 6 },
    output: {},
    cooldown: 35,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_golden_core_formation_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
brew_golden_core_formation_pill: {
    id: 'brew_golden_core_formation_pill',
    actionGroup: 'alchemy',
    name: '炼凝丹丸',
    cost: GOLDEN_CORE_FORMATION_PILL_COST,
    output: {},
    cooldown: 50,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_golden_core_formation_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
take_golden_core_formation_pill: {
    id: 'take_golden_core_formation_pill',
    actionGroup: 'alchemy',
    name: '服凝丹丸',
    cost: { goldenCorePills: 1 },
    output: {},
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_golden_core_formation_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
study_golden_core_strengthening_formula: {
    id: 'study_golden_core_strengthening_formula',
    actionGroup: 'alchemy',
    name: '辨固丹方',
    cost: { essence: 30, herbs: 5, insight: 6 },
    output: {},
    cooldown: 35,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_golden_core_strengthening_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
brew_golden_core_strengthening_pill: {
    id: 'brew_golden_core_strengthening_pill',
    actionGroup: 'alchemy',
    name: '炼固丹丸',
    cost: GOLDEN_CORE_STRENGTHENING_PILL_COST,
    output: {},
    cooldown: 50,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_golden_core_strengthening_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
take_golden_core_strengthening_pill: {
    id: 'take_golden_core_strengthening_pill',
    actionGroup: 'alchemy',
    name: '服固丹丸',
    cost: { goldenCorePills: 1 },
    output: {},
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_golden_core_strengthening_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
study_golden_core_fire_formula: {
    id: 'study_golden_core_fire_formula',
    actionGroup: 'alchemy',
    name: '辨烈丹方',
    cost: { essence: 35, herbs: 6, insight: 7 },
    output: {},
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_golden_core_fire_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
brew_golden_core_fire_pill: {
    id: 'brew_golden_core_fire_pill',
    actionGroup: 'alchemy',
    name: '炼烈丹丸',
    cost: GOLDEN_CORE_FIRE_PILL_COST,
    output: {},
    cooldown: 55,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_golden_core_fire_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
take_golden_core_fire_pill: {
    id: 'take_golden_core_fire_pill',
    actionGroup: 'alchemy',
    name: '服烈丹丸',
    cost: { goldenCorePills: 1 },
    output: {},
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_golden_core_fire_pill'],
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'home',
    },
  },
study_nascent_soul_nurturing_formula: {
    id: 'study_nascent_soul_nurturing_formula',
    actionGroup: 'alchemy',
    name: '辨培婴方',
    cost: { essence: 40, herbs: 7, insight: 8 },
    output: {},
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_nascent_soul_nurturing_pill'],
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'home',
    },
  },
brew_nascent_soul_nurturing_pill: {
    id: 'brew_nascent_soul_nurturing_pill',
    actionGroup: 'alchemy',
    name: '炼培婴丹',
    cost: NASCENT_SOUL_NURTURING_PILL_COST,
    output: {},
    cooldown: 60,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_nascent_soul_nurturing_pill'],
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'home',
    },
  },
take_nascent_soul_nurturing_pill: {
    id: 'take_nascent_soul_nurturing_pill',
    actionGroup: 'alchemy',
    name: '服培婴丹',
    cost: { nascentSoulPills: 1 },
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_nascent_soul_nurturing_pill'],
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'home',
    },
  },
study_nascent_soul_separation_formula: {
    id: 'study_nascent_soul_separation_formula',
    actionGroup: 'alchemy',
    name: '辨出窍方',
    cost: { essence: 45, herbs: 8, insight: 9 },
    output: {},
    cooldown: 45,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_nascent_soul_separation_pill'],
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'home',
    },
  },
brew_nascent_soul_separation_pill: {
    id: 'brew_nascent_soul_separation_pill',
    actionGroup: 'alchemy',
    name: '炼出窍丹',
    cost: NASCENT_SOUL_SEPARATION_PILL_COST,
    output: {},
    cooldown: 65,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_nascent_soul_separation_pill'],
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'home',
    },
  },
take_nascent_soul_separation_pill: {
    id: 'take_nascent_soul_separation_pill',
    actionGroup: 'alchemy',
    name: '服出窍丹',
    cost: { nascentSoulPills: 1 },
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_nascent_soul_separation_pill'],
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'home',
    },
  },
study_nascent_soul_protection_formula: {
    id: 'study_nascent_soul_protection_formula',
    actionGroup: 'alchemy',
    name: '辨护婴方',
    cost: { essence: 40, herbs: 7, insight: 8 },
    output: {},
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_nascent_soul_protection_pill'],
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'home',
    },
  },
brew_nascent_soul_protection_pill: {
    id: 'brew_nascent_soul_protection_pill',
    actionGroup: 'alchemy',
    name: '炼护婴丹',
    cost: NASCENT_SOUL_PROTECTION_PILL_COST,
    output: {},
    cooldown: 60,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_nascent_soul_protection_pill'],
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'home',
    },
  },
take_nascent_soul_protection_pill: {
    id: 'take_nascent_soul_protection_pill',
    actionGroup: 'alchemy',
    name: '服护婴丹',
    cost: { nascentSoulPills: 1 },
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_nascent_soul_protection_pill'],
      requiredRealm: Realm.NascentSoul,
      requiredLocation: 'home',
    },
  },
study_spirit_transform_formula: {
    id: 'study_spirit_transform_formula',
    actionGroup: 'alchemy',
    name: '辨化神丹方',
    cost: { essence: 50, herbs: 9, insight: 10 },
    output: {},
    cooldown: 45,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_spirit_transform_pill'],
      requiredRealm: Realm.SpiritTransformation,
      requiredLocation: 'home',
    },
  },
brew_spirit_transform_pill: {
    id: 'brew_spirit_transform_pill',
    actionGroup: 'alchemy',
    name: '炼化神丹',
    cost: SPIRIT_TRANSFORM_PILL_COST,
    output: {},
    cooldown: 70,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_spirit_transform_pill'],
      requiredRealm: Realm.SpiritTransformation,
      requiredLocation: 'home',
    },
  },
take_spirit_transform_pill: {
    id: 'take_spirit_transform_pill',
    actionGroup: 'alchemy',
    name: '服化神丹',
    cost: { spiritTransformPills: 1 },
    output: {},
    cooldown: 25,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_spirit_transform_pill'],
      requiredRealm: Realm.SpiritTransformation,
      requiredLocation: 'home',
    },
  },
study_spirit_transform_fire_formula: {
    id: 'study_spirit_transform_fire_formula',
    actionGroup: 'alchemy',
    name: '辨化火丹方',
    cost: { essence: 55, herbs: 10, insight: 12 },
    output: {},
    cooldown: 50,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_spirit_transform_fire_pill'],
      requiredRealm: Realm.SpiritTransformation,
      requiredLocation: 'home',
    },
  },
brew_spirit_transform_fire_pill: {
    id: 'brew_spirit_transform_fire_pill',
    actionGroup: 'alchemy',
    name: '炼化火丹',
    cost: SPIRIT_TRANSFORM_FIRE_PILL_COST,
    output: {},
    cooldown: 75,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_spirit_transform_fire_pill'],
      requiredRealm: Realm.SpiritTransformation,
      requiredLocation: 'home',
    },
  },
take_spirit_transform_fire_pill: {
    id: 'take_spirit_transform_fire_pill',
    actionGroup: 'alchemy',
    name: '服化火丹',
    cost: { spiritTransformPills: 1 },
    output: {},
    cooldown: 25,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_spirit_transform_fire_pill'],
      requiredRealm: Realm.SpiritTransformation,
      requiredLocation: 'home',
    },
  },
study_integration_formula: {
    id: 'study_integration_formula',
    actionGroup: 'alchemy',
    name: '辨合体丹方',
    cost: { essence: 60, herbs: 12, insight: 14 },
    output: {},
    cooldown: 50,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_integration_pill'],
      requiredRealm: Realm.Integration,
      requiredLocation: 'home',
    },
  },
brew_integration_pill: {
    id: 'brew_integration_pill',
    actionGroup: 'alchemy',
    name: '炼合体丹',
    cost: INTEGRATION_PILL_COST,
    output: {},
    cooldown: 80,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_integration_pill'],
      requiredRealm: Realm.Integration,
      requiredLocation: 'home',
    },
  },
take_integration_pill: {
    id: 'take_integration_pill',
    actionGroup: 'alchemy',
    name: '服合体丹',
    cost: { integrationPills: 1 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_integration_pill'],
      requiredRealm: Realm.Integration,
      requiredLocation: 'home',
    },
  },
study_integration_body_formula: {
    id: 'study_integration_body_formula',
    actionGroup: 'alchemy',
    name: '辨归体丹方',
    cost: { essence: 65, herbs: 13, insight: 15 },
    output: {},
    cooldown: 55,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_integration_body_pill'],
      requiredRealm: Realm.Integration,
      requiredLocation: 'home',
    },
  },
brew_integration_body_pill: {
    id: 'brew_integration_body_pill',
    actionGroup: 'alchemy',
    name: '炼归体丹',
    cost: INTEGRATION_BODY_PILL_COST,
    output: {},
    cooldown: 85,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_integration_body_pill'],
      requiredRealm: Realm.Integration,
      requiredLocation: 'home',
    },
  },
take_integration_body_pill: {
    id: 'take_integration_body_pill',
    actionGroup: 'alchemy',
    name: '服归体丹',
    cost: { integrationPills: 1 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_integration_body_pill'],
      requiredRealm: Realm.Integration,
      requiredLocation: 'home',
    },
  },
study_mahayana_formula: {
    id: 'study_mahayana_formula',
    actionGroup: 'alchemy',
    name: '辨大乘丹方',
    cost: { essence: 70, herbs: 15, insight: 18 },
    output: {},
    cooldown: 60,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_mahayana_pill'],
      requiredRealm: Realm.Mahayana,
      requiredLocation: 'home',
    },
  },
brew_mahayana_pill: {
    id: 'brew_mahayana_pill',
    actionGroup: 'alchemy',
    name: '炼大乘丹',
    cost: MAHAYANA_PILL_COST,
    output: {},
    cooldown: 90,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_mahayana_pill'],
      requiredRealm: Realm.Mahayana,
      requiredLocation: 'home',
    },
  },
take_mahayana_pill: {
    id: 'take_mahayana_pill',
    actionGroup: 'alchemy',
    name: '服大乘丹',
    cost: { mahayanaPills: 1 },
    output: {},
    cooldown: 35,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_mahayana_pill'],
      requiredRealm: Realm.Mahayana,
      requiredLocation: 'home',
    },
  },
study_mahayana_enlightenment_formula: {
    id: 'study_mahayana_enlightenment_formula',
    actionGroup: 'alchemy',
    name: '辨悟道丹方',
    cost: { essence: 80, herbs: 18, insight: 22 },
    output: {},
    cooldown: 70,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_mahayana_enlightenment_pill'],
      requiredRealm: Realm.Mahayana,
      requiredLocation: 'home',
    },
  },
brew_mahayana_enlightenment_pill: {
    id: 'brew_mahayana_enlightenment_pill',
    actionGroup: 'alchemy',
    name: '炼悟道丹',
    cost: MAHAYANA_ENLIGHTENMENT_PILL_COST,
    output: {},
    cooldown: 100,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_mahayana_enlightenment_pill'],
      requiredRealm: Realm.Mahayana,
      requiredLocation: 'home',
    },
  },
take_mahayana_enlightenment_pill: {
    id: 'take_mahayana_enlightenment_pill',
    actionGroup: 'alchemy',
    name: '服悟道丹',
    cost: { mahayanaPills: 1 },
    output: {},
    cooldown: 35,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_mahayana_enlightenment_pill'],
      requiredRealm: Realm.Mahayana,
      requiredLocation: 'home',
    },
  },
study_tribulation_protection_formula: {
    id: 'study_tribulation_protection_formula',
    actionGroup: 'alchemy',
    name: '辨护劫丹方',
    cost: { essence: 80, herbs: 20, insight: 25 },
    output: {},
    cooldown: 70,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_tribulation_protection_pill'],
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'home',
    },
  },
brew_tribulation_protection_pill: {
    id: 'brew_tribulation_protection_pill',
    actionGroup: 'alchemy',
    name: '炼护劫丹',
    cost: TRIBULATION_PROTECTION_PILL_COST,
    output: {},
    cooldown: 100,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_tribulation_protection_pill'],
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'home',
    },
  },
take_tribulation_protection_pill: {
    id: 'take_tribulation_protection_pill',
    actionGroup: 'alchemy',
    name: '服护劫丹',
    cost: { tribulationPills: 1 },
    output: {},
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_tribulation_protection_pill'],
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'home',
    },
  },
study_tribulation_soul_formula: {
    id: 'study_tribulation_soul_formula',
    actionGroup: 'alchemy',
    name: '辨安魂丹方',
    cost: { essence: 90, herbs: 22, insight: 28 },
    output: {},
    cooldown: 75,
    riskProbability: 0,
    conditions: {
      forbiddenFlags: ['known_recipe_tribulation_soul_pill'],
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'home',
    },
  },
brew_tribulation_soul_pill: {
    id: 'brew_tribulation_soul_pill',
    actionGroup: 'alchemy',
    name: '炼安魂丹',
    cost: TRIBULATION_SOUL_PILL_COST,
    output: {},
    cooldown: 110,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['known_recipe_tribulation_soul_pill'],
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'home',
    },
  },
take_tribulation_soul_pill: {
    id: 'take_tribulation_soul_pill',
    actionGroup: 'alchemy',
    name: '服安魂丹',
    cost: { tribulationPills: 1 },
    output: {},
    cooldown: 40,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['has_tribulation_soul_pill'],
      requiredRealm: Realm.Tribulation,
      requiredLocation: 'home',
    },
  }
};
