import { Action, Realm } from '../../game/types';

export const SECT_ACTIONS: Record<string, Action> = {
sect_chore: {
    id: 'sect_chore',
    actionGroup: 'sect',
    name: '外门杂务',
    cost: { essence: 20 },
    output: { coins: 1, insight: 1 },
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'outer_gate',
    },
    upgradeTier: 'daily',
    upgradeCondition: { flag: 'completed_sect_errand' },
  },
sect_errand: {
    id: 'sect_errand',
    actionGroup: 'sect',
    name: '领外门短差',
    cost: { essence: 40 },
    output: { coins: 4, herbs: 1, insight: 1 },
    cooldown: 50,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['heard_outer_gate_rules'],
      requiredLocation: 'outer_gate',
      requiredRealm: Realm.QiCondensation,
    },
  },
sect_supply: {
    id: 'sect_supply',
    actionGroup: 'sect',
    name: '领外门供给',
    cost: { essence: 20 },
    output: { herbs: 3, coins: 2 },
    cooldown: 80,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['completed_sect_errand'],
      requiredLocation: 'outer_gate',
      requiredRealm: Realm.QiCondensation,
    },
    upgradeTier: 'automated',
    upgradedFrom: 'sect_chore',
    upgradeCondition: { flag: 'sect_rank_inner' },
  },
sect_roll_call: {
    id: 'sect_roll_call',
    actionGroup: 'sect',
    name: '外门点卯',
    cost: { essence: 10 },
    output: { insight: 1 },
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['outer_gate_registered'],
      requiredLocation: 'outer_gate',
      requiredRealm: Realm.QiCondensation,
    },
  },
sect_patrol: {
    id: 'sect_patrol',
    actionGroup: 'sect',
    name: '领外门巡值',
    cost: { essence: 35 },
    output: { coins: 3, herbs: 1, insight: 1 },
    cooldown: 60,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['attended_outer_gate_roll_call'],
      requiredLocation: 'outer_gate',
      requiredRealm: Realm.QiCondensation,
    },
  },
listen_lesson: {
    id: 'listen_lesson',
    actionGroup: 'sect',
    name: '听课',
    cost: { essence: 15 },
    output: { insight: 1 },
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'outer_gate',
    },
  },
seek_foundation_guardian: {
    id: 'seek_foundation_guardian',
    actionGroup: 'sect',
    name: '求护法',
    cost: { essence: 20, coins: 8, insight: 2 },
    output: {},
    cooldown: 30,
    riskProbability: 0,
    conditions: {
      requiredFlags: ['bottleneck_foundation'],
      forbiddenFlags: ['foundation_guardian', 'foundation_guardian_account_open'],
      requiredLocation: 'outer_gate',
      requiredRealm: Realm.QiCondensation,
    },
  },
inner_gate_task: {
    id: 'inner_gate_task',
    actionGroup: 'sect',
    name: '领内门任务',
    cost: { essence: 30 },
    output: { coins: 2, insight: 1 },
    cooldown: 60,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'inner_gate',
      requiredFlags: ['sect_rank_inner'],
    },
  },
report_task_completion: {
    id: 'report_task_completion',
    actionGroup: 'sect',
    name: '复命',
    cost: { essence: 10 },
    output: {},
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'inner_gate',
      requiredFlags: ['has_active_sect_task'],
    },
  },
attend_sect_ceremony: {
    id: 'attend_sect_ceremony',
    actionGroup: 'sect',
    name: '参加宗门典礼',
    cost: { essence: 15 },
    output: { insight: 5 },
    cooldown: 100,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.FoundationEstablishment,
      requiredLocation: 'inner_gate',
      requiredFlags: ['sect_rank_inner'],
    },
  },
attend_ceremony: {
    id: 'attend_ceremony',
    actionGroup: 'sect',
    name: '参加典礼',
    cost: { coins: 3 },
    output: { insight: 2 },
    cooldown: 20,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'sect_hall',
      requiredRealm: Realm.FoundationEstablishment,
    },
  },
receive_mission: {
    id: 'receive_mission',
    actionGroup: 'sect',
    name: '领取任务',
    cost: { essence: 5 },
    output: { coins: 3, insight: 1 },
    cooldown: 5,
    riskProbability: 0,
    conditions: {
      requiredLocation: 'sect_hall',
      requiredFlags: ['sect_rank_outer'],
    },
  },
patrol_seal: {
    id: 'patrol_seal',
    actionGroup: 'exploration',
    name: '巡守封印',
    cost: { essence: 25 },
    output: { coins: 8, insight: 2 },
    cooldown: 15,
    riskProbability: 0,
    conditions: {
      requiredRealm: Realm.GoldenCore,
      requiredLocation: 'demon_seal_ground',
    },
  }
};
